### ISSUE TITLE
UI Design for Game/Loadout Diagnostics

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1002]
See #327 for parent Epic

Design UI and UX for viewing warnings or problems detected by the app regarding the Game, Loadout, or App state.

Diagnostic messages can have:
- Severity (Suggestion, Warning, Critical)
- Summary
- Details
- ~Timestamp~ We refresh them all at the same time every time loadout changes, so this isn't helpful

Examples could be:
- Mod incompatibility
- Missing dependency
- Mod not compatible with game version
- Circular dependencies between mods.

Each diagnostic would have a Short description and a long description.
The idea is that the long description would be Rich Text, supporting links that reference Pages or views inside the App.
E.g.:
```md
Mod ('{modA.Name}')[{Open modA ModInformation page}] is missing required dependency ('{missingDependency}')[{Open Nexus page}]
```

For some problems, the App might be able to provide automatized solutions, but not all of them.
We could use the rich links to also support user actions such as starting an automatic fix. 
Alternatively we would need to be able to add buttons to allow users to take action or choose between multiple solutions.

To display the Markdown rich text, we will need a Style for it: 
- [ ] #943 

## Design

[Figma link](https://www.figma.com/file/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BADiagnostics?type=design&node-id=1%3A2953&mode=design&t=I8MMubXlLfVXEQKS-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/aa0cecf3-6fc8-4e81-8aeb-0ef464649f1d)

**Comment by adykrni** [comment]
hey, can I contribute to this?
