### ISSUE TITLE
Add "Installation" section docs

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1006]
Add a section to the docs explaining how to install the App. It should have subsections for each OS type we support: Windows, Linux, and macOS. These subsections should contain a list of requirements, like the .NET runtime, as well as notes on OS-specific functionality.

**Comment by MattSturgeon** [comment]
It'd be great to have both **from source** and **binary** instructions & requirements.

Including this directly in the README might make sense too.
