### ISSUE TITLE
Stardew Vally Launch button throws exception if SMAPI is not installed

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1012]
Stardew Valley game has `"StardewModdingAPI.exe"` set as the primary executable on windows, which obviously fails if SMAPI was not installed.

Even then, my understanding was that SMAPI was supposed to replace the main exe, so perhaps it should always be `Stardew Valley.exe` on windows?

**Comment by erri120** [comment]
Our version of the SMAPI installer installs and overrides different files depending on the operating system and game store. Our installer follows the official installer and the wiki closely. However, I believe we can simplify it.

Our SMAPI installer currently overrides the "launch file" of Stardew Valley on Linux, macOS, and Windows when using the Xbox Game Pass:

| OS | Store | Overrides Launch File? |
|---|---|---|
| Linux | All | ✅  |
| macOS | All | ✅ |
| Windows | Steam | 🚫 |
| Windows | Other | ✅  |

I believe the official SMAPI installer doesn't override `Stardew Valley.exe` on Windows with Steam to allow players to run the vanilla game without having to uninstall SMAPI. However, we don't need this "feature". We can just override `Stardew Valley.exe` with `StardewModdingAPI.exe` on Windows without issue.
