### ISSUE TITLE
Add faster, potentially unsafe,`RelativePath.Join()` implementation

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1038]
# Improvement

## Currently 
Currently the `Join` method is used in hot paths to concatenate relative paths.
`Join` is apparently slow due to path sanitization checks.

## We want
A faster implementation of Join or an alternative that can be used when the paths are known to be safe and performance is critical.

## Details
To avoid misuse with unsafe strings, check if it is possible to limit usage with only Explicit `RelativePaths` (which hopefully are already sanitized)

**Comment by erri120** [comment]
Sanitation checks are debug-only.

**Comment by Al12rs** [comment]
@Sewer56 That good enough for you? Or do you want still faster?

**Comment by erri120** [comment]
Do you have any benchmarks or profiling sessions that show a performance bottleneck in the `RelativePath.Join` method in a Release build?

**Comment by Sewer56** [comment]
The context is pretty simple:
- I was doing a [fast append](https://github.com/Nexus-Mods/NexusMods.App/blob/4ba779ea2e031e2d9d8fcbed4070c279cbcecf96/src/Abstractions/NexusMods.Abstractions.GameLocators/Trees/GamePathNode.cs#L103) in tree creation. (Saves around 20ms IIRC on my machine for 50+k file loadout).
- @Al12rs thought 'if you're having to do this, shouldn't the Paths library be improved'?
- I mention 'well yeah, there is a Join method, it's good, but for this specific hot path, we can do better, we could maybe have an unsafe API for raw string concat, I dunno, put an Issue, maybe we can change it in the future.'. 
- Here we are.

**Comment by erri120** [comment]
> I was doing a fast append in tree creation. (Saves around 20ms IIRC on my machine for 50+k file loadout).

The reason we have a paths library is so we use the same code everywhere and run off doing custom implementations.

I'm closing this issue for now, we can go back to this if we have benchmarks or profiling sessions that show places for improvements.

**Comment by Al12rs** [comment]
So @Sewer56 use `Join` in the code, don't keep the fast append

**Comment by Sewer56** [comment]
> So @Sewer56 use `Join` in the code, don't keep the fast append

Why would I willingly make our performance worse though?

**Comment by Al12rs** [comment]
Because the whole point of the Paths library is that of avoiding rolling custom code everywhere, as @erri120 pointed out before.
If you have a faster join implementation then I can reopen this and change the description.

**Comment by Sewer56** [comment]
That method would be called something like `.UnsafeAppend()`. Our actual `.Join` method is fine, I didn't want an alternative to it, just wanted a fast multi string concat.

I'll throw it in the API down the road, don't worry about that part.

**Comment by erri120** [comment]
> Why would I willingly make our performance worse though? Said code follows the Paths library rules in ADR.

Because it makes the code less maintainable. If you want to do something with paths, use the path library.
