### ISSUE TITLE
App Activity Indicator - Stardew test candidate

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1104]
As a user of the App
I want to know when the app is doing something
So that I know to wait and I know not to close it. 

Currently its hard to tell when adding games to be managed that the game is in the process of being added. 

The method for indicating app activity will potentially be used in the future for indicating other in progress activity.

**Comment by Al12rs** [comment]
See:
- #901 
- #1035 
- #1069 

From discussions with design the general approach will be that of using custom loading indicator for each situation, but #901 should help as stop gap to getting there.

**Comment by Al12rs** [comment]
Closing as duplicate, refer to #901
