### ISSUE TITLE
Apply/Ingest - Ingesting file deletions does nothing if there are unapplied revisions

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1110]
As the title said, currently doing an ingest of file deletions while there are unapplied revisions will result in nothing happening.

The reason is that the change is merged into the last applied loadouot, and then the unapplied changes are merged on top of it. Unapplied changes still contain the deleted files, so they show up again in the final result.

Since we are only able to ingest as part of an apply operation, and Apply button is only available when there are unapplied loadout revisions, it is impossible to ingest deletions, except as part of running the game, which does an ingest on close.

**Comment by Al12rs** [comment]
This is blocked until we decide how we want to handle ingested data:
- #990

**Comment by halgari** [comment]
It is also unclear if we want to support this usecase at all. The way we get into this situation is if the user deletes files in their game folder, and also deletes from their loadout, without doing any sort of sync between the two. Data is not lost in this process and the state is not unrecoverable, it's simply that the deletes in the folder are reverted. So I'm inclined to say this is a non issue as it's a unsupported workflow that doesn't result in data loss. 

So I think we'll table this one for now, until we get some user feedback and figure out how much of a pain point it is for users.

**Comment by Al12rs** [comment]
> The way we get into this situation is if the user deletes files in their game folder, and also deletes from their loadout

This happens even if the user disables and re-enables a mod (no-op) and then tries to ingest outside changes.
Deletions are ignored, other changes are ingested correctly.

**Comment by Al12rs** [comment]
This was fixed with the introduction of Reified deletes
