### ISSUE TITLE
v0.4 Issue - Launch SMAPI with console enabled on Windows

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1135]
# Bug Report

## Summary
Apparently when you run smapi you are supposed to get a Console, but starting it from the App does not produce it.
We might need to use https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.useshellexecute?view=net-8.0 to allow the console to open.

## Steps to reproduce
Install SMAPI, Apply, hit Launch button.

## What is the expected behaviour?
A console and the game both open.

## Other information
The console is apparently useful and desirable to have for modding, so no need to have a setting to enable or disable it.

**Comment by erri120** [comment]
Works fine on Linux.

**Comment by Pickysaurus** [comment]
https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/66525d17-88fe-418d-a452-debf54ea68b7

Comparison between Vortex and the App in Windows 11

**Comment by erri120** [comment]
See https://github.com/Tyrrrz/CliWrap/discussions/114

**Comment by Al12rs** [comment]
Yeah, we were only collecting the stderr and stdout to print them in the log in case the program exit code wasn't 0. 
But allowing programs to start the console seems more useful, especially since many of these can be interacted with by users to execute commands.
