### ISSUE TITLE
Consider the best way to visualise SMAPI mods with multiple modules

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1146]
# Spike

## Proposal
When a SMAPI mod contains multiple sub-mods. The current logic of the app will split this into x entries in the loadout, which is technically correct but could have the side effect of confusing users as they install 1 mod and it "explodes" into several entries. We should talk to design/product to see if this is the right approach. The other thing to consider is what happens when we come to update these mods as all of the entries need to change. 

As I see it there are a few options (this is not an exhaustive list):
1. Continue to show all SMAPI sub-mods as separate entries 
2. Show the mod as a single entry according to the archive the user installed
3. Allow sub-mods to be "nested" under a single header (aka show both). 

## Impact
Core UX for Stardew Valley modders.

## Supporting Information
_(Include any supporting screenshots etc to support the above)_

**Comment by Sewer56** [comment]
Disk:

```
Mods
├── FlatOut
│   ├── flatout2.packs.goofyahhmod
│   ├── flatout2.utils.modloader
│   ├── flatout2.utils.mpnamechange
│   ├── flatout2.utils.richpresence
│   └── flatout2.utils.zpatch
├── <other unrelated mod 1>
├── <other unrelated mod 2>
└── <other unrelated mod 3>
```

![311567858-9ae3eefc-eaaf-4181-8ff4-e24ecf0e7b06](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/f59ab775-17d1-4caa-99af-13093527a6bb)

Reloaded-II for reference. Since it's similar to SMAPI in terms of how things are laid out.

**Comment by Sewer56** [comment]
>  wonder why most mode managers only display mods at a single level

If you were to ask me, I think it's probably a combination of:

- Combining Trees with DataGrid(s) is non-trivial in some UI frameworks.
- Not having an expectation of user juggling 100+ mods.

I find that most non-mainstream games will usually have users run somewhere in the range of 20-50 mods.

**Comment by Pickysaurus** [comment]
I don't know if we want to think more about the definition of a "Mod" in this case. For quite a few games there can be a lot of "Mods" per downloaded archive. Think of Bethesda mods with lots of plugins or Unreal Engine 4 mods with lots of PAKs

**Comment by Continous** [comment]
It's also worth noting that mod distribution seems to very much prefer the nesting approach where basically all mods utilize folder structure as a grouping method. IE a mod will have a root folder with all the necessary components, then subfolders with things like options and patches. And this is more and more true as expected user interaction with the actual files increases.

**Comment by Pickysaurus** [comment]
I'm looking for real-world examples of Stardew Valley mods where displaying all the modules would be a benefit to the user.

I briefly discussed this topic with FlashShifter (author of the biggest SDV mod) on Discord and in his case (and every other case I've seen so far) disabling one "submodule" of his mod would just break it. 
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/e644c674-3d66-4306-a396-fc39dc4109cc)

**Comment by Pickysaurus** [comment]
Example use case for disabling parts of a mod when using this mod and translation together:
- https://www.nexusmods.com/stardewvalley/mods/5305
- https://www.nexusmods.com/stardewvalley/mods/9394


The base mod has 3 parts:
- `RaisedGardenBeds`: a C# SMAPI Mod
- `[CP] RaisedGardenBeds`: a Content Pack for the Content Patcher that adds English Translations for the C# SMAPI Mod
- `[RGB] RaisedGardenBeds`: a Content Pack for the C# SMAPI Mod. The C# SMAPI Mod also acts as a Content Pack Framework

The translation has a single part:
- `[CP] RaisedGardenBeds - German`: German text for the mod. 

If you install the translation then you don't need to have `[CP] RaisedGardenBeds` active since that provides English translations.

Needs verifying that leaving the English things open actually causes issues.

**Comment by captainsandypants** [comment]
@Pickysaurus it doesn't seem like this is needed for Stardew Valley but will it be needed for other games? Is it rare enough that it could be a setting the user has to enable? I want to avoid cluttering the UI with this if possible.
