### ISSUE TITLE
NXM links stop working after exiting AppImage (0.4)

### ISSUE THREAD

**Issue by Slayer5934** [Nexus-Mods/NexusMods.App#1149]
# Bug Report

## Summary
When running the AppImage version and logging in, it correctly associates the file type link for that run, however if you exit the app and relaunch the "mount fuse" is not longer found and nxm links no longer work.

## Steps to reproduce
Launch the app image version
Log in
(nxm links work for downloading)
Exit app image
Relaunch
(nxm links no longer work) "Could not find the program '/tmp/.mount_NexusMBprMex/usr/bin/NexusMods.App'"

## What is the expected behaviour?
NXM links to continue working.

## Other information
Arch (EndeavourOS, KDE Plasma)

**Comment by erri120** [comment]
We'd probably wanna use [`APPIMAGE`](https://docs.appimage.org/packaging-guide/environment-variables.html#id2) environment variable to point to the file.
