### ISSUE TITLE
Download Library - Delete Mod

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1156]
As a user 
I want to be able to permanently delete a mod from the download library page
So that I can remove the mod permanently from my hard drive

This should be the only place in the App where you can permanently delete a mod from disk. (discuss)

A/C
If the mod is still turned on for any loadouts a popup lets the user know that they are about to permanently about to delete the mod and remove it from any loadouts. 
User should have to accept prompt before the app permanently deletes any mods. 

- #1154

**Comment by Al12rs** [comment]
See also #403
