### ISSUE TITLE
Download Library - Add mod to loadout

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1157]
As a user
I want to be able to add a mod to a loadout from the download library page
So that I don't have to navigate to the particular loadout first

This is kind of a QoL thing that will allow users to add mods to loadouts from the download library so they don't have to go to the loadout first. They will still be able to add mods via the loadout pages but they should be able to do it here too. 

- - https://github.com/Nexus-Mods/NexusMods.App/issues/1154

**Comment by Al12rs** [comment]
See also #402

**Comment by Al12rs** [comment]
Implemented in #1268
