### ISSUE TITLE
Link to relevant SDK version

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#1162]
# Improvement

## Currently 

[Getting Started](https://nexus-mods.github.io/NexusMods.App/GettingStarted/) says "Download the Latest [.NET SDK](https://dotnet.microsoft.com/en-us/download/dotnet/7.0)", but the link is to .NET 7.0.

## We want

Should link to whatever version of the .NET SDK is being used by the GitHub CI build.

**Comment by LukeNexusMods** [comment]
The link should now be pointing at the correct .net version.

**Comment by l0b0** [comment]
Um, .NET SDK 8 isn't the latest either. shouldn't the text instead say the specific version?

**Comment by erri120** [comment]
> Um, .NET SDK 8 isn't the latest either. shouldn't the text instead say the specific version?

.NET 8 is the latest "stable" .NET release. The new .NET 9 is still in preview.
