### ISSUE TITLE
Epic: Refactor the datamodel to use MnemonicDB

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#1173]
# Epic
Rewrite the backend of the app to use the new database https://github.com/Nexus-Mods/NexusMods.MnemonicDB

## Outline
Switch the following entities (and sub-entities) over to MnemonicDB

* [ ] AModFile
  * [ ] AStaticModFile
  * [ ] EmptyDirectory
  * [ ] GeneratedTestFile
  * [ ] PluginOrderFile
  * [ ] SortedFile
  * [ ] TestGeneratedFile
* [x] ArchivedFiles
* [x] DiskState
* [ ] CachedGeneratedFileData (no longer used, delete it)
* [ ] CachedModSourtRules
* [ ] DataStoreSettingsBackendEntity
* [x] DownloadAnalysis
* [ ] DownloaderState
* [ ] JWTTokenEntity
* [ ] Loadout
* [ ] ManuallyAddedGame
* [ ] Mod
* [ ] NexusModFile
* [ ] WindowData

**Comment by Al12rs** [comment]
This can be closed I think
