### ISSUE TITLE
[Investigate] Discuss and investigate if we want to reify deletes

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#1176]
# Spike

Most mod managers express deletes as the removal of data from the loadout. If you add a mod with 10 files, and delete 2, the manager will only show 8 files. Do we want to reify this information by showing a layer (or mod) with 10 files, then 2 files in another mod/layer that are marked as "deletes". This would allow us to easily overlay sets of changes on mods instead of modifying the mod itself. 

We should discuss this and figure out our final design.

**Comment by Al12rs** [comment]
### Advantages of reifying deletes:
- Can treat a set of outside changes as a single mod, without needing to modify or affect existing mods. Keeping the changes isolated.
- Without this it would be impossible to remove a Vanilla file without also replacing it or without modifying the "GameFiles" mod, which should instead ideally remain unchanged.
- This allows us to support mods that want to remove or rename vanilla files (e.g. removing startup logo videos from games and similar)

### Disadvantages:
- Added complexity in the code, mods are not just a collection of files but can also remove files now
- The concept needs to be communicated and made clear to the user through the UI.


### UI that would be affected:
- Mod contents file tree (how to show deletes?)
- Conflicts resolution view (showing a file delete that wins against other files)
- Mod history (show that a _delete_ was _added_ , or that a _delete_ was _removed_, could be quite tricky)

There is also the concept of what the delete is going to affect:
- Does it affect all the layers that have a lower priority (so all the mods that came before it)?
- Does it only affect one mod? Like a patch
Do we want both? How do we distinguish the two cases in the UI?

**Comment by halgari** [comment]
Other things affected:

* Diagnostics need to see the flattened list, would they need to see the modlist but also the flattened loadout
  * Would likely need a lot of boilerplate APIs to help ease the problem of switching between mods and game folders (game-level mods)
  * This problem exists already and needs fast APIs that allow diagnostics to query this information.
  * This is pretty advanced for SDV, but will matter more with more complex games (Skyrim)

**Comment by halgari** [comment]
Decisions from 4/8/2024:

* We want reified deletes
* Implement them as a new file type that does not have internal data (or a hash)
* The Apply/Ingest logic should be one of the few places with specialized logic for these files. Apply does *not* install these files (it deletes what's on disk), Ingest, creates these files for anything deleted from the loadout. 
* Would show up in the mod contents as a normal file, perhaps with a special icon or marker saying it's a "delete".
