### ISSUE TITLE
Diagnostics - Upgrade to SMAPI 4.0.6

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1181]
https://github.com/Pathoschild/SMAPI/releases/tag/4.0.6:

> 4.0.6 mainly lets mods set a min supported game version, to reduce issues from players who still have old game versions.

Might want new diagnostics for this.

Requires #1231.

**Comment by LukeNexusMods** [comment]
Do you think we should create an epic for diagnostics and keep adding this work like this into it? Or would you class this as an v0.4 issue?

**Comment by erri120** [comment]
> Do you think we should create an epic for diagnostics and keep adding this work like this into it? Or would you class this as an v0.4 issue?

This isn't a bug or anything that's broken. This is almost a feature request to add a new diagnostic. I'm not sure what you mean by creating an epic for diagnostics, and I'm also not sure what v0.4 represents atm.

**Comment by LukeNexusMods** [comment]
An Epic in the github sense is like a feature that we would want to implement which holds links to all the different issues that are related to it. 

v0.4 issue list is a place for all the issues with 0.4 to be gathered together. 

Ill add a new item to link any diagnostic work to.

**Comment by erri120** [comment]
Requires #1231.

**Comment by erri120** [comment]
Done in #1265.
