### ISSUE TITLE
Loadouts - Make "GameFilesCategory" mods non user interactable

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1195]
When turning off your game files and ingesting it prevents you from being able to launch the game again and then creates another set of game files. 

To stop this from happening please can we remove the switch from Game Files so that they cannot be disabled from the loadouts page?

- #397

**Comment by Al12rs** [comment]
Users should:
- Not be allowed to Disable/Enable these mods, they should always be force enabled
- Not be allowed to Remove these mods

**Comment by LukeNexusMods** [comment]
@captainsandypants This is the ticket that was raised for the game files. 

As part of this do you want to include any small changes to how they look in the list?

**Comment by halgari** [comment]
Instead of locking it down, so far we have no use for these items in the grid, so let's implement this as a filter on the grid that removes the view completely.

**Comment by Al12rs** [comment]
I personally have a use, and that is looking at what is inside the Game Files. That is very useful for trying out the app and seeing whether it is doing things correctly.

**Comment by Al12rs** [comment]
We should still make the mod non user interactable (no disable, no delete) in case it is enabled in the settings
