### ISSUE TITLE
Loadouts - Store "Vanilla" game state separately to be able to roll back to it or create new profiles

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1197]
For details see:
- #1166 

## Summary:
We need to be able to revert the game to a vanilla state, to do this we need to know what the vanilla state is.
We need this for:
- Removing a loadout (uninstalling all the mods) #399 
- Creating multiple loadout without ingesting previous loadouts #982 
- Managing game updates and allowing users to switch between them

## Implementation:
- Use the state of the game when the game is managed the first time as the base game state.
- Store this state in the `DiskStateRegistry`
- Provide an API to perform a hard reset of the game folders to a pre-cached `DiskStateRegistry` entry. 

## Future work
- Don't worry about how this data will be used, we will leverage this feature in the future, for now we just need the `Hard Reset` feature

**Comment by Al12rs** [comment]
Could this be implemented as a Special loadout instead? 
It would mean that we could reuse backend operations between loadouts instead of having a separate thing.
The main thing is that we need to be able to update this, copy it, modify it, etc.

Having it as a loadout would allow us to even potentially expose it to users to edit as if it were a normal loadout if we needed.

Something to consider.

**Comment by LukeNexusMods** [comment]
> Could this be implemented as a Special loadout instead? It would mean that we could reuse backend operations between loadouts instead of having a separate thing. The main thing is that we need to be able to update this, copy it, modify it, etc.
> 
> Having it as a loadout would allow us to even potentially expose it to users to edit as if it were a normal loadout if we needed.
> 
> Something to consider.

The unmodded game state behaves like a mod?

**Comment by Al12rs** [comment]
The problem of the mod approach is that each loadout should be isolated. And we want to have multiple versions of the game state, so you would have to have multiple versions of the game files mod, shared across all loadouts.

If we treat it as a Loadoout instead, we can have multiple versions by having multiple loadouts. 
It is a bit of a crazy idea. I thought to share it in case it resonated with somebody else
