### ISSUE TITLE
Loadouts - Tech debt: Cleanup how loadout revisions are represented in code

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1204]
# Tech debt

## Currently 
We have:
- `Loadout`
- `LoadoutId`
- `IId` or `DataStoreId`
- `LoadoutMarker`

Apart from `LoadoutId` these don't have an intuitive mapping to actual loadouts as the users interact with them.
- `LoadooutId` identifies one loadout as users are familiar with them
- `Loadout` is an object representing a Loadout, but only at a specific moment in time. What we have been referring to as `LoadoutRevision` in speech and other places of the code. 
- `DataStoreId` is the Id identifying a particular LoadoutRevision
- `LoadoutMarker`, had to look at the code to check what this actually did, and it is an object that simplifies getting the latest `Loadout` of a certain `LoaodutId`. Basically it is supposed to offer convenience due to the revisions always changing.

These names are quite confusing and make contributing to the project harder for third parties, as well as confuse current devs.

## We want
Better names and potentially even reconsider how these are structured. 
We already need to touch this code for integrating our new DataStore MnemonicDB (#1173 ) so it could be an opportunity to make our code easier to understand.

## Suggested solutions
- `Loadout` -> `LoadoutRevision`
- `DataStoreId` -> `LoadoutRevisionId`
- `LoadoutMarker` -> `Loadout`: I would consider fleshing this out a bit more and using this more, but open to other suggestions.
- `LoadoutId` -> no change, this is clear enough.

There are other concepts like LoadoutRoots that might also need looking at.

Epic:
- https://github.com/Nexus-Mods/NexusMods.App/issues/397

**Comment by LukeNexusMods** [comment]
Is this something that would make contributing to the project more accessible? Are there any performance factors that might be affected by this?

**Comment by Al12rs** [comment]
No performance factors. 
Yes this would make our code easier to understand and thus make it more accessible to contributors.

**Comment by Sewer56** [comment]
As a random reference, even I made an error last Thursday.

I assumed that under the current system a certain value we stored was like a `git commit hash` (basically random unique number), when in actuality it was a unique identifier of an item in our database. Which led me to write code suboptimally.

Thankfully it was caught in code review.

**Comment by Sewer56** [comment]
Might be worth visiting as part of the move to MneumonicDB (Tim's Database Library with Event Sourcing).
Since at that point the code would be touched.

**Comment by Al12rs** [comment]
Handled with move to MnemonicDb
