### ISSUE TITLE
Download Library - UI

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1210]
Based on the discussion we had last week the design will take into account the 3 states that a mod can be in. 

- Downloaded - Not installed
- Installed and disabled
- Installed and enabled

Design will take the approach of having a download library page utilising the existing download page, an additional button to add mods to a loadout at which point they install. History of downloads will also be available.

Deleting mods does not remove from disk but disables them and removes from view. 

The discussion about how to remove from disk is part of the garbage collection epic. 

### Designs

https://www.figma.com/file/5LmVL8YpgDHFSFA76fgCZA/%F0%9F%93%B1Mod-library?type=design&node-id=2%3A1825&mode=design&t=zZbzsbWvLGDOXKsb-1

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/876f4516-3148-4f27-8e4b-7636fc84cf0e)

Create one version with add and the one version with the additional add duplicate button.

Epic:
- https://github.com/Nexus-Mods/NexusMods.App/issues/1154

**Comment by Al12rs** [comment]
Important note:
- Completed downloads view will initially only be available from within a Loadout Workspace:

This avoids the confusion for which Loadout the download will be installed to when clicking Install.

**Comment by Al12rs** [comment]
Suggested simplifications for initial implementation:
- Skip "Add All" and "Add Selected" buttons, we don't have functionality to queue the installation of multiple mods (wouldn't be impossible to add just not really worth it and no UI to support showing progress on this).
- Only have "Add" button. Skip "Add duplicate" variation.

**Comment by captainsandypants** [comment]
Let's keep "Add duplicate" to reinforce to the user that the add was successful and clicking the button again will now add a duplicate.

**Comment by halgari** [comment]
Having an "Add Duplicate" requires connecting downloads to installed mods.
Right now we don't do this and don't have an easy way to query this data,
so there is an extra step involved. I'm fine with this being broken up into
two PRs: one that adds the UI, the other that adds this link and the state
change to "Add Duplicate"

**Comment by Al12rs** [comment]
I don't particularly like "Duplicate" or "Copy" in this case either. If the original mod was modified, this would not add a duplicate or copy. If the mod goes through an installer with choices, the end result is unlikely to be a copy or a duplicate either. I would prefer "Add again" instead.

As Tim said, I would implement this in a second PR.

**Comment by captainsandypants** [comment]
"Add again" works, I'll update the design. And yeah, next PR it is.

**Comment by erri120** [comment]
Blocked by #1276.
