### ISSUE TITLE
More tests should have `RequiresNetworking`

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#1223]
# Improvement

## Currently 

Some tests require networking, but are not annotated as such.

## We want

`[Trait("RequiresNetworking", "True")]` annotations for tests which require networking.

**Comment by erri120** [comment]
As mentioned in #1222 

> The `RequiresNetworking` trait isn't very descriptive, but we're using this for tests that talk to the Nexus Mods API. A better name for the trait would be "RequiresNexusModsAPIKey".
