### ISSUE TITLE
Linux test failures with `nix-build`

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#1224]
# Bug Report

## Summary

A bunch of tests fail when running on Linux.

## Steps to reproduce

`nix-build -A nexus-mods-app` on https://github.com/NixOS/nixpkgs/pull/270372.

## What is the expected behaviour?

Tests should pass.

## Other information

[Build log](https://gist.github.com/l0b0/dd7836622054702caecff670a608f981)

**Comment by erri120** [comment]
Our CI runs all tests on Windows, Linux, and macOS, and they're all passing on main.

**Comment by erri120** [comment]
```
[xUnit.net 00:00:00.19]       System.PlatformNotSupportedException : Operation is not supported on this platform.
[xUnit.net 00:00:00.19]       Stack Trace:
[xUnit.net 00:00:00.19]            at GameFinder.Wine.AWinePrefix.GetUserName()
[xUnit.net 00:00:00.19]            at GameFinder.Wine.AWinePrefix.CreateOverlayFileSystem(IFileSystem fileSystem)
```

Missing `USER` environment variable:

https://github.com/erri120/GameFinder/blob/ae2ef6afbf6e8f807c05e744bb2e3626560561bc/src/GameFinder.Wine/AWinePrefix.cs#L53-L58

**Comment by erri120** [comment]
```
[xUnit.net 00:00:00.45]         [2024-04-17 06:50:54Z] fail: NexusMods.FileExtractor.FileExtractor[0]
[xUnit.net 00:00:00.45]               While extracting via NexusMods.FileExtractor.Extractors.SevenZipExtractor
[xUnit.net 00:00:00.45]         System.ComponentModel.Win32Exception (0x80004005): Failed to start a process with file path '/build/source/tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz'. Target file or working directory doesn't exist, or the provided credentials are invalid.
[xUnit.net 00:00:00.45]          ---> System.ComponentModel.Win32Exception (2): An error occurred trying to start process '/build/source/tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz' with working directory '/build/source/tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/bin/Release/net8.0'. No such file or directory
[xUnit.net 00:00:00.45]            at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
[xUnit.net 00:00:00.45]            at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
[xUnit.net 00:00:00.45]            at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 56
[xUnit.net 00:00:00.45]            at CliWrap.Utils.ProcessEx.Start() in /_/CliWrap/Utils/ProcessEx.cs:line 68
[xUnit.net 00:00:00.45]            at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken) in /_/CliWrap/Command.Execution.cs:line 307
[xUnit.net 00:00:00.45]            at CliWrap.Command.ExecuteAsync(CancellationToken cancellationToken) in /_/CliWrap/Command.Execution.cs:line 326
[xUnit.net 00:00:00.45]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync_Impl(IStreamFactory sFn, AbsolutePath destination, CancellationToken token, IActivitySource`1 activity) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 141
[xUnit.net 00:00:00.45]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync_Impl(IStreamFactory sFn, AbsolutePath destination, CancellationToken token, IActivitySource`1 activity) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 182
[xUnit.net 00:00:00.45]            at NexusMods.FileExtractor.Extractors.SevenZipExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath destination, CancellationToken token) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs:line 63
[xUnit.net 00:00:00.45]            at NexusMods.FileExtractor.FileExtractor.ExtractAllAsync(IStreamFactory sFn, AbsolutePath dest, CancellationToken token) in /build/source/src/ArchiveManagement/NexusMods.FileExtractor/FileExtractor.cs:line 68
```

Extractor at `/build/source/tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz` doesn't exist, so no archives could be extracted.

**Comment by erri120** [comment]
Since this is related to your nix setup, I'm going to close this issue. You can still comment here, or you can go to our [Discord](https://discord.com/invite/ReWTxb93jS).

**Comment by l0b0** [comment]
Thank you heaps for the help though, I'm really not familiar with this project.

**Comment by l0b0** [comment]
> Extractor at `/build/source/tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz` doesn't exist, so no archives could be extracted.

What would create the `7zz` executable at [that location](https://github.com/Nexus-Mods/NexusMods.App/blob/0f8d2e946a3a259d9148474488dd1b5522b6146a/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs#L190), though? It's not mentioned anywhere else in the code base, so something must be creating a symlink or copying it or something.

**Comment by erri120** [comment]
> > Extractor at `/build/source/tests/Games/NexusMods.Games.BethesdaGameStudios.Tests/bin/Release/net8.0/runtimes/linux-x64/native/7zz` doesn't exist, so no archives could be extracted.
> 
> What would create the `7zz` executable at [that location](https://github.com/Nexus-Mods/NexusMods.App/blob/0f8d2e946a3a259d9148474488dd1b5522b6146a/src/ArchiveManagement/NexusMods.FileExtractor/Extractors/SevenZipExtractor.cs#L190), though? It's not mentioned anywhere else in the code base, so something must be creating a symlink or copying it or something.

https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/ArchiveManagement/NexusMods.FileExtractor/NexusMods.FileExtractor.csproj

https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/ArchiveManagement/NexusMods.FileExtractor/build/NexusMods.FileExtractor.targets

**Comment by halgari** [comment]
In general, Nix is such a wildly different OS, that you're likely going to have more than a few issues porting the application to it. Some of the Nix issues we've encountered so far are: 

* OS not having a display
* OS not having a user
* OS not being OSX/Windows/Linux according to .NET

We likely won't be doing anything to support the OS due to the lack of installbase by gamers, but if you submit PRs that fix these various issues, and have a github runner for it, we likely won't refuse the PRs. Be aware though, the PRs may also be a hard sell if they require a lot of maintinance from us. For example in the case of USER not being set, we'd have to track down a Nix install to figure out why it wasn't set, where it *is* set, and how to get that value. After that's fixed it then becomes a bit of a load on the rest of the codebase, becasue every feature we add has to be verified against all the supported platforms.

**Comment by erri120** [comment]
> * OS not having a display
> * OS not having a user
> * OS not being OSX/Windows/Linux according to .NET

I think the first two issues came from building the App in a special nix environment. This is somewhat similar to trying to build the App in a basic docker container, where most normal desktop features aren't available. The fix is to just update the build script to include the correct dependencies.

Can you link where we saw the first issue? .NET should classify nix as Linux without issue.

**Comment by l0b0** [comment]
> In general, Nix is such a wildly different OS, that you're likely going to have more than a few issues porting the application to it. Some of the Nix issues we've encountered so far are:
> 
>     * OS not having a display

That's expected because of the sandboxing of the build.

>     * OS not having a user

Ditto, and was easily fixed by running `dotnet test` with `--environment=USER=nobody`.

>     * OS not being OSX/Windows/Linux according to .NET

That's bizarre. It's absolutely Linux (you can basically think of it as any other Linux with a different package manager), but it's possible that the sandboxing is thwarting some code from reaching out and getting what it needs. Like @erri120 I'd like to know where you've encountered this elsewhere, to see if it's something which can be fixed on my side.

**Comment by l0b0** [comment]
After replacing 7zz in the repo with a binary built for NixOS only three tests are failing. Thank you for the help!
