### ISSUE TITLE
UI/UX - Visually distinguish multiple installations of the same game in MyGames page (Steam, Epic, disk, etc)

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1225]
Currently there is no visual distinction or way to identify multiple installations of the same game in the MyGames page:
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/73c30d3e-63c0-4ed2-95cd-f20717e71b43)

It would be useful to show the installation path in some way to allow users to identify which one is which.

Currently users have to try blindly and hope of getting the one they want, and even then it isn't easy to figure out exactly which game installation is being managed.

## Design

[Figma link](https://www.figma.com/design/droQp7IUqRCq5AUGmXldvP/%F0%9F%93%B1-Add%2Fmanage-games?node-id=1072-2728&t=UdWa98ZupGi4UWZl-1)

![Image](https://github.com/user-attachments/assets/094c3dfb-425c-4501-9ceb-868ff06eb19b)

**Comment by LukeNexusMods** [comment]
We will need to distinguish between which game provider has been used to download it at some point too.
