### ISSUE TITLE
OAuth Login is Borked

### ISSUE THREAD

**Issue by StellarHarbour** [Nexus-Mods/NexusMods.App#1241]
# Bug Report

## Summary
App Log in button doesn't work

## Steps to reproduce
1.Click Log in button
2.Click Authorise on site and choose 
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/45370592/1ad4950b-279c-4ea1-9e1b-aae3ce20cd30)
3.Blank tab open in browser, app Log in button no more clickable

## What is the expected behaviour?
Log in

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_
[nexusmods.app.slim.00.log](https://github.com/Nexus-Mods/NexusMods.App/files/15029976/nexusmods.app.slim.00.log)
[nexusmods.app.main.00.log](https://github.com/Nexus-Mods/NexusMods.App/files/15029977/nexusmods.app.main.00.log)

**Comment by Sewer56** [comment]
According to person opening this PR (on Discord), it only happens on AppImage on their Fedora setup.

I'll look into this.

**Comment by StellarHarbour** [comment]
[nexusmods-app-nxm.tar.gz](https://github.com/Nexus-Mods/NexusMods.App/files/15030141/nexusmods-app-nxm.tar.gz)
Worked once for me with archived version, then stopped worked after log out...

**Comment by halgari** [comment]
Completely reworked the handling of this last week as part of #1345
