### ISSUE TITLE
App stopped working

### ISSUE THREAD

**Issue by StellarHarbour** [Nexus-Mods/NexusMods.App#1242]
# Bug Report

## Summary
Stopped working during mod downloads...
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/45370592/f864e964-a37d-44d6-af45-321698c005f5)

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_
[nexusmods.app.main.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15030523/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15030524/nexusmods.app.slim.current.log)
[nexusmods.app.main.53.log](https://github.com/Nexus-Mods/NexusMods.App/files/15030526/nexusmods.app.main.53.log)
[nexusmods.app.slim.53.log](https://github.com/Nexus-Mods/NexusMods.App/files/15030527/nexusmods.app.slim.53.log)

[nexusmods.app.main.49.log](https://github.com/Nexus-Mods/NexusMods.App/files/15030525/nexusmods.app.main.49.log)

**Comment by Pickysaurus** [comment]
Did you build the app from source, or are you using the version from the releases tab?

**Comment by erri120** [comment]
Is this still relevant?

**Comment by erri120** [comment]
If the issue is still relevant with the latest version, you can re-open it.
