### ISSUE TITLE
Disabling SMAPI deletes StardewValley.exe 

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1269]
# Bug Report

## Summary
When installing SMAPI for some reason it installs `StardewModdingAPI.exe` as `StardewValley.exe` which overwrites the executable provided by the game. If the user then disables SMAPI and applies changes the app will delete the SMAPI exe from the game folder but doesn't restore the original one. 

## Steps to reproduce
1. Manage Stardew Valley on Windows
2. View the EXE and see that it's the default StardewValley.exe file
3. Install SMAPI and apply the changes.
4. See that instead of installing `StardewModdingAPI.exe` as expected, `StardewValley.exe` has been replaced. 
5. Disable SMAPI and apply changes.
6. See that `StardewValley.exe` no longer exists. Where the original EXE should be restored. 

## What is the expected behaviour?
The original game EXE is restored. 

## Other information

Log files can be found in these locations:
[nexusmods.app.slim.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15106240/nexusmods.app.slim.current.log)
[nexusmods.app.main.00.log](https://github.com/Nexus-Mods/NexusMods.App/files/15106241/nexusmods.app.main.00.log)
[nexusmods.app.slim.00.log](https://github.com/Nexus-Mods/NexusMods.App/files/15106242/nexusmods.app.slim.00.log)
[nexusmods.app.main.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15106243/nexusmods.app.main.current.log)

**Comment by Sewer56** [comment]
This doesn't seem to happen to me on Linux at least, I'll check Windows later.

**Comment by Al12rs** [comment]
I can't reproduce on Windows either.

@Pickysaurus Can you reproduce on a clean start?

It might have been an ingest bug at some point. 
In no one can reproduce we can close this as a one time snafu and keep an eye out for ingest bugs once we decide how ingest should actually behave.

**Comment by Pickysaurus** [comment]
After restarting the app it's no longer happening so I'll close this for now.
