### ISSUE TITLE
UI scaling (HiDPI) support

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#1277]
# Improvement

## Currently 

Currently, starting the GUI on a 4k screen means having to sit very close to the screen to be able to read the UI text.

## We want

Some form of HiDPI support, so that I can use the app the same as everything else on my desktop.

## Design

Some ideas, in increasing UX order:

1. Detect some _environment variable_ which determines scaling. This would be a good first step, but on its own would be a big stumbling block for less technical users.
2. A _configuration option_ to change the scaling would be more user-friendly. The big disadvantage is having to find it _while using the non-scaled UI._
3. _Detect UI scaling in the desktop environment,_ and apply that. For example, my GNOME desktop is scaled 2x, and this scaling applies to the vast majority of desktop applications out of the box.

**Comment by Sewer56** [comment]
Relevant links

https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI

https://github.com/AvaloniaUI/Avalonia/issues/9390

This is an underlying framework issue (Avalonia) with some setups involving X11 backend. Be it xwayland or other.
There isn't a lot we can do on our end right now.

**Comment by erri120** [comment]
Not really anything we can do here.
