### ISSUE TITLE
Mod enable toggle state gets updated while scrolling

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1287]
# Bug Report

## Summary
When the user has enough mods to scroll the loadout view, the "enable" toggle animation replays each time the row appears.

## Steps to reproduce
1. Install enough mods to have a scroll bar
2. Scroll up and down rapidly
3. See the toggle "twitching". 

## What is the expected behaviour?
The animation should only play when the rows are enabled or disabled. 

## Other information
https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/a1f1f445-07b7-44f1-8dcd-cac96fa47621

**Comment by erri120** [comment]
There is no "animation" to speak of. When the control gets loaded, the default position for the toggle is set to false. After the control gets "activated" we actually pull in the data and switch the toggle.

**Comment by Sewer56** [comment]
And the control going back from 'false' to true when scrolling back up is most likely due to virtualization.

We (or rather Avalonia) reuse the rows under the hood, rather than storing all the rows around forever.

**Comment by erri120** [comment]
This isn't a bug, nothing technical is wrong with our code. This is unwanted UI behavior.

**Comment by Al12rs** [comment]
This is still not something we want though, it is still a bug, even if we know why it happens.

**Comment by Sewer56** [comment]
It's an improvement, I'd say.

**Comment by Pickysaurus** [comment]
I don't think we need to get bogged down in the semantics of this. From a user perspective, this is a UI bug. The toggles appear to move without me interacting with them.
