### ISSUE TITLE
Stuck on running game

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#1303]
# Bug Report

## Summary

`NexusMods.App` gets stuck waiting for Steam to run the game, with the "RUNNING" indication going indefinitely.

## Steps to reproduce

1. Start Steam
1. Install Skyrim Special Edition
2. [Build](https://github.com/NixOS/nixpkgs/pull/270372) and run `NexusMods.App`
1. Install [USSEP](https://www.nexusmods.com/skyrimspecialedition/mods/266)
3. Click "Launch"

## What is the expected behaviour?

It should launch the game *or* show the relevant error message.

## Other information

[nexusmods.app.slim.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15217442/nexusmods.app.slim.current.log)
[nexusmods.app.main.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15217443/nexusmods.app.main.current.log)

If I run the same command as NMA says it's running, `xdg-open steam://rungameid/489830`, that does start Skyrim.

**Comment by l0b0** [comment]
> @erri120 Related to previous logs on Linux?

Huh?

**Comment by Sewer56** [comment]
It's similar to an issue previously reported, so I pinged the person last working on it.

**Comment by erri120** [comment]
Closing in favor of #1151.
