### ISSUE TITLE
Avoid bundling dynamically linked 7zz binary

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#1306]
# Improvement

## Currently 

The 7zz binary bundled with the Linux version of this package will not work on platforms like NixOS without additional tweaks. It would be good to have the option to not copy this executable to the output directory during the build.

## We want

A flag to exclude 7zz from the output when building.

## Supporting Information

See https://github.com/NixOS/nixpkgs/pull/270372/files for a workaround, using the 7zz package from nixpkgs instead.

@erri120

**Comment by erri120** [comment]
PR #1308 adds `NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR` that you can specify during build time:

```bash
NEXUSMODS_APP_USE_SYSTEM_EXTRACTOR=1 dotnet build
```

This will result in the runtimes not being copied to the output directory, and the code will start the system `7zz`. As usual, this requires that `7zz` is found in `PATH`.
