### ISSUE TITLE
Closing and restarting the App while a Download is in progress doesn't automatically resume the download

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1311]
Download appears stuck, no progress is shown.
User has to pause and resume the download manually to make it actually resume downloading.
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/d152a748-7100-4f13-856c-4f1a14825e95)

**Comment by Pickysaurus** [comment]
Should it auto-resume? If the user has left it several hours the download link would've expired (from Nexus Mods).
