### ISSUE TITLE
Windows - App fails to startup on first attempt from a "cold start"

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1312]
# Bug Report

## Summary
When I first turn on my PC, the Nexus Mods app will fail to start up properly the very first time I try to launch it. I can exhibit any of the following symptoms:
- The command window appears but closes again without opening the UI
- The command window appears, and the UI window appears as a transparent frame but is unresponsive.
- The command window appears, and the UI loads but is unresponsive. 

Restarting the app fixes this. 

I am currently using a version of the app built from source, but this issue has persisted across multiple updates so I am now reporting it. 

## Steps to reproduce
On Windows:
- Start the PC up.
- Attempt to open the app. 
- See the failure
- Try to open it again
- Success

## What is the expected behaviour?
The app should open properly from a "cold start". 

## Other information
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/abc28ebb-4945-440d-a5b0-a63d66e4c1da)
The main window is frozen as shown here. 

[nexusmods.app.main.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15233765/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/Nexus-Mods/NexusMods.App/files/15233766/nexusmods.app.slim.current.log)

**Comment by LukeNexusMods** [comment]
I just had this problem too.

**Comment by erri120** [comment]
Is this still relevant?
