### ISSUE TITLE
Improve casing on language selector

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1313]
# Improvement

## Currently 
Listed languages are shown with inconsistent case.

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/867e7609-3fa4-4d20-90c0-bc6df299f76c)

## We want
Ensure we are using proper capitalisation for language names (e.g. Polski, Italiano)

## Supporting Information
_(Include any supporting screenshots etc to support the above)_

## Design
_(Any designs to required for this feature)_

**Comment by erri120** [comment]
We're using [`CultureInfo.NativeName`](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.nativename):

> The culture name, consisting of the full name of the language, the full name of the country/region, and the optional script. The format is discussed in the description of the CultureInfo class.

Possible alternative is [`DisplayName`](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.displayname):

> The full localized culture name in the format languagefull [country/regionfull], where languagefull is the full name of the language and country/regionfull is the full name of the country/region.

```

CULTURE ISO ISO WIN DISPLAYNAME                              ENGLISHNAME
ar      ar  ara ARA Arabic                                   Arabic
bg      bg  bul BGR Bulgarian                                Bulgarian
ca      ca  cat CAT Catalan                                  Catalan
zh-Hans zh  zho CHS Chinese (Simplified)                     Chinese (Simplified)
cs      cs  ces CSY Czech                                    Czech
da      da  dan DAN Danish                                   Danish
de      de  deu DEU German                                   German
el      el  ell ELL Greek                                    Greek
en      en  eng ENU English                                  English
es      es  spa ESP Spanish                                  Spanish
fi      fi  fin FIN Finnish                                  Finnish
zh      zh  zho CHS Chinese                                  Chinese
zh-Hant zh  zho CHT Chinese (Traditional)                    Chinese (Traditional)
zh-CHS  zh  zho CHS Chinese (Simplified) Legacy              Chinese (Simplified) Legacy
zh-CHT  zh  zho CHT Chinese (Traditional) Legacy             Chinese (Traditional) Legacy
```

**Comment by erri120** [comment]
The `NativeName` is technically correct, since a language selector should show the native language name and casing for those languages are correct. I think @Al12rs can verify that the correct casing for Italian in Italian is `italiano`.

**Comment by Pickysaurus** [comment]
> The `NativeName` is technically correct, since a language selector should show the native language name and casing for those languages are correct. I think @Al12rs can verify that the correct casing for Italian in Italian is `italiano`.

Fair, but when showing these options in English it looks inconsistent. Maybe we could do it as "Display Name (Native Name)"? 

I appreciate this is only a problem for Latin languages, but if/when we have a Japanese locale it might be nice to show it as "Japanese (日本語)"?

**Comment by Al12rs** [comment]
> The `NativeName` is technically correct, since a language selector should show the native language name and casing for those languages are correct. I think @Al12rs can verify that the correct casing for Italian in Italian is `italiano` (comes from `Lingua italiana` iirc).

Yeah, in Italian languages are not capitalized

**Comment by Pickysaurus** [comment]
It should probably be up to @captainsandypants if we do anything here. My preference would be both `DisplayName` and `NativeName`:

**Comment by erri120** [comment]
`DisplayName` doesn't really make much sense since you're trying to change to the language you know. So if the App is accidentally in Japanese, then seeing ドイツ語 doesn't really help with selecting German. That's why everything uses the native language name and/or the country flag for languages, since that's easiest to understand. We don't have country flags, and they also aren't great for language selection, so native name is definitely the best option.

**Comment by Pickysaurus** [comment]
Here's an example of how Discord presents the languages. 
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/db2d1109-54a3-4902-9470-cb67d6fce0ae)

**Comment by Patriot99** [comment]
In the Polish language, nouns and proper nouns are capitalized in user interfaces, as is standard practice in the language. This includes menu items, buttons, titles, headings, and other text on the interface. Adjectives and verbs, on the other hand, are not capitalized unless they are at the beginning of a sentence or are being used as proper nouns.

**Comment by erri120** [comment]
@captainsandypants still needs to comment on what we want here.

**Comment by captainsandypants** [comment]
Capitalised
