### ISSUE TITLE
Regression: Remove loadouts and unmanage game functionality has been removed

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1322]
PR #1302 reverted changes from these two PRs:
- #1279
- #1294

It is now no longer possible to unmanage a game or to remove a loadout and to revert to vanilla state in doing so.

These need to be added/implemented back in

**Comment by Sewer56** [comment]
Yes sir, am actually already working on this as we speak

**Comment by halgari** [comment]
Fixed as part of #1349
