### ISSUE TITLE
Loadout Items, Library Items, and Downloads

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1336]
Ever since the beginning of the project, a Loadout contained "Mods":

https://github.com/Nexus-Mods/NexusMods.App/blob/6354819d181ea8f3d6eb75f1d35529fbebec31e4/src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs#L20-L23

Which the new DB and PR #1302, this changed to "Mods" specifying the Loadout they are in:

https://github.com/Nexus-Mods/NexusMods.App/blob/afcab9601d6fda78ea6f0ec2f33f6eec6f1305fe/src/Abstractions/NexusMods.Abstractions.Loadouts/Mods/Mod.cs#L132-L136

https://github.com/Nexus-Mods/NexusMods.App/blob/afcab9601d6fda78ea6f0ec2f33f6eec6f1305fe/src/Abstractions/NexusMods.Abstractions.Loadouts/Loadout.cs#L123-L126

We now have a reversed relationship between Loadouts and "Mods". Instead of getting a Loadout and then having access to its "Mods", we can now just get every Entity that is a Mod and has a `LoadoutId` property that matches the value of the Loadout we're trying to look up.

This issue is about removing the `Mod` model, and replacing it with a generic `LoadoutItem` model.

We've been trying to shoehorn everything into our `Mod` model. This is best illustrated by looking at our `ModCategory` enum that describes what the `Mod` is:

https://github.com/Nexus-Mods/NexusMods.App/blob/afcab9601d6fda78ea6f0ec2f33f6eec6f1305fe/src/Abstractions/NexusMods.Abstractions.Loadouts/Mods/ModCategory.cs#L3-L13

Translating this into English, we're saying that a `Mod` can be "Game Files", it can be "Saves", it can be a "Mod"...

The abstraction that we have, of Loadouts containing Mods, is woefully inadequate. The effects of this can already be seeing by reading #1195 and #1146. We don't even have two Mods installed and already our system is not doing the things we want it to do.

Other mod managers also have an issue with shoehorning everything into a "Mod". In Vortex (@insomnious), a Nexus Mods Collection is represented as a Mod, in Mod Organizer 2 (@Al12rs) a "Mod" is literally just a subdirectory in the `mods` directory.

Continuing to use "Mods" to represent the content of a Loadout will just lead to more and more issues, that'll require weird hacks, and that'll incur a lot of tech debt.

However, which the new DB, we can go down a different path. Loadouts won't be containing "Mods" anymore. Instead, we'll have Loadout Items that reference a Loadout. A Loadout Item can be anything: Game Files, Configs, SMAPI Mods, Collections. Since Entities in the new DB are just collections of attributes that we gave a type to make it work in C#, each individual system can just query for the specific attributes it needs.

The apply process wouldn't go through all "Mods" to get the file trees, it would just query all Entities that reference the current Loadout that has a "File Bucket" attribute or similar.

While this is primarily a backend change, doing this allows the UI to be much richer. We could show all Loadout Items like this:

![2024-05-13_11-13-31](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/c3c263ec-4cfe-48da-b791-8c271a683e58)

Here we have "Game Files" because a Loadout contains those, we have SMAPI, and then we have an "Item Group" called "Raised Garden Beds". This item group contains three SMAPI Mods as well as a "Config" item that we created when the user launched the game, and it created a config file for the SMAPI Mod. Our new model would allow all of these to be different types of Items that have relationships between one another.

Whether we show such a view is up to the designers, but what this new model allows us to do is make the "Loadout Mods" view easier as well:

![2024-05-13_11-16-57](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/d3602fb5-40a8-4cfb-ab32-c48cc1774272)

Instead of using stuff like the `ModCategory` enum to filter out "Mods" we don't want to show in this view, we'll use the Loaodut Items and special attributes to figure out what we want to show.

Collections would also be easier to implement with this, since it'll just be another Item that gets referenced by all the Items it contains.

Overall, going from "Mods" to Loadout Items will make our data model much easier and simpler, as well as allow us to build better UIs. We won't be able to escape the term "Mod" when making a "Mod Manager" but we won't be forced to use it in our backend.

As a small postfix to this post, a "Mod" is just a list of instructions on how to modify something that we humans gave a name to. Outside of modding games, mods exists for cars and other real things as well.

**Comment by Al12rs** [comment]
Something to note is that the App actually mostly only cares about the so called `FileBuckets`, which is what it will actually need to install the files. 
The `FileBuckets` are the performance critical parts of the code that we really need to be able to reason around efficiently architecture wise. 

How these `FileBuckets` are shown in the UI and are mapped to what users traditionally think of mods is mostly a user experience issue of making things clear and easy. 

The proposal above aims to move our architecture from a simple `FileBucket` system (which we currently improperly call mods), to something that is closer to how we might want the UI to show things.

I think that the `FileBucket` architecture being efficient is more important than proper mapping of UI concepts into our architecture, but this isn't either or, we can have both. Just I wouldn't want to compromise efficiency.

Apart from UI and Game specific features, Mod Updates are the main feature of the App that would likely be influenced for the better by a more accurate mapping of loadout entities into architecture.

**Comment by erri120** [comment]
@halgari we should use this issue to plan out the core types we'll be using, as well as how the new source generator would be used here.

I'm thinking that a Loadout Item should only consist of a name, a reference to a Loadout, and an optional reference to a "parent"/group which itself is just another Loadout Item:

```csharp
interface ILoadoutItem
{
  EntityId ItemId;
  LoadoutId LoadoutId;
  Optional<EntityId> ParentItemId;
}
```

We should also have a marker attribute like `HasFiles` and `Files` would contain a reference to a Loadout Item with this marker attribute. In code, we'd want a separate interface:

```csharp
// better name welcomed
interface ILoadoutItemWithFiles : ILoadoutItem
{
  // optionally can have methods like GetFiles() or ToFileTree(), but this shouldn't really have any properties.
}
```

Additional metadata like the version should be in separate interfaces as well. I'd almost say we want separate entities for metadata entirely, similar to how we'd do "layers".

Just some ideas, and as you hopefully notice, not a single mention of "mod".

**Comment by erri120** [comment]
Notes after chatting with @captainsandypants and @Al12rs. Will write a separate comment about the "My Mods" page.

## Downloads

First off, the data for our downloads should be better organized and simplified. The new designs for the UI heavily make use of the Nexus Mods mod pages.

Files that we "download", be that archives, executables, or other, would get metadata attached to them, matching the data available at the "origin". All of this data is also not local to a Loadout, but global:

```mermaid
erDiagram
    DownloadedFile {
        string FileName
        ulong Size
        Hash Hash
        DateTime DateDownloaded
    }
    NexusModsFile {
        string Name
        string Version
        int FileId
        NexusModsPage Page
    }
    NexusModsPage {
        string Name
        Image Screenshot
        int ModId
    }
    LocalFile {
        string Path
    }

    DownloadedFile ||--|| LocalFile : includes
    DownloadedFile ||--|| NexusModsFile : includes
    NexusModsFile }|--|| NexusModsPage : references

    Archive {
        DownloadedFile Origin
    }
    ArchiveFile {
        stirng FileName
        ulong Size
        Hash Hash
        Archive Parent
    }
    NestedArchive

    DownloadedFile ||--|| Archive : references
    Archive ||--|{ ArchiveFile : references
    Archive ||--|| NestedArchive : includes
    ArchiveFile ||--|| NestedArchive : includes
```

If a user adds a file from disk, we'd create a new `LocalFile` entity. If the user downloads via Nexus Mods, we create a `NexusModsFile` entity, and check link it to an existing `NexusModsPage` or create a new one.

If the downloaded file is an archive, we run it through the extractor and create new `Archive` and `ArchiveFile` entities. I put `NestedArchive` in there and made it include both `Archive` and `ArchiveFile` but I'm not 100% sure about that.

This model can also be expanded with a `NexusModsCollection` model that includes `DownloadedFile` as well, since a collection is also downloaded as an archive:

```mermaid
erDiagram
    NexusModsCollection {
        NexusModsFile[] Files
    }

    NexusModsCollection ||--|| DownloadedFile : includes
    NexusModsCollection ||--|{ NexusModsFile : references
```

The new "Mods Library" page designed by @captainsandypants will display `DownloadedFile` entities. How it's displayed is beside the point, we just need to make sure the data is easily obtainable.

**Comment by Al12rs** [comment]
I'm still not happy with some of the names, `DownloadedFile` that can represents a `LocalFile`.

I'm thinking about some potential alternatives like `UserArchive` or based on function `InstallableFile`

**Comment by erri120** [comment]
@Al12rs what about `LibraryFile`?

**Comment by Al12rs** [comment]
> @Al12rs what about `LibraryFile`?

I like that more than everything else so far, I think that could work. 
I would actually propose `LibraryItem` for symmetry with `LoadoutItem`, what do you think?

We can rename the `FileOriginsPage` to `LibraryPage` since we have a clearer idea what the Library term actually means now.

**Comment by erri120** [comment]
> > @Al12rs what about `LibraryFile`?
> 
> I like that more than everything else so far, I think that could work. 
> I would actually propose `LibraryItem` for symmetry with `LoadoutItem`, what do you think?
> I guess I'm proposing making a hierarchy here, similar to what we are going to do with Loaodut items
> 
> 
> We can rename the `FileOriginsPage` to `LibraryPage` since we have a clearer idea what the Library term actually means now.
> 

`LibraryItem` also came to me a minute after writing `LibraryFile`. This might also cover things that aren't necessarily a single file.

**Comment by erri120** [comment]
So updated relationships would look like this:

```mermaid
erDiagram
    LibraryItem {
        string Name
    }

    LibraryFile {
        ulong Size
        Hash Hash
    }

    NexusModsFile {
        string Name
        string Version
        int FileId
        NexusModsPage Page
    }
    NexusModsPage {
        string Name
        Image Screenshot
        int ModId
    }

    LocalFile {
        string Path
    }

    LibraryFile ||--|| LibraryItem : includes
    NexusModsFile ||--|| LibraryFile : includes
    LocalFile ||--|| LibraryFile : inclues
    NexusModsFile }|--|| NexusModsPage : references

    Archive {
        LibraryFile Origin
    }
    ArchiveFile {
        stirng FileName
        ulong Size
        Hash Hash
        Archive Parent
    }
    NestedArchive

    Archive ||--|| LibraryFile : references
    ArchiveFile }|--|| Archive : references
    NestedArchive ||--|| Archive : includes
    NestedArchive ||--|| ArchiveFile : includes
```

**Comment by Al12rs** [comment]
Cool! Yeah I think this is pretty understandable.
I guess the `NestedArchive` would have a parent property? Or was it a deliberate decision not to have parent property on it?

**Comment by erri120** [comment]
> Cool! Yeah I think this is pretty understandable. I guess the `NestedArchive` would have a parent property? Or was it a deliberate decision not to have parent property on it?

I'm not sure what `NestedArchive` is supposed to be yet. It "includes" `ArchiveFile` which has a `Parent` that is an `Archive` but it's also an `Archive` itself. The idea for this, is to allow consumers to not care whether we have a nested archive or not, they just get an `Archive` and stuff works.

@halgari can we do double includes like this, or use a different approach?

**Comment by Al12rs** [comment]
Ah, I had missed the relationship with `ArchiveFile`, I see what you mean. 

I don't think `NestedArchive` entity needs to include `ArchiveFile` and be the same entity, it could just hold a reference to it or something like that.

**Comment by halgari** [comment]
We can have a double includes in the data model, but it's not exposed in a clear way via the source generators. What it would involve is writing our own "TryGetAsXX" and then doing a "reinterpret cast" into the other type. This is pretty much the way the code works internally, and it's about 10 lines of code.

**Comment by erri120** [comment]
```mermaid
erDiagram
    LibraryFile
    NexusModsLibraryFile {
        NexusModsFileMetadata FileMetadata
    }
    NexusModsLibraryFile ||--|| LibraryFile : includes
    NexusModsFileMetadata {
        string Name
        string Version
        int FileId
        NexusModsModPage Page
    }
    NexusModsModPageMetadata {
        string Name
        int ModId
    }
    NexusModsLibraryFile ||--|| NexusModsFileMetadata : references
    NexusModsFileMetadata }|--|| NexusModsModPageMetadata : references

    PersistedState {
        PersistedStatus Status
        OptionalSize TotalSize
    }
    NXMDownloadState {
        NexusModsFileMetadata FileMetadata
    }
    NXMDownloadState ||--|| PersistedState : includes
    NXMDownloadState ||--|| NexusModsFileMetadata : references
```

**Comment by erri120** [comment]
Superseded by #1763.
