### ISSUE TITLE
New component - NMA topbar

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#135]
### Name
NMA Topbar

### Purpose
To provide an area for important global actions such as login, search, settings.

### Notes
Replaces the temporary topbar with a new componentised version that is part of the design system. 
All icons, buttons and fields within the topbar currently have no functionality and are only placeholders for future functionality.

## Design

[Figma design system link](https://www.figma.com/file/8pjtQeNggvVi7RWoLNGV80/%F0%9F%A7%B0-Nexus-Mods-Design-System?node-id=6359%3A22735&t=yQa4yDbAIR2ar4br-1)

![image](https://user-images.githubusercontent.com/118466382/220715199-43dc3918-b66f-4218-b5e0-ab68120bacef.png)

**Comment by halgari** [comment]
Implemented as part of #154
