### ISSUE TITLE
Spine items "flash" during installation of multiple mods.

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1366]
# Bug Report

## Summary
The spine load-outs (and parts of the table) appear to flash when batch-installing mods. 

## Steps to reproduce
1. Install lots of mods via the "Add mod" button
2. Watch the spine and table items "flash" while processing. 

## What is the expected behaviour?
The loadout items remain static. 

## Other information
 

https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/64de80f4-971e-483d-82a8-c4e0bb674f31

**Comment by Sewer56** [comment]
My Explanation (copied from Discord).

What happens is in `Repository<TModel>`. `_cache.AddOrUpdate` is being called. The EId of the object added matches but the object itself does not. DynamicData is treating this as an object `Replace` and is emitting the modification of the object as `Object was Removed` and then `Object was Added`.

When we add a mod, a new revision of a loadout is created (i.e. Loadout is Modified), therefore the `Loadout` itself is treated as `Removed` then `Added`.

For more info, see: https://discord.com/channels/1134149061080002713/1134151856537469060/1240384685486510100

**Comment by Sewer56** [comment]
I will fix this after #1349 is merged. As this affects my code in there too.
No proper solution yet.

**Comment by halgari** [comment]
Fixed as part of #1349
