### ISSUE TITLE
Command Window still showing

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1368]
The command window is still appearing when running the app in Windows. 

Is it possible to prevent this from appearing?

**Comment by Sewer56** [comment]
1 line fix.
Set `<OutputType>WinExe</OutputType>` in `NexusMods.App.csproj`.

That's all.

**Comment by Al12rs** [comment]
Lol this actually fixed the problems of #1365

**Comment by halgari** [comment]
@Al12rs @Sewer56 in my experience turning the console logging back on, with a WinEXE means we don't get any console at all

**Comment by Sewer56** [comment]
Have you ran `AllocConsole` to spawn a console? Or is the issue you spawned the console and it doesn't write text to it?
