### ISSUE TITLE
[SDV] Fashion Sense UI - fails to install

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#1385]
# Bug Report

## Summary
I'm sure this is a commentary about me being a nerd, but I can't install `https://www.nexusmods.com/stardewvalley/mods/22946?tab=files` For some reason it pops up the "Advanced Install" window for this mod

## Steps to reproduce
1. Install this via the app: https://www.nexusmods.com/stardewvalley/mods/22946?tab=files
2. Be insulted because you don't have any fashion sense

**Comment by erri120** [comment]
Opening the advanced installer for this mod is the correct approach. The mod isn't a SMAPI mod, it directly replaces the files of another mod.
