### ISSUE TITLE
Flaky tests: `System.IO.DirectoryNotFoundException : Could not find a part of the path`

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1391]
https://github.com/Nexus-Mods/NexusMods.App/actions/runs/9173525498?pr=1390

**Comment by erri120** [comment]
Fixed in #1417.

**Comment by erri120** [comment]
Not fixed.

**Comment by halgari** [comment]
Fixed as part of several other ongoing improvements to the test system
