### ISSUE TITLE
Sidebar/Spine and buttons design update

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1395]
- Reduced border radius on games #1539
- Add side bar button for add game/loadout button (currently switches to the "Home" workspace and goes to "My Games") - add button should disappear when on this page.
- Home button in sidebar should be changed to the "Nexus Mods" logo variant.

## Designs

[Figma designs](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=971%3A5523&t=2pRtcDzXUi3D1Qf4-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/3ccb9836-7b45-437c-bec2-427738c26fab)

**Comment by erri120** [comment]
Can this be closed with #1539? @captainsandypants @Al12rs

**Comment by Al12rs** [comment]
I think we are probably missing the Add button on the spine that is mentioned, but we can add that as part of the multiple loadouts implementation.

**Comment by captainsandypants** [comment]
I'm going to close and we can do the add button as a separate issue.
