### ISSUE TITLE
Add SMAPI to mod install CI

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1414]
Install latest SMAPI versions in the mod installation pipeline.

**Comment by LukeNexusMods** [comment]
What happens if our SMAPI installer breaks?  smapi updates, and then install latest version to fix any problems. 

If smapi changes something there is a risk of it breaking.

**Comment by LukeNexusMods** [comment]
Communication with the mod author can be used to head off any problems that this piece of work would fix.
