### ISSUE TITLE
Regression: Creating Multiple Loadouts presents multiple 'Games Added'

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#1415]
# Bug Report

## Summary

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/afce34c2-57e8-4b02-9ea3-208899e8a678)

## Steps to reproduce

- Make two loadouts for a game.
- Go to 'My Games'
- 2 pills show.

## What is the expected behaviour?

- 1 pill shows.

## Other Information

Introduced in 0c8f1f9c2400a76af9b31ea9c706e76701c082f4

@Al12rs and I already talked about this during review. We just need to add a Distinct in `MyGamesViewModel.WhenActivated`.

**Comment by LukeNexusMods** [comment]
@Sewer56 Has this been fixed?

**Comment by Al12rs** [comment]
No
