### ISSUE TITLE
Add new item/s counter badge to "Library" left menu option

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1424]
Add a counter badge to the Library item in the left hand menu when a mod is added to the Library list. This will indicate to users where their downloaded mods can be found. The badge should disappear once the Library page is opened.

## Design

[Figma link](https://www.figma.com/design/5LmVL8YpgDHFSFA76fgCZA/%F0%9F%93%B1Mod-library?node-id=148%3A2124&t=GTNnAbzBa0CCknmH-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/2c6b7014-83a7-4f6c-b9e7-e9dd25b0bb78)

**Comment by erri120** [comment]
Should this counter be persisted (hard) or ephemeral, meaning it'll disappear after a restart of the App (easy)?

**Comment by captainsandypants** [comment]
Ephemeral is fine
