### ISSUE TITLE
Stardew Valley - Xbox Game Pass support is using the wrong path

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1474]
# Bug Report

## Summary
Using the app to manage SDV on GamePass selects the wrong folder. 

## Steps to reproduce
1. Install SDV on Game Pass
2. Manage with the app
3. Use "View Mod Files" or "Preview Changes" to see the path being managed. 
4. `..\Stardew Valley\Content\Content` is being used (duplicate Content folder!)

## What is the expected behaviour?
`..\Stardew Valley\Content\` is the correct path

## Other information
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/54828c59-9b62-4047-986c-947a015fa36e)

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by erri120** [comment]
That appears to be what's causing the issue. I don't know why that's there but removing it will probably fix the issue.

**Comment by Pickysaurus** [comment]
Removing that seems to have fixed it, but the app can't manage the game (probably due to DRM on the EXE file)
