### ISSUE TITLE
Left menu item button design improvement

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1485]
The left hand menu buttons now have designs in Figma with rest, hover and active states:

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/ab0f3217-b2ad-41ee-a6e0-de1afaf43328)

[Figma designs](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=971-5497&t=Tdl2zDMnlDxe3Ans-1)

**Comment by Al12rs** [comment]
After 0.5
