### ISSUE TITLE
Spine/Sidebar game button border radius change

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1486]
Change border radius for these currently circular buttons to 8px (rounded-lg).

[Figma designs](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=971-5524&t=1itiANcAOoy8J8bd-1)

Note: This is only the game and loadout buttons, NOT the home or download buttons.

**Comment by Al12rs** [comment]
Will not go in 0.5, they currently use the same styles
