### ISSUE TITLE
User Metrics: Questions

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1487]
Is it possible for telemetry to answer the following questions:

How many games is a user managing through NMA?
How many mods does a user have installed? will need this per game. 
How many mods has the user downloaded?
How long does it take for a game to be managed? per game
What system specs are being used?
How many loadouts are being created per game?
How many people have undo turned on to turned off?
Can we track bugs or problems with the app?

Is there anything we can add that would tell us if there is a problem with the app?

- #1184

**Comment by erri120** [comment]
>  How many mods does a user have installed? will need this per game.

We don't do mods per game since we have loadouts. I don't think aggregating the mod counts of all Loadouts for a game is gonna provide meaningful insights. Mods per Loadout would be better.

>  How many mods has the user downloaded?

Is this a global count? I'm not sure why we want the amount of downloads if we have the amount of installed mods per loadout already.

>  How long does it take for a game to be managed? per game

>  What system specs are being used?

Not possible with metrics since we aggregate all data.

>  How many people have undo turned on to turned off?

I don't really understand this.

>  Can we track bugs or problems with the app?

> Is there anything we can add that would tell us if there is a problem with the app?

Define bugs and problems.

**Comment by LukeNexusMods** [comment]
Per loadout is fine for the mod numbers, but the loadout is linked to a game right? So knowing the game too would be good. 

The number of downloaded mods will be different to the number of installed mods. Because there is that thing in the app where you have to click the button to add it to a loadout. 

When we eventually work on the Undo feature and we create the ability to turn it off if people dont want it, we will want to track that. 

When we get the point of having the ability for the app to upload logs or report issues, we will want to keep track of the numbers. So that if for any reason loads of bug reports start coming in we will see it and act on it.

**Comment by erri120** [comment]
> Per loadout is fine for the mod numbers, but the loadout is linked to a game right? So knowing the game too would be good.

For the following scenario:

- Loadout A (Stardew Valley): 100 Mods
- Loadout B (Stardew Valley): 50 Mods
- Loadout C (Cyberpunk 2077): 75 Mods

We can generate these metrics:

```
avg_mod_count{game="Stardew Valley"}=75.0
avg_mod_count{game="Cyberpunk 2077"}=75.0
```

The client would get all Loadouts and calculate the average mod count per game.

> When we eventually work on the Undo feature and we create the ability to turn it off if people dont want it, we will want to track that.

We don't have that yet, so no point in adding a metric for it.

> When we get the point of having the ability for the app to upload logs or report issues, we will want to keep track of the numbers. So that if for any reason loads of bug reports start coming in we will see it and act on it.

Same here, not implemented yet, so no metrics for this yet.

**Comment by erri120** [comment]
Some additional metrics that would be useful:

- Users per Version
- Size of all downloads per User
- Size of a Loadout
