### ISSUE TITLE
Top of Left menu should align to the top of the workspace

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1488]
The top edge of the top button should be in line with the top of the panel (this is easier to see when the top button is in an active or hover state)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/9d131c65-58d2-4657-a985-4d18ff2599dc)

**Comment by Al12rs** [comment]
Done with 
- #1517
