### ISSUE TITLE
Increase padding on Diagnostic list items to match designs

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1489]
Increase top and bottom padding of items to 12px (spacing/3).
Bonus, not necessary: If the drop/box shadow small style already exists in our back end then also apply that to the diagnostic items.

Increase top padding on empty state, should be 24px.

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/76963393-bd3f-4f43-af92-ecd3d9623bc2)

## Design
[Figma link](https://www.figma.com/design/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BADiagnostics?node-id=1-2954&t=1Vsn9iFV7O5lbZ8R-1)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/a25c4c4c-a2a3-4d1b-9de5-ab873db8742e)

**Comment by erri120** [comment]
Can you link to the figma design and attach a screenshot showing the issue?

**Comment by Al12rs** [comment]
Done with 
- #1517
