### ISSUE TITLE
Use markdown for telemetry opt-in overlay

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1506]
# Bug Report

## Summary
The link to the "More info about data we track" in this modal does not correctly open the help page. 

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/263d62ab-302e-42ca-a5fb-ca42afa02602)

## Steps to reproduce
Open the app for the first time.

## What is the expected behaviour?
The link opens this page https://help.nexusmods.com/article/121-diagnostics-usage-data-vortex

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by erri120** [comment]
The text should be using the markdown renderer, right now we hardcode text controls and a button control. Related to #1457.

**Comment by Pickysaurus** [comment]
I've actually noticed that the link I gave is Vortex-specific, so we may need to make a new page for the app. Let me know when this gets picked up and I'll sort it

**Comment by erri120** [comment]
> I've actually noticed that the link I gave is Vortex-specific, so we may need to make a new page for the app. Let me know when this gets picked up and I'll sort it

Opened a PR: https://github.com/Nexus-Mods/NexusMods.App/pull/1523
