### ISSUE TITLE
Standardize how we mark Entities as deleted in database

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1508]
# Improvement

## Currently 
In MnemonicDB you can't really remove data, so deletes are expressed by either retracting datom values or by adding some kind of marker.
We have different entities like Loadouts, Mods, File entries, Download Data, etc and we are using different approaches for each entity type.

## We want
A standardized way to mark entities as deleted. 
Ideally this would be handled on the DB API side. We wouldn't be getting deleted entities from queries. 
We would likely still need a way to access those, but not from the main APIs.

**Comment by halgari** [comment]
Done as part of #1626
