### ISSUE TITLE
Run Windows builds of games from Steam through Steam

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#152]
If the current game is not native for Linux and was installed via Steam, we have to run the game through the Steam created Proton instance.

**Comment by Sewer56** [comment]
As a sub-task of this task; or a part of it.

While most WINEPREFIX(es) ship with VC++ runtime in there already we'll also need to investigate installing the .NET Runtime into Wine to run some tools.  

There isn't really a good official way of automatically installing or even determining if .NET is installed from code; outside of wrapping around the `dotnet-install` scripts intended for CI.

That said, I did write a library for this sort of thing when I was working on Reloaded-II called [NetCoreInstallChecker](https://github.com/Sewer56/NetCoreInstallChecker) that can determine .NET installations and install them, pretty sure with some minor tweaking to the code you could make it run on a WINEPREFIX.
