### ISSUE TITLE
Advanced installer button just calls the normal installer rather than the advanced one

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1527]

**Comment by Sewer56** [comment]
I brought this up during standup.
For context, `_provider.GetKeyedService<IModInstaller>("AdvancedInstaller")` returns `null` when it shouldn't.

Probably a simple regression from a change of how we set up DI at some point.

**Comment by Sewer56** [comment]
I fixed this on my branch that updates the mod library.

**Comment by Al12rs** [comment]
Fixed in 
- #1529
