### ISSUE TITLE
Log out on app

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1531]
Currently when using the app if you click on your profile icon whilst being logged in it will log you out. 

There should be an extra step in there to confirm logout before the app logs the user out.

**Comment by LukeNexusMods** [comment]
@captainsandypants Can you have a think about this please?

**Comment by erri120** [comment]
Will be done with https://github.com/Nexus-Mods/NexusMods.App/issues/1552.
