### ISSUE TITLE
Library - Remove Item

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1538]
As a user 
I want to remove a mod from the library
So that I have the ability to make decisions about what I see in there but also to remove failed or cancelled mod installations. 

This is feedback from users that were testing in the office. 

@captainsandypants Ill put this one in your column for now to see if you have any designs for this and if you agree that it will compliment the UX.

**Comment by Sewer56** [comment]
Oh, this was done, by yours truly. I can close this.
