### ISSUE TITLE
User profile button and logout design improvement

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1552]
Improved design for user profile button, has states and a dropdown arrow to show it can be clicked.
On click, dropdown menu is show with options for:

My profile - Opens browser to `https://nexusmods.com/users/***userID***`
Account settings - Opens browser to `https://users.nexusmods.com/account/security`
Sign out - Signs you out of the app

## Designs

[Figma designs](https://www.figma.com/design/UNwKwbexsX5gXFNJtJ4eqf/%F0%9F%93%B1-Login?node-id=429-2585&t=hqCVMHFaZDIhVZrA-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/6c4a83b9-d78c-440d-a8b0-3c037fabe8a9)

**Comment by erri120** [comment]
The "View app logs" and "Give feedback" items feel very out-of-place. I think a second button with a debug icon specifically for those two items would be much better.

**Comment by captainsandypants** [comment]
We could add a dropdown to the help icon and move these under there

**Comment by Pickysaurus** [comment]
@captainsandypants Small terminology mismatch.

We say "Log in" and "Sign out". Should it be "Log in" and "Log out" or "Sign In" and "Sign out"?

**Comment by captainsandypants** [comment]
@erri120 The user avatar is missing the `rounded-full` border radius.
