### ISSUE TITLE
Selective GameFiles Backup

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1578]
As a user of the nexus mods app
I want to be able to decide if I use the undo feature
So that I can decide if I want the backup to use additional hard drive space

Allowing users to decide if they want to use the backup/undo feature is something that has been heard from the feedback received.  Users want to choose if the app uses additional drive space.

**Comment by Al12rs** [comment]
Duplicate of #899

**Comment by Al12rs** [comment]
See relevant comments from 
- #899
