### ISSUE TITLE
Change "Activate & apply" to "Apply" on button label & Primary button label colour update

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1583]
When user enables multiple profiles, they can see "Activate & apply" as the button label, rather than just "Apply".

Change to "Apply"

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/f94e8b13-ccde-4276-8851-2abf7c07d133)

**Comment by Al12rs** [comment]
We don't have multiple loadouts yet so thins should not be a problem for now
