### ISSUE TITLE
"My Mods" empty state improvement

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1589]
Please include the Library icon.

[Figma design](https://www.figma.com/design/Ntr9PttR5VrqpTRwwZHzLu/%F0%9F%93%B1-Mod-list---adding%2Fremoving-mods?node-id=3605-59526&t=00XU22IbwzZB1nVd-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/052a872a-288c-4ec4-968d-a35f14831ffa)

**Comment by erri120** [comment]
Related to #1600.
