### ISSUE TITLE
"Library" empty state improvement

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1591]
[Figma link](https://www.figma.com/design/5LmVL8YpgDHFSFA76fgCZA/%F0%9F%93%B1Mod-library?node-id=110-561&t=yHDmU7BTi9YD2Sr9-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/7f8948a7-7f3a-4807-8871-86788ffc85d4)

**Comment by erri120** [comment]
Related to #1600.
