### ISSUE TITLE
Installing a Mod in One Game's Library Prevents it from being Installed in Another Game's Library

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#1605]
# Bug Report

## Summary

If a mod is added to the Mod Library in one Game, it cannot be added to the Mod Library in another game.

This happens if the source origin of the mod is the same. 
For example: If you install an archive from same location, or a mod file from the same download on the site.

## Steps to reproduce

The easiest way to reproduce this is with a local archive on disk.

1. Download a mod from the Nexus

Then do the following

1. Manage Game A (e.g. Stardew Valley)
2. Add downloaded mod via `From Drive` in Stardew's Library
3. Manage Game B (e.g. Skyrim SE)
4. Add (the same) downloaded mod via `From Drive` in Skyrim's Library

(Note: Although Library is scoped per loadout, the downloaded items currently appear to be scoped per game, this may be a bug of its own worth reporting.)

## What is the expected behaviour?

When the mod is added to the second game's library, it should appear in that library.

However no mod appears after being added.

## Other information

It may be a bit unclear as to why you'd want this at first.

The reason comes down to generic, non game-specific mods and utilities; as well as general purpose mod loaders.

Arbitrary Examples:

- BepinEx (Unity Games)
- ReShade

**Comment by nbiju-nexusmods** [comment]
Hi @Sewer56 , I wanted to check if this is still a bug. On Linux, I can add mods for Stardew Valley and Cyberpunk to both libraries (Library and Library New). Is there anything I might be missing? Thank you!



![Image](https://github.com/user-attachments/assets/f37874f0-4437-48d6-a983-01bf0d1f0287)

**Comment by Sewer56** [comment]
@nbiju-nexusmods I believe this is fixed in the latest dev releases.
