### ISSUE TITLE
Premium pill in topbar change

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1608]
Change Premium pill to a badge just using the Title/MD/Semi typography style

[Figma link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=437-2192&t=vTR45Pqi1V8KWQrh-1)

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/07222729-3f6a-40b3-9f59-73613df7793b)

**Comment by insomnious** [comment]
Figma shows a circular avatar image so will add that too
