### ISSUE TITLE
[Up For Grabs] Multiple Registration of DI Services Causing Runtime Failures when using DI to get IEnumerable<TService>

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#162]
# Bug Report

## Summary

We have a problem with multiple registration of various services to the DI Container.  

This can lead to unexpected runtime behaviour (or even failure for some code) when we use DI to inject into constructors which take `IEnumerable<TService>` [these add all registrations as parameter; and thus contain duplicates].  

## Steps to reproduce

Easiest way to reproduce is by trying to hash a folder, e.g.
`NexusMods.App.exe hash-folder -f <SOME_COOL_FOLDER_NAME>`

Set a breakpoint here: https://github.com/Nexus-Mods/NexusMods.App/blob/ad5c1c0b87715274ef039454ec833bb5200852c9/src/NexusMods.App/CLI/Renderers/Spectre.cs#L15-L18

And observe there are duplicates in the `IEnumerable`.  
Resuming the program will lead to runtime failure.

## What is the expected behaviour?

There are no duplicates registered in DI.  
Hash operation completes successfully.  

## Other information

Issue originally introduced for `DataModel` in 0cc002f100193251ead2328354c683dcef1dc38b [OAuth Authentication].  
Unknown if this affects other services [I have not investigated]. 

Found this during my refactoring. Up for grabs and relatively easy to fix.

**Comment by halgari** [comment]
This may be why we're getting occasional build failures in CI
