### ISSUE TITLE
`uninstall-app` CLI command has no feedback

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1634]
# Improvement

## Currently 
When running the `uninstall-app` command via CLI there is no feedback to say that something is happening (or has happened) 

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/83ceb28c-f248-4a85-852e-1ad1db7e162b)

## We want
Show a message in the console to confirm the command has been accepted. 

## Supporting Information
_(Include any supporting screenshots etc to support the above)_

## Design
_(Any designs to required for this feature)_

**Comment by Al12rs** [comment]
Closing in favour of #1664
