### ISSUE TITLE
OpenUrl broken on Windows

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#165]
# Bug Report

## Summary
We can't log into the app currently due to `explorer.exe <url>` opening a copy of Windows Explorer instead of the default app. Not sure if this is a problem with our login URL or the way we're calling explorer. 

## Steps to reproduce
Try and login via the app, a file manager window opens instead of the default browser.

## What is the expected behaviour?
A browser opens.

**Comment by erri120** [comment]
I think `explorer.exe <url>` has to be executed in a shell context. The original code uses it:

```csharp
new ProcessStartInfo(url) { UseShellExecute = true }
```

However, CliWrap creates its own PSI behind the scenes.

**Comment by Sewer56** [comment]
Here's what I do in Reloaded-II

```csharp
/// <summary>
/// Opens an URL with default associated program.
/// </summary>
public static void OpenFileWithDefaultProgram(string url)
{
    Process.Start(new ProcessStartInfo("cmd", $"/c start \"\" \"{url}\"")
    {
        CreateNoWindow = true,
        WindowStyle = ProcessWindowStyle.Hidden
    });
}
```

You might have some luck with starting from cmd.
