### ISSUE TITLE
Bug: SVG Icons in App Cannot be Recoloured

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#1666]
# Bug Report

## Summary

All icons that are imported via SVG files in the App cannot currently be recoloured.

As part of 
-  https://github.com/Nexus-Mods/NexusMods.App/issues/1551

My intent is to fix this, however, because this is a bit more involved; I'm lifting this out to separate PR/issue.
More technical info will be posted here.

## Steps to reproduce

- Toggle individual left menu items.

## What is the expected behaviour?

Items should change in colour, some of them do not; they happen to be SVGs.

## Other information

We need an improved mechanism for loading vectors.

Previously we loaded vectors only by the path, i.e. 

```csharp
Geometry.Parse(M12.46 17.9912L18.1722 13.5441L19.445 12.5584L12.46 7.12561L5.47498 12.5584L6.74004 13.5441L12.46 17.9912Z)
```

This has the flaw of not loading icons in the correct size, a.k.a.
- https://github.com/Nexus-Mods/NexusMods.App/issues/1551

The cause for this appears to be the lack of a ViewBox.

Many of the icons on Figma contain padding on the edges.
When a ViewBox is missing, this padding is not present, thus the icons are displayed larger than the design.

Consider the SVG version of the above icon

```xml
<svg width="25" height="25" viewBox="0 0 25 25" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" clip-rule="evenodd" d="M12.46 17.9912L18.1722 13.5441L19.445 12.5584L12.46 7.12561L5.47498 12.5584L6.74004 13.5441L12.46 17.9912Z"/>
</svg>
```

Note the `viewBox="0 0 25 25"` field here. We need to make a control which is `25x25`, and THEN render the path inside that control. This will in turn include the padding and the sizes should match.

To get this to working I believe we need a variation of `Avalonia.Controls.PathIcon`, or at least something that derives from `DrawingImage` and `IImage`.

The easiest approach would probably be making a variation of [IconImage.cs](https://github.com/Projektanker/Icons.Avalonia/blob/main/src/Projektanker.Icons.Avalonia/IconImage.cs) from Projectanker.

**Comment by erri120** [comment]
> To get this to working I believe we need a variation of Avalonia.Controls.PathIcon, or at least something that derives from DrawingImage and IImage.

See #1661. `SvgImage` is what you're looking for. This is a control that also implements `IImage` specifically for SVGs.

**Comment by Sewer56** [comment]
> See #1661. `SvgImage` is what you're looking for. This is a control that also implements `IImage` specifically for SVGs.
> 
> We can probably update `UnifiedIcon` to also use `SvgImage`.

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/77fd4aa0-49b7-4ec6-b553-05b56f45e480)

I tried this, but it doesn't seem to do the trick, unfortunately.

**Comment by erri120** [comment]
Not sure what the image is supposed to show, but if that didn't work, then we'd just have to pass custom CSS to the `Svg` control.

**Comment by Al12rs** [comment]
You might need to do some trickery in `UnifiedIcon.cs` to force the change notification to the underlying Foreground property or whatever else the SVGImage uses:
https://github.com/Nexus-Mods/NexusMods.App/blob/5aac9e57276af679d2de7e108a83aea4af218089/src/NexusMods.Icons/UnifiedIcon.cs#L87

**Comment by erri120** [comment]
> You might need to do some trickery in `UnifiedIcon.cs` to force the change notification to the underlying Foreground property or whatever else the SVGImage uses:
> 
> https://github.com/Nexus-Mods/NexusMods.App/blob/5aac9e57276af679d2de7e108a83aea4af218089/src/NexusMods.Icons/UnifiedIcon.cs#L87

That's the thing, the `Svg` control doesn't have a `ForegroundProperty`. Everything is controlled via CSS since it just gets passed down to Skia.

**Comment by erri120** [comment]
Probably need to do something cursed like this:

```csharp
 else if (change.Property == ForegroundProperty && Content is Avalonia.Svg.Skia.Svg svg)
        {
            if (change.NewValue is not SolidColorBrush brush) return;
            var css = $"svg {{ color: {brush}; }}";
            Avalonia.Svg.Skia.Svg.SetCss(svg, css);
        }
```

**Comment by Sewer56** [comment]
> but it's probably something like this.

I was away for 10 mins for a meal, but yeah, it's pretty much like this.

If you see the [Projectanker solution](https://github.com/Projektanker/Icons.Avalonia/blob/main/src/Projektanker.Icons.Avalonia/IconImage.cs), it's similar, it exports a brush property, and an update on the brush is propagated to the underlying geometry object.
