### ISSUE TITLE
Stardew Valley - Multiple installs of SMAPI cause unexpected diagnostics

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1672]
# Bug Report

## Summary
When multiple versions of SMAPI are installed to the same loadout, a Health Check message starts to behave unexpectedly. 

If you have two SMAPIs installed (e.g. v3 and v4) but have disabled the older one, the app will report that SMAPI is disabled, even though there is a build of SMAPI enabled in the loadout. 

## Steps to reproduce
1. Install SMAPI twice (see screenshot)
2. Disable one of the SMAPIs
3. See the diagnostic message

## What is the expected behaviour?
_(What did you expect to happen instead?)_

## Other information
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/baeebd92-02a2-4673-b44d-ab663b4edf4b)
Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by erri120** [comment]
Issue comes from using the same result from checking if SMAPI is installed, for checking if SMAPI is disabled. Relevant code:

https://github.com/Nexus-Mods/NexusMods.App/blob/2e72a5f78d4f9411ad4542cba1eb5ffa487bb8b5/src/Games/NexusMods.Games.StardewValley/Emitters/MissingSMAPIEmitter.cs#L20-L37

Solution is getting the first enabled SMAPI mod.
