### ISSUE TITLE
Round file sizes to less decimal places

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1694]
# Improvement

## Currently 
We round file sizes to 3 decimal places. There doesn't appear to be much value to the user in showing this level of precision. 

## We want
Consider rounding these sizes (and any other sizes we display in the app) to a single decimal place.

e.g. 39.347MB -> 39.3MB

## Supporting Information
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/eef61c81-5e4c-4208-8a3d-7050e5a8418f)

## Design
_(Any designs to required for this feature)_

**Comment by LukeNexusMods** [comment]
Change to the humanised design.

**Comment by insomnious** [comment]
Prob do with updating [NumberExtension.cs](https://github.com/Nexus-Mods/NexusMods.Paths/blob/main/src/NexusMods.Paths/Extensions/NumberExtensions.cs) so it's a global change.

**Comment by insomnious** [comment]
Information from @erri120 (taken from Slack)

We have two options: change Size.ToString to use Humanize, that'll require no UI changes, or change the UI code to have both a data and string property, similar to the formatted date properties in LibraryItemModel. I'm fine with the first option but it does mean taking on an additional dependency for the path lib



Could also just change the formatted string in our custom method, if we want to keep that around.

**Comment by LukeNexusMods** [comment]
This is down to two decimal places in the latest version
