### ISSUE TITLE
Regression: Entity IDs aren't serialized properly

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#1697]
Due to the recent DB changes in #1626, Entity IDs aren't serialized properly to JSON, which is required for Workspace Data:

![2024-06-27_14-53-24](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/bd13a546-ff92-44e7-a695-dfb5cacfc4c1)

**Comment by Sewer56** [comment]
I've confirmed this happens 👍

**Comment by LukeNexusMods** [comment]
Efficiency work, fixing this would allow code to be deleted and the app simplified. 

Around 2 days work
