### ISSUE TITLE
Rapidly toggling mods leads to a strange UX

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1698]
# Bug Report

## Summary
Rapidly toggling mods off causes the table to refresh and "forget" some of the choices made. 

## Steps to reproduce
1. Rapidly disable or enable several mods.
2. Watch the UI flicker and appear to temporarily undo some changes
3. Wait a few seconds for it catch up. 

## What is the expected behaviour?
The UI keeps up with user input. 

## Other information

https://github.com/Nexus-Mods/NexusMods.App/assets/31670524/d62c1401-9be2-49a9-bf2b-a52fb8ecf872

[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/16014653/nexusmods.app.slim.current.log)
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16014654/nexusmods.app.main.current.log)

**Comment by LukeNexusMods** [comment]
We need to investigate this further to replicate the issue. But we have ideas as to the fix.

**Comment by LukeNexusMods** [comment]
Was this custom built or the 0.5.2 release?

**Comment by erri120** [comment]
Doesn't apply anymore since the page has been reworked.
