### ISSUE TITLE
Font style updates

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1706]
Font styles need to be updated to stay in line with the website styles. The table below lists the things that need to be changed for each style:

| Style name | Old | New |
| -------- | ------- | ------- |
| heading/2xl/semi | Family: Montserrat | Family: Inter |
| heading/xl/semi | Family: Montserrat | Family: Inter |
| heading/lg/semi | Family: Montserrat, Tracking: Normal (0px) | Family: Inter, Tracking: Tight (-0.9px) |
| heading/md/semi | Family: Montserrat, Tracking: Wide (0.8px) | Family: Inter, Tracking: Normal (0px) |
| heading/sm/semi | Family: Montserrat, Tracking: Wide (0.6px) | Family: Inter, Tracking: Normal (0px) |
| heading/xs/semi | Family: Montserrat, Tracking: Wide (0.6px) | Family: Inter, Tracking: Normal (0px) |
| title/md/semi | Family: Montserrat | Family: Inter |
| title/sm/semi | Family: Montserrat | Family: Inter |
| title/xs/semi | Family: Montserrat | Family: Inter |
| body/xl/bold | Family: Montserrat, Weight: Bold | Family: Inter, Weight, Semi-Bold |
| body/xl/normal | Family: Montserrat | Family: Inter |
| body/lg/bold | Family: Montserrat, Weight: Bold | Family: Inter, Weight, Semi-Bold |
| body/lg/normal | Family: Montserrat | Family: Inter |
| body/md/bold | Family: Montserrat, Weight: Bold | Family: Inter, Weight, Semi-Bold |
| body/md/normal | Family: Montserrat | Family: Inter |
| body/sm/bold | Family: Montserrat, Weight: Bold | Family: Inter, Weight, Semi-Bold |
| body/sm/normal | Family: Montserrat | Family: Inter |

**Comment by Al12rs** [comment]
[Figma Link](https://www.figma.com/design/8pjtQeNggvVi7RWoLNGV80/%F0%9F%A7%B0-Nexus-Mods-Design-System?m=auto&node-id=3744-12851&t=diadWRjXx63FIda3-1l)
