### ISSUE TITLE
Can't get logged in with firefox or brave.

### ISSUE THREAD

**Issue by rabidrivas** [Nexus-Mods/NexusMods.App#1716]
# Bug Report

## Summary
When logging in after being prompted by the app it doesn't work. Firefox asks to manage link with nxm app but doesn't do anything afterwards and brave pops up a KDE choose app window but the nexus app isn't there.

## Steps to reproduce
Try to log in from the app image with firefox as a default browser. For brave paste the link shown in the app. Using Nobara 40 with KDE (Based on Fedora 40)

## What is the expected behaviour?
To log in

## Other information
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16089685/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/16089686/nexusmods.app.slim.current.log)
[nexusmods.app.slim.04.log](https://github.com/user-attachments/files/16089687/nexusmods.app.slim.04.log)
[nexusmods.app.main.00.log](https://github.com/user-attachments/files/16089688/nexusmods.app.main.00.log)
[nexusmods.app.slim.03.log](https://github.com/user-attachments/files/16089689/nexusmods.app.slim.03.log)
[nexusmods.app.slim.02.log](https://github.com/user-attachments/files/16089690/nexusmods.app.slim.02.log)
[nexusmods.app.slim.01.log](https://github.com/user-attachments/files/16089691/nexusmods.app.slim.01.log)
[nexusmods.app.slim.00.log](https://github.com/user-attachments/files/16089692/nexusmods.app.slim.00.log)

**Comment by Sewer56** [comment]
Most relevant part of log

```
00:00:39.706 [DEBUG] (NexusMods.SingleProcess.CliServer) Received command: nxm://oauth/callback?code=otVjSYtXd3GZFHrK9EaoZ8UdX-eWn4FxK79gs6yqeew&state=3d6710d917084cf1a3fff12f33a7b88b
00:00:50.910 [INFO] (NexusMods.SingleProcess.CliServer) Accepted TCP connection from 48674
00:00:50.945 [DEBUG] (NexusMods.SingleProcess.CliServer) Received command: nxm://oauth/callback?code=otVjSYtXd3GZFHrK9EaoZ8UdX-eWn4FxK79gs6yqeew&state=3d6710d917084cf1a3fff12f33a7b88b
00:02:54.299 [INFO] (Avalonia.ReactiveUI.ViewModelViewHost) ViewModel is null. Falling back to default content.
00:03:04.073 [ERROR] (NexusMods.Networking.NexusWebApi.LoginManager) Unable to login: task was canceled|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Linq.AsyncEnumerable.ObservableAsyncEnumerable`1.MoveNextCore() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToAsyncEnumerable.Observable.cs:line 104
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|95_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 130
   at System.Linq.AsyncEnumerable.<TryGetFirst>g__Core|95_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/FirstOrDefault.cs:line 132
   at System.Linq.AsyncEnumerable.<FirstAsync>g__Core|87_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/First.cs:line 31
   at NexusMods.Networking.NexusWebApi.Auth.OAuth.AuthorizeRequest(CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.NexusWebApi/Auth/OAuth.cs:line 93
   at NexusMods.Networking.NexusWebApi.LoginManager.LoginAsync(CancellationToken token) in /_/src/Networking/NexusMods.Networking.NexusWebApi/LoginManager.cs:line 117
```

I'll leave it to the rest to look into this as am doing repacking things, but this is pretty strange, the App is getting the callback from the browser, just that it hasn't seemingly done anything with it.

**Comment by rabidrivas** [comment]
> Please try the steps here if you haven't already [Why can't I log into the app or download from Nexus Mods?](https://nexus-mods.github.io/NexusMods.App/users/FAQ/#linux)

I am using the app image so I don't have a .desktop file for the app

**Comment by erri120** [comment]
> I am using the app image so I don't have a .desktop file for the app

We generate a `.desktop` file for you. Go to `~/.local/share/applications` and there should be a `nexusmods-app-nxm.desktop` file. Can you copy and paste the contents of that file here?

**Comment by rabidrivas** [comment]
`[Desktop Entry]
Name=NexusMods.App NXM Handler
Terminal=false
Type=Application
Path=/home/rabid/Applications
Exec=/home/rabid/Applications/NexusMods.App.x86_64.AppImage protocol-invoke --url %u
MimeType=x-scheme-handler/nxm
NoDisplay=true
`

Trying to learn here: Why did the app not show when I searched for it if I had a .desktop file? It would be cool if I could use this to launch the app like I do with native apps. Maybe a feature request?

**Comment by erri120** [comment]
> I have followed the steps and it now works but I have two identical entries in the firefox menu that pops up when choosing a handler. And only one of them works. It is fixed for me, but It should be more intuitive.

The next version is going to have a much better experience.

**Comment by RodoMa92** [comment]
Same experience here, but I can't actually log in at all. It doesn't work. Doesn't matter if firefox has Use System Handler for nxm links or manually specify the protocol, the login never comes back to the app. This should be reopened.

**Comment by RodoMa92** [comment]
Log file attached, which seems to have an identical stack trace as the user above.
[nexusmods.app.main.00.log](https://github.com/user-attachments/files/16097179/nexusmods.app.main.00.log)

**Comment by RodoMa92** [comment]
> `[Desktop Entry] Name=NexusMods.App NXM Handler Terminal=false Type=Application Path=/home/rabid/Applications Exec=/home/rabid/Applications/NexusMods.App.x86_64.AppImage protocol-invoke --url %u MimeType=x-scheme-handler/nxm NoDisplay=true `
> 
> Trying to learn here: Why did the app not show when I searched for it if I had a .desktop file? It would be cool if I could use this to launch the app like I do with native apps. Maybe a feature request?
> 
> I have followed the steps and it now works but I have two identical entries in the firefox menu that pops up when choosing a handler. And only one of them works. It is fixed for me, but It should be more intuitive.
> 
> Still, thanks!

You can get that experience already if you "install" the appimage file using GearLevel, it will manage and create a desktop link automatically for you: https://flathub.org/apps/it.mijorus.gearlever

**Comment by LukeNexusMods** [comment]
We believe we have improved this experience in the latest version that will be released next week. 

Thanks very much for reporting it. Hopefully wont be too much longer before you can give it another try and let us know if the issue has been resolved. 

We really appreciate all the feedback you are sending in.

**Comment by rabidrivas** [comment]
Yeah, the issue is resolved. Now I am going to try installing mods. So If the next version improves the overall user experience maybe this issue should be closed. I don't have much experience with github so I leave it up to you
