### ISSUE TITLE
Error read file steam://rungameid/413150

### ISSUE THREAD

**Issue by rosakodu** [Nexus-Mods/NexusMods.App#1727]
# Bug Report

## Summary
I installed the mods, start the game and this error appears

In my PC Arch linux:(  but on my steam deck it works

## Other information
![Снимок экрана_20240706_155047](https://github.com/Nexus-Mods/NexusMods.App/assets/132022924/3bb77adf-c253-4a04-8bfc-7c94aeb92a11)
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16116214/nexusmods.app.main.current.log)

**Comment by erri120** [comment]
Can you upload the `nexusmods.app.main.current.log` file?

**Comment by rosakodu** [comment]
> Можете ли вы загрузить `nexusmods.app.main.current.log`файл?

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16116218/nexusmods.app.main.current.log)

**Comment by erri120** [comment]
> > Можете ли вы загрузить `nexusmods.app.main.current.log`файл?
> 
> [nexusmods.app.main.current.log](https://github.com/user-attachments/files/16116218/nexusmods.app.main.current.log)

That file is almost empty. You can look at the modified date of the files in the logs folder to find the log files for the session where you encountered the issue.

**Comment by rosakodu** [comment]
> > > Можете ли вы загрузить `nexusmods.app.main.current.log`файл?
> > 
> > 
> > [nexusmods.app.main.current.log](https://github.com/user-attachments/files/16116218/nexusmods.app.main.current.log)
> 
> That file is almost empty. You can look at the modified date of the files in the logs folder to find the log files for the session where you encountered the issue.

[nexusmods.app.main.22.log](https://github.com/user-attachments/files/16116522/nexusmods.app.main.22.log)

**Comment by erri120** [comment]
Can you open a terminal and check if you have `xdg-open` available:

```bash
which xdg-open

xdg-open --version
```

If this fails, then you don't have `xdg-open` installed, which we use for launching Steam.

**Comment by rosakodu** [comment]
> Can you open a terminal and check if you have `xdg-open` available:
> 
> ```shell
> which xdg-open
> 
> xdg-open --version
> ```
> 
> If this fails, then you don't have `xdg-open` installed, which we use for launching Steam.
> 
> Check our [Linux Dependencies](https://nexus-mods.github.io/NexusMods.App/users/SystemRequirements/#linux-dependencies) section for more details.

**Comment by rosakodu** [comment]
> > Can you open a terminal and check if you have `xdg-open` available:
> > ```shell
> > which xdg-open
> > 
> > xdg-open --version
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If this fails, then you don't have `xdg-open` installed, which we use for launching Steam.
> > Check our [Linux Dependencies](https://nexus-mods.github.io/NexusMods.App/users/SystemRequirements/#linux-dependencies) section for more details.

xdg-open 1.2.1

**Comment by rosakodu** [comment]
> Can you open a terminal and check if you have `xdg-open` available:
> 
> ```shell
> which xdg-open
> 
> xdg-open --version
> ```
> 
> If this fails, then you don't have `xdg-open` installed, which we use for launching Steam.
> 
> Check our [Linux Dependencies](https://nexus-mods.github.io/NexusMods.App/users/SystemRequirements/#linux-dependencies) section for more details.

THE PROBLEM WAS SOLVED, the fact was that my steam client was installed from the pacman repository, I installed steam from flathab and everything worked out

**Comment by erri120** [comment]
> THE PROBLEM WAS SOLVED, the fact was that my steam client was installed from the pacman repository, I installed steam from flathab and everything worked out

That's odd, I also installed Steam via the `steam` package. Anyways, I'll close the issue since it was a faulty Steam installation. My guess is that you didn't had a proper `.desktop` file for Steam that registered the `steam://` scheme.
