### ISSUE TITLE
Supported games: Differentiate duplicate installations

### ISSUE THREAD

**Issue by tlitookilakin** [Nexus-Mods/NexusMods.App#1729]
# Improvement

## Currently 
If multiple copies of the same supported game are installed in standard locations, the app will detect them all. This is good, but they appear identical, and there is no way to tell which one is which.

## We want
A way of differentiating multiple installs of the same game. 

## Supporting Information
I have two separate GOG installs, as well as a steam install, and they are all used for different things. I'd like to make sure nexus is only managing the one that I have set up specifically for it.

## Design
Preferably display either folder path or launcher name on the 'supported game' card. (IE. steam vs GOG).

**Comment by LukeNexusMods** [comment]
Thanks very much for your feedback. 
We are aware of this and are working on a design so we can display multiple copies of the game from various different sources. From there you can decide which one you would like to manage with the Nexus Mods app.

**Comment by LukeNexusMods** [comment]
https://github.com/Nexus-Mods/NexusMods.App/issues/1225

**Comment by erri120** [comment]
Closing in favor of #1225.

**Comment by tlitookilakin** [comment]
Thank you!
