### ISSUE TITLE
Game specific backup - settings text

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1732]
The text on the settings page related to the game specific toggles needs updating to something more user friendly. 

Also can an experimental tag be added to those options please? 

@captainsandypants Any suggestions for the text needed? 

Please move the game specific settings under the experimental section.

**Comment by captainsandypants** [comment]
**Cyberpunk 2077: Full game backup**
Backup all game folders, including the game asset folders. This experimental setting is intended for developers testing the upcoming restore feature. Please note that this will increase disk space usage.
_Default state - Toggle is DISABLED_

**Cyberpunk 2077: Full game backup**
Backup all game folders, including the Content folder. This experimental setting is intended for developers testing the upcoming restore feature. Please note that this will increase disk space usage.
_Default state - Toggle is DISABLED_
