### ISSUE TITLE
i cant log in

### ISSUE THREAD

**Issue by declanmcmains** [Nexus-Mods/NexusMods.App#1740]
i cant log in and how do i use the code

**Comment by Pickysaurus** [comment]
Please see the FAQ. 
https://nexus-mods.github.io/NexusMods.App/users/FAQ/#why-cant-i-log-into-the-app-or-download-from-nexus-mods

This should be improved in the next version (if you're on Linux).

When raising a bug report it's important to provide all requested information.

**Comment by braiam** [comment]
@Pickysaurus  The faq is broken. Stylesheets and the document itself 404. For some reason you have “media-src http:” in your CSP header (it can only load insecure media?) It happens both in Firefox and Chrome.

**Comment by Al12rs** [comment]
Try this link: https://nexus-mods.github.io/NexusMods.App/users/faq/

**Comment by Pickysaurus** [comment]
I've fixed my original link. I updated the docs, which means the URL has to be lowercase. Regardless, this issue has a workaround and should be improved in the next release.
