### ISSUE TITLE
Won't launch on Kubuntu (0.5.3)

### ISSUE THREAD

**Issue by LiamDawe** [Nexus-Mods/NexusMods.App#1765]
**UPDATE**: After removing the config folders for it in both /.local/state and /.local/share the app did then launch. So some sort of config issue with the new version and using the the configs of the old version I assume.

**Main bug report:**
The latest 0.5.3 release seems to not actually launch on Kubuntu 24.04

Here's what it showed in terminal:

> liam@liam-kub:~$ /home/liam/Downloads/NexusMods.App.x86_64.AppImage 
> Unhandled exception. System.AggregateException: One or more errors occurred. (One or more hosted services failed to start. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.))
>  ---> System.AggregateException: One or more hosted services failed to start. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at NexusMods.StandardGameLocators.ManuallyAddedGame.FindByGameDomain(IDb db, GameDomain value) in /_/src/NexusMods.StandardGameLocators/obj/Release/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_StandardGameLocators_ManuallyAddedGame.Generated.cs:line 39
>    at NexusMods.StandardGameLocators.ManuallyAddedLocator.Find(ILocatableGame game) in /_/src/NexusMods.StandardGameLocators/ManuallyAddedLocator.cs:line 73
>    at NexusMods.DataModel.GameRegistry.FindInstallations()+MoveNext() in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 136
>    at System.Collections.Generic.AsyncEnumerableHelpers.ToSet[T](IAsyncEnumerable`1 source, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 108
>    at System.Collections.Generic.AsyncEnumerableHelpers.ToSet[T](IAsyncEnumerable`1 source, IEqualityComparer`1 comparer, CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncEnumerableHelpers.cs:line 108
>    at System.Linq.AsyncEnumerable.DistinctAsyncIterator`1.ToArrayAsync(CancellationToken cancellationToken) in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Distinct.cs:line 56
>    at NexusMods.DataModel.GameRegistry.Startup(CancellationToken token) in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 69
>    at NexusMods.DataModel.GameRegistry.StartAsync(CancellationToken cancellationToken) in /_/src/NexusMods.DataModel/GameRegistry/GameRegistry.cs:line 151
>    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
>    --- End of inner exception stack trace ---
>    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
>    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
>  ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
>    at NexusMods.Networking.Downloaders.Tasks.State.DownloaderState.All(IDb db) in /_/src/Networking/NexusMods.Networking.Downloaders/obj/Release/net8.0/NexusMods.MnemonicDB.SourceGenerator/NexusMods.MnemonicDB.SourceGenerator.ModelGenerator/NexusMods_Networking_Downloaders_Tasks_State_DownloaderState.Generated.cs:line 81
>    at NexusMods.Networking.Downloaders.DownloadService.StartAsync(CancellationToken cancellationToken) in /_/src/Networking/NexusMods.Networking.Downloaders/DownloadService.cs:line 162
>    at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)<---
> 
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at System.Threading.Tasks.Task.Wait(TimeSpan timeout, CancellationToken cancellationToken)
>    at NexusMods.App.Program.Main(String[] args) in /_/src/NexusMods.App/Program.cs:line 63
> Aborted (core dumped)

Only log it gave was this:
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16235143/nexusmods.app.main.current.log)

**Comment by Sewer56** [comment]
I'm guessing we probably made an unintended breaking change from last release.
The update was meant to be breaking in any case; so it's within expectation.

Next release will be breaking too.

**Comment by erri120** [comment]
> I should note, after removing the config folders for it in both /.local/state and /.local/share the app did then launch. So some sort of config issue with the new version and using the the configs of the old version I assume.

The new release is expected to require a clean installation. We haven't added support for migrations yet.
