### ISSUE TITLE
Fix the strange API of DataStore

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#177]
# Bug Report
The way immutable Entities work in IDataStore right now is a tad strange: they are generated by persisting the object and getting the hash of the contents of the value. This has the nasty side-effect of making a *get* on an entity a mutating operation. 

## Fix
We should make ID generation for entities more explicit and require an explicit "Persist" call. We can probably do this by throwing an error whenever a `.DataStoreId` happens on a unpersisted entity.

**Comment by Sewer56** [comment]
This was fixed in #178
