### ISSUE TITLE
Change the text in the "Update Available" dialog box

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1776]
Please can you update the notification that alerts app users to updates so that it points to the page where you are able to see the breaking changes warning before they download it. 

So that the users are aware as soon as possible that the download will require a full reinstall of all mods etc. 

We are getting more and more users who will already have the app installed and will need to know about breaking changes in a more obvious way. 

When we move to a more robust migration system it will mitigate this. 

New text:

Update available
{OLD} -> {NEW}
Please note: In order to update to the latest version of the app you need to uninstall all your mods and the current version of the app. [Read more](http://link/).
[Later] [View Changelog]

**Comment by Al12rs** [comment]
Some references:

Current in app:
![image](https://github.com/user-attachments/assets/45f92f39-656f-457f-bc9c-0ee904ebee4b)

Figma:
![image](https://github.com/user-attachments/assets/ec6a5551-8d95-4d30-9b81-668b1e79b6a1)
https://www.figma.com/design/oWcjirFQDdwyeVPGiCUgWP/%F0%9F%93%B1-Update-application?node-id=0-1&m=dev

**Comment by insomnious** [comment]
I've just done this now but will discuss on Monday given the fact that app/figma/what is needed is a bit wishy washy.

![Image](https://github.com/user-attachments/assets/f0d8dfbe-0e70-443e-b6f2-54a2355351c9)

**Comment by insomnious** [comment]
@captainsandypants has updated Figma and so we are going with this. 'View update' button is linking to https://github.com/Nexus-Mods/NexusMods.App/releases/latest

![image](https://github.com/user-attachments/assets/820f01b3-157f-480e-b02f-317d3f968e51)
