### ISSUE TITLE
As a user, I want to download a mod

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#180]
## User Story

As a user, I want to download mods from the Nexus Mods website and have them handled by NMA.

## Requirements
**Must haves:**
NMA detects download and handles process.
User can view download speed and progress.
User can pause/resume.
User can cancel download.

**Won't haves:**
An interface to browse mods and download directly from within the app.

## Issues
https://github.com/Nexus-Mods/NexusMods.App/issues/254 - Create 'In Progress' page layout
https://github.com/Nexus-Mods/NexusMods.App/issues/255 - Allow users to pause downloads
https://github.com/Nexus-Mods/NexusMods.App/issues/256 - Allow users to cancel downloads
https://github.com/Nexus-Mods/NexusMods.App/issues/257 - Display total download progress
https://github.com/Nexus-Mods/NexusMods.App/issues/252 - Component - Sidebar button, "Download" variant

## Designs

https://www.figma.com/file/Ntr9PttR5VrqpTRwwZHzLu/Mod-list?node-id=252%3A24430&t=cQvpDNHXgW3eiUYd-1

![Image](https://user-images.githubusercontent.com/118466382/230349031-56d64ea0-2fbf-4f36-8f24-a9ed9789e609.png)

### Scenario 1

**Given**
I have download a mod from Nexus Mods
**When**
The app detects the download
**Then**
It appears in the "In progress" page in the download section of the app.

### Scenario 2

**Given**
I am downloading a mod in the app
**When**
I select the mod from the download section and click pause/resume
**Then**
The mod pauses/resumes downloading (paused downloads remain on the "In progress" page

### Scenario 3

**Given**
I am downloading a mod in the app
**When**
I select the mod from the download section and click cancel
**Then**
The cancelled download is stopped and the mod is removed from the list (it does not appear on the "Completed" downloads page)

### Scenario 4

**Given**
I am downloading a mod in the app
**When**
The mod finished downloading
**Then**
The mod is removed from the "In progress" page and is added to the "Completed" page.

### Scenario 5

**Given**
I have mod/s in the "Completed" list
**When**
I click select the mod and click "clear" from the toolbar 
**Then**
The mod is removed from the "Completed" list. (alternatively, click "clear all" and all completed downloads are cleared)

**Comment by Greg-Nexus** [comment]
Suggested breakdown of this issue:

1. Create 'Downloads - In Progress' page, add layout and display 'In Progress' table without the pause/cancel/total progress/speed/time remaining.
2. Add 'Pause' feature.
3. Add 'Cancel' feature.
4. Add 'Speed'/'Time Remaining'.
5. Add 'Total Progress'.
6. Create 'Downloads - Complete' page.
