### ISSUE TITLE
Adding a 27th loadout results in a duplicate name

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1804]
# Bug Report

## Summary
Added loadouts 1-26 correctly names them for each letter of the alphabet. Adding a 27th loadout results in a duplicate name.
![image](https://github.com/user-attachments/assets/bd64e847-3b61-4a23-8f5e-5aa2d1faa4fe)

## Steps to reproduce
1. Manage a game and keep creating loadouts until you have a duplicate.

## What is the expected behaviour?
Loadouts are uniquely named and/or capped at 26. 

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by Al12rs** [comment]
Lol I was wondering how long it would take for this to come up. I believe duplicate names are better than blocking loadout creation. Internally loadouts are identified with a unique id, the name is decorative, only there to allow user to discriminate them.

If 26 loadouts is considered a large enough number that users would be unlikely to reach it, enough so to cap them to it, then it is also a large enough number that there should not be a problem if we allow it but with same name. 

One letter names are not a long term solution in any case, and loadout names will allow renaming at some point.

**Comment by erri120** [comment]
We could just start iterating over numbers. Or make a setting to choose the behavior.

**Comment by captainsandypants** [comment]
Or go: `AA, AB, AC, AD` to ` ZX, ZY, ZZ` as if we use numbers it only gets us 10 more before we have to handle two characters in the UI anyway

**Comment by Sewer56** [comment]
> Or go: `AA, AB, AC, AD` to ` ZX, ZY, ZZ` as if we use numbers it only gets us 10 more before we have to handle two characters in the UI anyway

This is what I'd personally prefer.
It gives us around 26^2 = (676) slots.
