### ISSUE TITLE
Replace toolbar buttons with new buttons

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1824]
New button with many variants that will replace the following existing buttons. Set state attribute the same as existing, all other attributes listed below:

# Toolbar buttons replacement details

### Text-dropdown: Primary
Type = Primary
Size = sm
Filled = None
Show label = True
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = False

### Text-dropdown: Secondary
Type = Secondary
Size = sm
Filled = Strong
Show label = True
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = False

### Text-dropdown: Tertiary
Type = Tertiary
Size = sm
Filled = None
Show label = True
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = False

### Text: Primary
Type = Primary
Size = sm
Filled = None
Show label = True
Show icon right = False
Show icon left = False

### Text: Secondary
Type = Secondary
Size = sm
Filled = Strong
Show label = True
Show icon right = False
Show icon left = False

### Text: Tertiary
Type = Tertiary
Size = sm
Filled = None
Show label = True
Show icon right = False
Show icon left = False

### Text-icon: Primary
Type = Primary
Size = sm
Filled = None
Show label = True
Show icon right = False
Show icon left = True

### Text-icon: Secondary
Type = Secondary
Size = sm
Filled = Strong
Show label = True
Show icon right = False
Show icon left = True

### Text-icon: Tertiary
Type = Tertiary
Size = sm
Filled = None
Show label = True
Show icon right = False
Show icon left = True

### Text-icon-dropdown: Primary
Type = Primary
Size = sm
Filled = None
Show label = True
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = True

### Text-icon-dropdown: Secondary
Type = Secondary
Size = sm
Filled = Strong
Show label = True
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = True

### Text-icon-dropdown: Tertiary
Type = Tertiary
Size = sm
Filled = None
Show label = True
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = True

### Icon: Primary
Type = Primary
Size = sm
Filled = None
Show label = False
Show icon right = False
Show icon left = True

### Icon: Secondary
Type = Secondary
Size = sm
Filled = Strong
Show label = False
Show icon right = False
Show icon left = True

### Icon: Tertiary
Type = Tertiary
Size = sm
Filled = None
Show label = False
Show icon right = False
Show icon left = True

### Icon-dropdown: Primary
Type = Primary
Size = sm
Filled = None
Show label = False
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = True

### Icon-dropdown: Secondary
Type = Secondary
Size = sm
Filled = Strong
Show label = False
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = True

### Icon-dropdown: Tertiary
Type = Tertiary
Size = sm
Filled = None
Show label = False
Show icon right = True
Icon right: Keyboard_arrow_down
Show icon left = True

**Comment by insomnious** [comment]
Fixed by https://github.com/Nexus-Mods/NexusMods.App/pull/2197
