### ISSUE TITLE
Update button styles

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1833]
Current buttons to be replaced with the new "Button" component. This is to stay in line with the website, improve UI and clean up the design system

# Standard buttons

OLD
![Image](https://github.com/user-attachments/assets/c27e837c-863c-4fa0-b355-a3272d82c3c7)

NEW
![Image](https://github.com/user-attachments/assets/160b294b-e2eb-4eb5-8af9-16b893fc4ad8)

[Figma link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=1949-6839&t=UmvVuhDcKUko1zVF-1)

## Replace the following variants of the current component with these variants in the new component

**Note: If an old button specifies an icon, set that same icon to “Icon left” on the new button**

**REPLACE:** Primary + icon
**WITH:** Type=Primary, Size=md, State=Default, Filled=None, Show label=True, Show icon right=False, Show icon left=True.

**REPLACE:** Primary
**WITH:** Type=Primary, Size=md, State=Default, Filled=None, Show label=True, Show icon right=False, Show icon left=False.

**REPLACE:** Primary Outlined + icon
**WITH:** Nothing - Can be removed

**REPLACE:** Primary Outlined
**WITH:** Nothing - Can be removed

**REPLACE:** Secondary + icon
**WITH:** Type=Secondary, Size=md, State=Default, Filled=Strong, Show label=True, Show icon right=False, Show icon left=True.

**REPLACE:** Secondary
**WITH:** Type=Secondary, Size=md, State=Default, Filled=Strong, Show label=True, Show icon right=False, Show icon left=False.

**REPLACE:** Secondary outlined + icon
**WITH:** Type=Secondary, Size=md, State=Default, Filled=None, Show label=True, Show icon right=False, Show icon left=True.

**REPLACE:** Secondary outlined
**WITH:** Type=Secondary, Size=md, State=Default, Filled=None, Show label=True, Show icon right=False, Show icon left=False.

**REPLACE:** Tertiary + icon
**WITH:** Type=Tertiary, Size=md, State=Default, Filled=None, Show label=True, Show icon right=False, Show icon left=True.

**REPLACE:** Tertiary
**WITH:** Type=Tertiary, Size=md, State=Default, Filled=None, Show label=True, Show icon right=False, Show icon left=False.

# Rounded buttons

OLD
![Image](https://github.com/user-attachments/assets/e81dc341-9ffc-47f0-919e-9f73d4bff535)

NEW
![Image](https://github.com/user-attachments/assets/0bdca703-dcf9-45e3-b73f-b758b6c65f35)

[Figma link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=1949-6839&t=UmvVuhDcKUko1zVF-1)

## Replace the following variants of the current component with these variants in the new component

**Note: If an old button specifies an icon, set that same icon to “Icon left” on the new button**

**REPLACE:** Primary no icon, State=Default, Pill=False
**WITH:** Type=Tertiary, Size=sm, State=Default, Filled=weak, Show label=True, Show icon right=False, Show icon left=False.

**REPLACE:** Primary, State=Default, Pill=False, Icon=”Add”
**WITH:** Type=Tertiary, Size=sm, State=Default, Filled=weak, Show label=True, Show icon right=False, Show icon left=True, Icon left=”Add”

**REPLACE:** Primary-icon-only, State=Default
**WITH:** Type=Tertiary, Size=sm, State=Default, Filled=weak, Show label=False, Show icon right=False, Show icon left=True

**REPLACE:** Primary, State=Active, Pill=False, Icon=”Close”
**WITH:** Type=Secondary, Size=sm, State=Default, Filled=Strong, Show label=True, Show icon right=False, Show icon left=True

**REPLACE:** Primary, State=Semi-Active, Pill=False, Icon=”Close”
**WITH:** Type=Secondary, Size=sm, State=Default, Filled=Weak, Show label=True, Show icon right=False, Show icon left=True

**REPLACE:** Primary, State=Semi-Active, Pill=False, Icon=”Close”
**WITH:** Type=Secondary, Size=sm, State=Default, Filled=Weak, Show label=True, Show icon right=False, Show icon left=True

**REPLACE:** The blue filled one
**WITH:** Type=Primary, Size=sm, State=Default, Filled=Strong, Show label=True, Show icon right=False, Show icon left=True

**REPLACE:** The blue outlined one
**WITH:** Type=Tertiary, Size=sm, State=Default, Filled=Weak, Show label=True, Show icon right=False, Show icon left=True

**Comment by insomnious** [comment]
We've decided to turn this task into two parts due to the button on the design system being very out of sync with the apps current design.

First part, and to close this ticket, is to make as little tweaks as necessary for the app to more closely match the design system. This is primarily buttons (both standard button and rounded button as mentioned in the task) and also the combobox used in settings.

Second part, now that the design system has all of the button types and states decided, is going to be the creation of a button component that caters for all of the variations we can see in Figma. This will better prepare the app for the future with less code repetition, quicker iterations, a cleaner design -> app workflow and easier long term maintenance. This will be on a new project task.
