### ISSUE TITLE
Add game store to game tiles and update design

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#1860]
## Currently
The game tiles do not show what store the game is from. So if a user has a game from two different stores there is no way to tell which one they are adding. The design was also a placeholder design and needs to be updated.

## We want
To add the game store to the tile as an icon and update the design to be easier to consume.

**Stretch goals:**
Add tooltip on hover to game store icon that has the name of the game store.
Add disabled states for the in progress actions of "Adding" and "Deleting".

## Design

[Figma component link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=2102-7789&t=6OzTWX2JEe6i6dKg-1)

[Figma game page link](https://www.figma.com/design/droQp7IUqRCq5AUGmXldvP/%F0%9F%93%B1-Add%2Fmanage-games?node-id=1072-2728&t=nvVOZ7lPEQdJWXFU-1)

![Image](https://github.com/user-attachments/assets/f2ace875-ea0c-4833-bbb0-decc0f0c9885)

**Comment by erri120** [comment]
Do we have icons for all game stores?

- Unknown
- Manually Added
- Steam
- GOG
- EGS
- EA Desktop
- Xbox Game Pass

**Comment by insomnious** [comment]
We will need Unknown and Manually Added @captainsandypants, I've got the others already app.

**Comment by erri120** [comment]
Unknown can just be a "?", it's our fallback value in case something goes wrong.

**Comment by insomnious** [comment]
Sure, I'll just use one of these two
![image](https://github.com/user-attachments/assets/70007525-defc-4388-a502-d0179a7fe54c)
