### ISSUE TITLE
App Crashes Immediately On Launch

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/NexusMods.App#1865]
EDIT: It worked after I completely deleted the LOCALAPPDATA folder. I had previously installed an older version on this machine some months ago. Maybe there needs to be some file removal from older, incompatible versions?

# Bug Report

## Summary
_(Summarize the bug encountered concisely ensuring you state the current behaviour)_
App Crashes immediately on launch with no message.

## Steps to reproduce
_(How one can reproduce the issue - this is very important)_
Try to run app. Crash immediately. 

## What is the expected behaviour?
_(What did you expect to happen instead?)_
App starts.

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16553768/nexusmods.app.main.current.log)
[nexusmods.app.slim.current.log](https://github.com/user-attachments/files/16553769/nexusmods.app.slim.current.log)

**Comment by erri120** [comment]
We don't support upgrading from one version to another just yet.

Related: #1765.
