### ISSUE TITLE
`AbsolutePath` API Improvements

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#189]
From previous discussions:
- https://github.com/Nexus-Mods/NexusMods.App/pull/187#discussion_r1135610423
- https://github.com/Nexus-Mods/NexusMods.App/pull/187#discussion_r1135778351

`AbsolutePath.Directory` is currently nullable, and the only place where it's set to `null`, is in `FromFullPath` when the input path isn't rooted. This raises the question, if a path that is not rooted, meaning it doesn't have a root directory (eg: `foo`) is considered an "absolute path".

`AbsolutePath.GetFullPath` has two versions: `string GetFullPath()` and `void GetFullPath(Span<char>)`. Both methods create a full path, except one writes it to a span, while the other simply returns a heap-allocated string. Internally, they work differently and it might be worth consolidating the internals. `string GetFullPath` could call `GetFullpath(Span<char>)` instead of doing something else internally.

`GetFullPathWithSeparator` should be phased out now that #187 and #176 have been merged, however the custom file/directory enumeration methods still need to be converted to use `IFileSystem` from #176.

**Comment by Sewer56** [comment]
> Internally, they work differently and it might be worth consolidating the internals. string `GetFullPath` could call `GetFullpath(Span<char>)` instead of doing something else internally.

For a long while there wasn't an official way to do it, so you'd just create a dummy string, pin it and do it in unmanaged memory.

Thankfully these days, we do have an API with a purpose like this, see [string.Create()](
https://learn.microsoft.com/en-us/dotnet/api/system.string.create?view=net-7.0#system-string-create-1(system-int32-0-system-buffers-spanaction((system-char-0))))
