### ISSUE TITLE
 Detect Wine prefixes managed with the Flatpak version of Bottles. 

### ISSUE THREAD

**Issue by Estebiu** [Nexus-Mods/NexusMods.App#1893]
# Improvement

## Currently 
Nexus Mods currently scans the directories where Bottles' Wine prefixes are; but doesn't do so for the Flatpak version of Bottles (for devices such as the Steam Deck that have an immutable OS).

## We want
Nexus Mods App to scan '~/.var/app/com.usebottles.bottles/data/bottles/bottles'

## Supporting Information
PR #148  added support for the 'normal' version of Bottles.

## Design
Thanks for actively developing this program to be linux-compatible from the get-go.

**Comment by erri120** [comment]
The app uses [GameFinder](https://github.com/erri120/GameFinder), please open the issue at https://github.com/erri120/GameFinder.
