### ISSUE TITLE
Design for Library Item Deletion Warnings

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#1899]
# Improvement

## Currently 

We have the current modals warning users when deleting an item from the `Mod Library`.

Locally Added Mods:

![image](https://github.com/user-attachments/assets/cd1e4cfa-a7bf-425e-a06f-b68566f9e549)

Loadout Only:

![image](https://github.com/user-attachments/assets/1605ba5b-171d-46df-8e83-9839505ce02c)

Mod Added from Disk:

![image](https://github.com/user-attachments/assets/3b72900b-cdf8-4bb1-ad4c-8b901ba1e4d3)

Multiple (All) Warnings at Once:

![image](https://github.com/user-attachments/assets/9e103f71-b87a-4f58-96bd-d7fc4717ae9f)

The black canvas for reference is 1280x800, approximately the size we have on a Steam Deck.

## We want

Figma designs

https://www.figma.com/design/5LmVL8YpgDHFSFA76fgCZA/%F0%9F%93%B1-Mod-library?node-id=373-9939&t=it3QD0JxxKmlGuar-1

![image](https://github.com/user-attachments/assets/95edb386-260f-4159-b8e5-f4b23ad74e77)

**Comment by Al12rs** [comment]
@Sewer56 Is this completed?

**Comment by Sewer56** [comment]
This is completed.
