### ISSUE TITLE
Deleting a mod from the library doesn't remove it from the view

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#1921]
# Bug Report

## Summary
Removing a mod via the "Delete" option doesn't remove it from the old or new library view. 

For the old library, you must switch to a different page and back.

For the new library, it remains indefinitely. 

## Steps to reproduce
1. Log in
2. Install a mod from Nexus Mods
3. Delete it from the old library

## What is the expected behaviour?
The deleted mod is removed immediately (or close to) 

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by Pickysaurus** [comment]
https://github.com/user-attachments/assets/8f2dc3dd-2cb7-4795-acb8-05138fb5df06

**Comment by Al12rs** [comment]
Likely related to #1904
