### ISSUE TITLE
Prevent applying/switching loadouts while the Game or a Tool is running

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#1922]
Applying while game is running will cause `UnauthorizedAccessException` if it happens to try to touch files that are in use by the game or Tool. 
This is very likely to happen in particular when switching loadouts, since we are currently reverting to vanilla state and then applying the new loadout, which means we delete all the added files, some of which likely to be in use.

## Impact:
Currently this causes an exception in the log and Apply will fail, it isn't clear if the game folder is left in an inconsistent state. 
But I was able to resume normal operation after closing the game, and applying again. Everything appeared to be as expected in the game folder at that point.

**Comment by Al12rs** [comment]
If running a game or tool is wrapped in a Job, we can detect whether there are jobs running and disable the buttons based on that.
Should wait for jobs rework probably

**Comment by Sewer56** [comment]
@captainsandypants
