### ISSUE TITLE
Prevent Managing Games multiple times

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1928]
It is possible to manage the same game multiple times by closing and reopening My Games page, as the loading state is reset.

Unmanaging a game has the same issue. Also continuously displays game removing, doesn't refresh to show the game was removed without changing pages.

**Comment by erri120** [comment]
The state is in the UI only, so changing pages reset the UI state.

**Comment by halgari** [comment]
We should turn managing a game into a Job, and then hook that view up to the JobMonitor. I *think* that makes this task a half-day fix, and should be pretty straight forward.
