### ISSUE TITLE
Rework image blur code

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#194]
# Bug Report

The code I wrote in the [GameWidget](https://github.com/Nexus-Mods/NexusMods.App/blob/61c39a627deda2277e9b339104d19721707a879c/src/NexusMods.App.UI/Controls/GameWidget/GameWidget.axaml.cs#L33-L62) is an offense against nature, and should really be replaced.

## Summary
The issue is that we want to modify the image using Skia's routines, but the image in the start and end of the transformation should be an Avalonia bitmap. Avalonia uses Skia for drawing, but I couldn't find any sort of good translation at the time. We should figure out how to convert these bitmaps and remove the ugly code that saves and loads the images from PNGs.

## What is the expected behaviour?
That the transformation would be done without any sort of encoding/decoding/saving of the image data.

**Comment by Sewer56** [comment]
I'll pick this up next sprint. 👌
