### ISSUE TITLE
Play Button text stuck on "Running..."

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#1950]
![Image](https://github.com/user-attachments/assets/ddcba756-b4a3-41b0-835b-19df83d68889)

After quitting Cyberpunk sometimes the play button turns into this.

It becomes clickable at this point but the running text doesn't change to Play

**Comment by LukeNexusMods** [comment]
This also happening when applying loadouts

**Comment by Sewer56** [comment]
Duplicate of: https://github.com/Nexus-Mods/NexusMods.App/issues/759
