### ISSUE TITLE
Implement a flexible HTTP downloader

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#20]
Several parts of the application need a reliable HTTP downloader. In some cases users want to restrict the bandwidth of their downloads both at a per-connection and per-bytes-per-second level. So this should be backed by a `IResource<>`

Currently we have [`SimpleHttpDownloader`](https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/Networking/NexusMods.Networking.HttpDownloader/SimpleHttpDownloader.cs) that implements the [`IHttpDownloader`](https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/Networking/NexusMods.Networking.HttpDownloader/IHttpDownloader.cs) interface. We also have a test framework that can serve up arbitrary data via `HttpListener`. We can add another endpoint to that listener that randomly kills the connection or only sends partial data.

Requirements:
- Should support one or more HTTP urls, extra URLs are assumed to be mirrors
- Should try mirrors on 404s, and 500s
- Should retry the same mirror at least once, so we don't switch datacenters due to a single hiccup.
- Can download directly to disk, no need restrict yourself to a `Stream` interface
- `IHttpDownloader` includes a `size` parameter that can be used to verify download sizes for use in retries
- Should support resume, even after a complete app crash
  - Perhaps with two-phase write, write data, write a log of what was downloaded in a separate file? On restart, we can pick up at the location of the last log point.
- Should respect the `IResource<>` interface, and report all data usage and connections
- Should a given connection fail, try one of the mirrors. Restarting where the previous connection died.
- Should be backed by a DI `HttpClient`. .NET recommends a single HttpClient instance for the entire app.
- Implement tests
  - Using HTTPListener simulate retry, resume, etc.
  - We can pass parameters to the HttpListener endpoint to define how many bytes to go before causing a disconnect. 
  - We can drive those parameters with FsCheck (https://fscheck.github.io/FsCheck//QuickStart.html) for a truely robust solution

**Comment by TanninOne** [comment]
@halgari At this point I think this implementation is usable and further changes/improvements (e.g. bandwidth throttling) should probably be prioritized in separate tickets.
