### ISSUE TITLE
Figure out what to do about UI testing

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#200]
# Improvement
Find a way to do integration and unit testing of the UI portions of the app

## Currently 
We have a lot of UI code, most of it is completely untested

## We want
Some way to test the UI code, preferably even the Views, as even they tend to have a lot of binding logic in them.

**Comment by erri120** [comment]
[`Avalonia.Headless`](https://github.com/AvaloniaUI/Avalonia/tree/master/src/Avalonia.Headless) can be used to render components. Aside from that, the Avalonia repo mostly just uses Moq: https://github.com/AvaloniaUI/Avalonia/blob/master/tests/Avalonia.Base.UnitTests/Animation/AnimatableTests.cs

**Comment by halgari** [comment]
fixed in #262
