### ISSUE TITLE
Refresh remote metadata

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#2008]
Need to figure when and how we refresh. Whether that's on command, periodically, or both.

**Comment by erri120** [comment]
@Sewer56 @LukeNexusMods required for mod updates.

**Comment by Sewer56** [comment]
Originally I noted this as part of PR review, leading to this ticket being made.

It only dawned on me this morning; I actually 'solved' this as part of writing the update code too; and efficiently.
I simply need to add (literally) a few lines to also fetch and update the main mod page details with the files.

Will fully handle and close this when we talk to backend and then fully migrate mod updates to V2.
Maybe it may be possible to fetch files with main Mod page, as Tim alluded to yesterday; that is a question I too, have.
