### ISSUE TITLE
Deactivated fake parent library item models have an empty library items list

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2023]
When highlighting a large amount of mods to delete when clicking delete the modal that appears only contains the mods that are visible on the screen and not the others selected off of the screen. 

This results in you having to use the delete button multiple times to remove mods that do not display. 

To reproduce download a collection or have a mod list that requires you to scroll down.
Highlight all.
Press delete
The mods that appear in the modal will be the ones that appear on the screen currently. 
It will not delete mods not displayed on the screen.

**Comment by erri120** [comment]
Item models that get scrolled out-of-view are deactived. Deactivation will clear the list of library items, thus selected parents out-of-view will never be deleted.

**Comment by LukeNexusMods** [comment]
Its the same for the Install process too

**Comment by Al12rs** [comment]
I'm quite sure I specifically tested this and it was working, is this a regression from other changes?

**Comment by erri120** [comment]
> I'm quite sure I specifically tested this and it was working, is this a regression from other changes?

It's the same issue we've had with the selected children. This issue was always there. I'll rework the code to something that should be more reliable.

**Comment by LukeNexusMods** [comment]
This doesnt fix it for installing the mods. Only deleting them

**Comment by LukeNexusMods** [comment]
Looks like its still happening to an extent:

**Comment by Al12rs** [comment]
This particular bug was fixed, will open separate ticket
