### ISSUE TITLE
Apply button stays there after pressing it

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2026]
When applying the mods the apply button never changes to play.

https://github.com/user-attachments/assets/51506785-84aa-4002-9ca0-a64d6128a27d

**Comment by erri120** [comment]
Need logs

**Comment by LukeNexusMods** [comment]
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/16977287/nexusmods.app.main.current.log)

**Comment by nbiju-nexusmods** [comment]
[nexusmods.app.main.current.odt](https://github.com/user-attachments/files/16977615/nexusmods.app.main.current.odt)

**Comment by Sewer56** [comment]
You're in luck

https://github.com/Nexus-Mods/NexusMods.App/pull/2015

I fixed this yesterday

**Comment by halgari** [comment]
#2015 was reverted, we'll fix this as part of fixing the larger issues.
