### ISSUE TITLE
Library Badge numbers don't decrease on item deletions

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2028]
When deleting items from the library that are new the number in the orange circle does not reduce as you are deleting.

**Comment by Sewer56** [comment]
This is most likely a duplicate of an issue I raised yesterday:

https://github.com/Nexus-Mods/NexusMods.App/issues/2016#issue-2521093393

That number should be showing 'unseen' items, like a notification. If you're already on library page, that item should already be 'seen' by definition and the left menu should not show a number whatsoever
