### ISSUE TITLE
Installing many mods at the same time causes some installs to fail  

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2035]
When highlighting a large number of mods in the library and clicking add to install them, not all of them install correctly. 

I tested this by downloading:
https://next.nexusmods.com/cyberpunk2077/collections/iszwwe?tab=about

highlighting it all and then clicking add.

**Comment by halgari** [comment]
Might either be due to an error or race condition in the code somwhere. Probably an error. @LukeNexusMods do the mods that don't install, work when installed individually?

**Comment by LukeNexusMods** [comment]
I just tried a few of them and yes they do @halgari

**Comment by LukeNexusMods** [comment]
Is this related to the scrolling issue we found when deleting items out of the library?

**Comment by Al12rs** [comment]
I don't know, depends on the type of failures you were seeing. Are you still able to reproduce? 
Logs would have been good here to know what the problem used to be.

**Comment by LukeNexusMods** [comment]
I downloaded the latest Git build
downloaded Welcome to Night City
For some reason it started to auto-install which I don't know is intentional or not. 
It then only installs the mods in view but this might be due to it hitting a fomod because the installer pops up. 

[nexusmods.app.main.current.log](https://github.com/user-attachments/files/17187867/nexusmods.app.main.current.log)

**Comment by LukeNexusMods** [comment]
I believe this is fixed.
