### ISSUE TITLE
[Linux] 0.6 doesn't launch

### ISSUE THREAD

**Issue by CcMenta** [Nexus-Mods/NexusMods.App#2039]
When I try to launch 0.6 it doesn't launch, 0.5.3 starts up (The first version I tried was 0.6 and because it didn't worked I tried 0.5.3 later).

## Steps to reproduce
Launch either the appimage or zip version (after extracting it).

## What is the expected behaviour?
NexusMods app starts up

## Other information
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/17003756/nexusmods.app.main.current.log)
nexusmods.app.slim isn't generated because the program wasn't able to start up.
I use CahcyOS (arch based).

**Comment by MattSturgeon** [comment]
I believe you're running into breaking changes made to the database. 

Currently you're supposed to run `NexusMods.App uninstall-app` before upgrading. If you don't it'll just crash, with no user-friendly error message.

**Comment by MattSturgeon** [comment]
> When I try to launch 0.6 it doesn't launch, 0.5.3 starts up

This sounds like an old desktop entry sticking around.

The app (used to?) install a desktop entry at `~/.local/share/applications/com.nexusmods.app.desktop` for nxm url mimetype association. If that still exists, it may be pointing to the old version instead of the new one.

**Comment by CcMenta** [comment]
Thanks it fixed it, now I remember that I had this once installed but uninstalled it so I could try to make nexus send the nxm url to mod organizer, it didn't work.
