### ISSUE TITLE
Add tooltips to toolbar buttons

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#2044]
# Improvement

## Currently 
The toolbar buttons do not have tooltips

## We want
To add tooltips

### Top bar
- Back arrow -> Back
- Forward arrow -> Forward
- Account Icon (Logged In) -> Logged in to Nexus Mods as {USERNAME}
- Log In -> Connect your Nexus Mods account

### My Mods
- Switch View -> Show or hide mod page groups*
- View Mod Files -> Browse the files in the selected mod
- Remove -> Remove the selected mod(s) from this loadout

### Library
- Switch View -> Show or hide mod page groups*
- Delete -> Permanently remove this mod from your Library
- Add -> Add the selected mod(s) to this loadout
- Advanced Add -> Select specific files from a mod to add to your loadout
- From Drive -> Import a mod from your computer
- From Nexus Mods -> Open Nexus Mods

\* Temporary button, so not a priority. 

## Supporting Information
_(Include any supporting screenshots etc to support the above)_

## Design
_(Any designs to required for this feature)_

**Comment by Pickysaurus** [comment]
@captainsandypants for you to review.

**Comment by captainsandypants** [comment]
@Pickysaurus I think these are ok but I wouldn't schedule this work in anytime soon. We're likely to change buttons and labels as we go. We'd also want to add the keyboard shortcuts in for some of these, which haven't been implemented yet. We should keep this ticket open and updated though.

**Comment by LukeNexusMods** [comment]
Simon is working on this. close ticket when complete please.
