### ISSUE TITLE
Deleting multiple items from Library page sometimes does nothing

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#2047]
From Luke:

Ive posted a video in slack:
https://nexusmods.slack.com/archives/C04NE2CTMEU/p1726489801121449?thread_ts=1726489544.691279&cid=C04NE2CTMEU

Testing with this collection:
https://next.nexusmods.com/cyberpunk2077/collections/iszwwe

**Comment by LukeNexusMods** [comment]
[nexusmods.app.main.current.log](https://github.com/user-attachments/files/17013480/nexusmods.app.main.current.log)

**Comment by Al12rs** [comment]
duplicate of #1994
