### ISSUE TITLE
Perf: Merge `PathFor` and `HaveArchive` APIs in ArchiveManager.

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#206]
# Improvement

## Currently 

Currently `ArchiveManager` contains the `HaveArchive` and `PathFor` API; both of these archives use the exact same code, but return different results, i.e. File Exists (bool) or File Path (`AbsolutePath`). 

This risks the possibility of programmers writing code such as 

https://github.com/Nexus-Mods/NexusMods.App/blob/d2160b41d1453b15748e2239d3575b7a2d4c5073/tests/Games/NexusMods.Games.RedEngine.Tests/ModInstallerTests.cs#L61-L62

Which effectively run the exact same code twice over, converting a hash to a string, iterating a hashset and checking the existence of the file twice over [slow]. In addition, you can already use `PathFor` API for `HaveArchive` theoretically by just catching the exception for when path is not present.

When we run `_archiveManager.HaveArchive`, we already know the path of the file; so ideally, we could export this path via an `out` parameter.

## We want

An API like:  

```csharp
bool TryGetArchive(Hash hash, out AbsolutePath path);
```

Then consolidate the usages of these APIs.

## Supporting Information
See Currently [above]

**Comment by halgari** [comment]
Done as part of #334
