### ISSUE TITLE
Switching logged in users results in UI error

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2061]
I went to log out of my free user and log in with my premium one.
I clicked logout
Tried to log back in
Browser opened - already still logged in with my free user
I closed the browser

![Image](https://github.com/user-attachments/assets/7d03633b-832b-47a5-beac-a91a81fce739)

**Comment by erri120** [comment]
That's not a UI error. When you click login, we have a 5 minute timeout where we wait for you to login. During that timeout, the button is disabled. This works as intended.
