### ISSUE TITLE
Health check item shadow improvement

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#2068]
## Currently
Health check items use the SM shadow on rest and MD on hover.

## We want
Health check items to use the new XS shadow on rest and SM on hover.

## Design
[Figma link](https://www.figma.com/design/hsUiqro210T3tsK1F9l1fQ/%F0%9F%93%B1%F0%9F%A9%BAHealth-Check?node-id=1-2954&t=NxOUlESCXnOi7HVz-1)

![Image](https://github.com/user-attachments/assets/68b56a74-8ff7-4d01-a458-4ec15841ccb3)

**Comment by insomnious** [comment]
This is done, waiting on https://github.com/Nexus-Mods/NexusMods.App/pull/2065 as this PR contains the new `BoxShadowXS`
