### ISSUE TITLE
Cannot download from hidden mod pages

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#2084]
# Bug Report

## Summary
It is not currently possible to download hidden mods with the app. An error is generated when the app gets the HTTP 401 error from trying to pull the mod metadata. 

## Steps to reproduce
1. Find a hidden mod page - the same may be true of a deleted mod page.
2. Download a file
3. See the app does not react. 

## What is the expected behaviour?
The app is able to install files from hidden and deleted mod pages. 

## Other information
**Example 1 - Cyberpunk 2077**
https://www.nexusmods.com/cyberpunk2077/mods/10426
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=87139&game_id=3333

**Example 2 - Generic test files**
https://www.nexusmods.com/site/mods/415
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=1559&game_id=2295
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=1560&game_id=2295

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by LukeNexusMods** [comment]
@halgari

**Comment by erri120** [comment]
Please attach logs.

**Comment by Pickysaurus** [comment]
> Please attach logs.

Follow the replicate instructions, it happens 100% of the time. I don't have the logs anymore.
