### ISSUE TITLE
Images not showing in FOMOD installer

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#2085]
## Bug

Images aren't showing in the FOMOD installer. 

Run a FOMOD that has options with images, see that images aren't displayed. The installer does seem to detect that there is an image though, as it adds the "contains image" icon:

![Image](https://github.com/user-attachments/assets/f916929a-3881-4016-b409-ecb06c253cc0)

**Comment by erri120** [comment]
What FOMOD is this?

**Comment by erri120** [comment]
Superseded by #2086.
