### ISSUE TITLE
CI Release Github Action is tagging wrong branch

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#2087]
# Bug Report

## Summary
Release CI workflow is tagging main even when releasing from a different branch/commit.
The build happens on the desired branch correctly, but a tag is then pushed on main and the release linked to that tag.

## Details
It seems `softprops/action-gh-release@v1` should be updated to v2 and that we should provide it with `target_commitish` if we wish to push a tag on a different branch.

Fix would be to:
- set `target_commitish` to the branch the workflow is being run on if it is not set
- add optional `target_commitish` input to workflow to allow tagging a specific commit
    - Update the rest of the workflow to use the passed target commit if set, to create the build based on that instead of latest commit.

**Comment by Sewer56** [comment]
This happened this morning while publishing 0.6.1 for the record. We found out the hard way. Surprising this wasn't noticed before.
