### ISSUE TITLE
BUG - Uninstaller Does NOT remove Local AppData Folder

### ISSUE THREAD

**Issue by ChemGuy1611** [Nexus-Mods/NexusMods.App#2089]
# Bug Report

EDIT: Maybe this was only an issue with older versions? I installed and uninstalled v0.6.1 a couple times, and it seems to be deleting the %LOCALAPPDATA%/NexusMods.App folder now. Perhaps older version uninstallers did not do this?

## Summary
The uninstaller does NOT remove the %LOCALAPPDATA%/NexusMods.App folder. It only removes the %LOCALAPPDATA%/**Programs**/NexusMods.App folder. Leaving that other folder behind makes the App crash immediately on launch, even after uninstalling previous version and installing new version. 

I actually reported this bug previously. The Uninstall guides do NOT mention the need to delete this second folder anywhere. 

https://github.com/Nexus-Mods/NexusMods.App/issues/1865

## Steps to reproduce
1. Start with previous version of app installed. Run once.
2. Uninstall previous version
3. Install latest version and try to run.
4. App crashes immediately on startup.

## What is the expected behaviour?
Uninstaller should remove contents of BOTH folders. Otherwise, it is impossible to launch the program after an update. Even after uninstalling previous version.

**Comment by Pickysaurus** [comment]
Can confirm this isn't working properly on both Windows and Linux (based on other reports)

**Comment by Sewer56** [comment]
This should be done with #2121.
Both removing folder entirely and making it work when there were spaces.
