### ISSUE TITLE
Switch to GQL for all Nexus Mods queries (or the ones we can)

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#2091]
# Improvement

## Currently 
Collections use the V2 API (GQL) and the rest of the mod library uses the V1 API. We should unify this behavior. This will allow us to reduce the calls we make by batching requests. But it will require reworking 2 core methods in NexusModsLibrary.cs

**Comment by Sewer56** [comment]
Originally noted in this PR feedback: 
- https://github.com/Nexus-Mods/NexusMods.App/pull/2081#discussion_r1775624794

It's not directly correlated, but this issue was created as a response to that comment.
