### ISSUE TITLE
Game not found

### ISSUE THREAD

**Issue by elogicuk** [Nexus-Mods/NexusMods.App#2097]
I use lutris on linux to manage all my games

and the nexusmods app does not find any games installed.

Please allow us to select a path for a game.

![ksnip_20240926-162533](https://github.com/user-attachments/assets/5a909285-2ec3-4854-86f8-de553fe216a0)

**Comment by Sewer56** [comment]
This is technically a duplicate of:

- https://github.com/Nexus-Mods/NexusMods.App/issues/1699

**Comment by erri120** [comment]
Closing in favor of #1699 and #1838.
