### ISSUE TITLE
Load Order UI v1: flat button list, no styling

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2099]
Phase two of load order will utilise the backend work completed in phase 1 to display a flat list of items that need to be ordered. 

No interaction with this list will be introduced at this stage. It will be a flat list. 

https://www.figma.com/design/1sbIAJGr8URkY3wmisyaJg/%F0%9F%93%B1-Load-order?node-id=264-14154&node-type=section&t=IoDRh4h53c2O0jTt-0

In addition to displaying the items that need to be ordered the backend needs to understand how to load them in an order, ready for the next phase. 

Definition of done
A list can be seen of mods that need to be loaded in order. 
Knowledge of which mods need ordering will help here. 
Installing mods that need ordering and then seeing if they appear in the new list will signify that UI piece of work is complete.

**Comment by LukeNexusMods** [comment]
@captainsandypants when you are able to please can you attach the flatlist design to this please?

**Comment by Al12rs** [comment]
- Requires #2098
