### ISSUE TITLE
Rewrite HashRelativePath Struct to Use Single RelativePath

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#210]
# Improvement

## Currently

In our C# codebase, we have a struct called `HashRelativePath`, which stores the hash of a given file and an array of `RelativePath` structs. These `RelativePath `structs are meant to be combined (joined) to store the complete relative path tied to the struct. 

i.e. The `HashRelativePath` struct is currently defined as:

```csharp
// Simplified for clarity
public struct HashRelativePath
{
    public Hash Hash;
    public RelativePath[] Parts;
}
```

However, after examining the codebase, as far as I can tell, all current uses of `HashRelativePath` only require one `RelativePath` struct, and the structs are never joined or combined; therefore making the array redundant. In addition, the relative paths can simply be joined up front, rather than being stored as an array, improving overall efficiency.

## We Want

We want to simplify the `HashRelativePath` struct by using only a single `RelativePath` struct instead of an array. This would make the struct more efficient and easier to work with. The updated `HashRelativePath` struct should look more like:

```csharp
public struct HashRelativePath
{
    public Hash Hash;
    public RelativePath Path;
}
```

# Other Info 

This code is based on the old Paths library/system. When rewriting the `Paths` library, it seems I missed this code because this code resides in the `NexusMods.Hashing.xxHash64` library when I was working on `NexusMods.Paths`.

**Comment by halgari** [comment]
Originally the idea here was that if there were archives in archives we would want to have something like `[0xDEADBEEF | /foo/bar.zip | baz.bsa | file.dds]`

However we could store this as a series of hash prefixed paths:

```
 [0xDEADBEEF | /foo/bar]
 [0xF000BADD | baz.bsa]
 [0xFF00dad | file.dds]
 ```
