### ISSUE TITLE
[Potential Bug] LoadoutManager.ExportToAsync: Ensure Cross-Platform Compatibility [Directory Separators]

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#212]
# Improvement

This issue reports a potential (unconfirmed) bug.

## Currently
In `LoadoutManager`, we have a function called `ExportToAsync` that creates a zip file containing the contents of a given loadout for testing and backup/restore purposes. The current implementation includes the following code: `zip.CreateEntry("entities\\" + entityId.TaggedSpanHex)`.

The generated `.zip` archives by this code might not open correctly in Linux-based archivers, as the `.zip` archive format expects the character `/` to be used as the directory separator instead of `\`. 

To quote the ZIP standard:  
> 4.4.17.1 The name of the file, with optional relative path. The path stored MUST not contain a drive or device letter, or a leading slash. All slashes MUST be forward slashes '/' as opposed to backwards slashes '\' for compatibility with Amiga and UNIX file systems etc. If input came from standard input, there is no file name field.

For file paths inside generated .zip archives we should be using the `/` separator to ensure standards compliance.  
Most Windows software can handle either separator, but some Linux software notably only handles the `/` separator.  

----

Note: There's a possibility the BCL itself might standardise the separator during the save operation; but I have not tested this. It is better to ensure we're adding paths correctly rather than relying on a black box lower level component to potentially correct us. [I use the term 'black box' here as implementation of BCL can obviously change between runtime versions].

## We want
We want the `ExportToAsync` function to be cross-platform compatible and work correctly with both Windows and Linux-based archivers. To achieve this, we need to use the appropriate directory separator character for `.zip` archives.

## Design
To resolve this issue, update the `ExportToAsync` function to use the '/' character as the directory separator when creating .zip archive entries. i.e. do not use:

```csharp
zip.CreateEntry("entities\\" + entityId.TaggedSpanHex)
```

instead use: 
```csharp
zip.CreateEntry("entities/" + entityId.TaggedSpanHex)
```

## Other Information

As aforementioned; this is not confirmed as a 'bug', but we should ensure correctness here; and in other cases where we might create zip(s) in the future.

**Comment by halgari** [comment]
The standard says that, but nothing actually enforces it, so whatever we do, our extraction routines will need to support both formats

**Comment by Sewer56** [comment]
Our code (.NET BCL), can handle either I'm pretty sure; so it's not a big deal. I opened this issue with external archiving tools in mind; e.g. in case anyone wants to open an exported loadout. Not sure why someone would in any case; but ensuring correctness would be a 👍

**Comment by erri120** [comment]
Is it set in stone that we're going to use `.zip` for our export, or was that just the easiest to implement/work with?

**Comment by Sewer56** [comment]
I don't think it is; but I don't think we'd really get any benefits space-wise from another format as [IIRC] we're packing the entire archive files that contain the mods.

**Comment by Sewer56** [comment]
> I don't think it is; but I don't think we'd really get any benefits space-wise from another format as [IIRC] we're packing the entire archive files that contain the mods.

Potential improvement here would be to not re-compress archives.
