### ISSUE TITLE
HeroicGOGHandler crashes app

### ISSUE THREAD

**Issue by MistaOmega** [Nexus-Mods/NexusMods.App#2129]
Erroneous issue, I believe it (may) be a gamefinder bug

**Comment by erri120** [comment]
You can open an issue on the GameFinder repo: https://github.com/erri120/GameFinder

I'll reopen this issue since the app crashing is still a bug on our side.

**Comment by MistaOmega** [comment]
https://github.com/erri120/GameFinder/issues/154
