### ISSUE TITLE
Collections - Window stealing focus

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#2131]
# Bug Report

## Summary
During a collection download as a Premium user, the app constantly steals Window focus and pops to the front, making it impossible to do anything else on your PC. 

## Steps to reproduce
1. Install a collection as a premium user
2. During the download, try and use any other apps on your PC
3. See that the app keeps stealing focus

## What is the expected behaviour?
The app does not steal focus during install (it may make sense to do so once all download are complete or if user intervention is required) 

## Other information
Reported by @insomnious via internal Slack chats

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by LukeNexusMods** [comment]
I am not seeing this on the latest git build.

**Comment by LukeNexusMods** [comment]
Fixed
