### ISSUE TITLE
Sewer's Self-Contained Performance Optimisation Issue [2-3 Days]

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#214]
# Improvement

This issue lists a number of minor, smaller scale optimisations to be done which on their own are probably too small to make issues for. 

This supersedes https://github.com/Nexus-Mods/NexusMods.App/issues/99 , which will be closed. #99 will be implemented by a combination of the elements listed below.

# High Impact 🔥

<details>

  <summary>Cancelled in Favour of Switching to Another Library</summary>

## Reading Items from SQLite has Unnecessary Overhead

Affects all `Get` operations.

When reading blobs [including IDs], we use the method `GetStream(0)`; this method is defined as:  

```csharp
public virtual Stream GetStream(int ordinal)
{
    using (MemoryStream bufferStream = new MemoryStream())
    {
        long bytesRead = 0;
        long bytesReadTotal = 0;
        byte[] buffer = new byte[4096];
        do
        {
            bytesRead = GetBytes(ordinal, bytesReadTotal, buffer, 0, buffer.Length);
            bufferStream.Write(buffer, 0, (int)bytesRead);
            bytesReadTotal += bytesRead;
        }
        while (bytesRead > 0);

        return new MemoryStream(bufferStream.ToArray(), false);
    }
}
```

In other words, to read a 150 byte item we:
- Allocate a 4096 byte buffer [in method].  
  - And zero-fill it.  
- We allocate a 255 byte buffer in `MemoryStream` (on Write) [I checked source to determine this behaviour]  
  - And zero fill it.
- We extract the 150 bytes `ToArray()` from the 255 byte buffer [i.e. `return new MemoryStream(bufferStream.ToArray(), false)`].  
  - [at least `ToArray` *doesn't* unnecessary zero fill]

All to get 150 bytes out from the database. 

Most of our serialized JSON blobs are under 150 bytes; and almost all (99%) are under 350; so this is incredibly wasteful.

</details>

# Low-Medium Impact ⚡

## Don't Zero out Arrays Whose Contents we Discard

This one notably applies to all IDs; which are naturally a hot path since every `DataModel` item has one.

### On the Stack

We have many uses of `stackalloc` throughout the codebase; around 60 in total.  
In most of these cases, we do something like the following:  

```csharp
Span<byte> span = stackalloc byte[SpanSize];
ToSpan(span);
```

By default, arrays allocated to the stack are actually zero'd out unless you apply the `SkipLocalsInit` attribute to the method. So we allocate, zero it out and replace the data.

Note: It's possible to apply this attribute to the whole assembly; but I'd prefer to avoid that because it's something contributors might not be aware of is the default.

### On the Heap

Similar situation with heap allocated items.

```csharp
var idBytes = new byte[id.SpanSize];
id.ToSpan(idBytes.AsSpan());
```

We should be using the API `GC.AllocateUninitializedArray<byte>()` to do these allocations without zero-initializing.

## Remove Bounds Checks in Serialization

Using `FileCacheEntry` as example.

![rider64_3IfIw0pdTG](https://user-images.githubusercontent.com/6697380/226064047-2e2a4900-f2a6-404c-ba99-81698f4c0c64.png)

These serialize/deserialize methods produce bounds checks on every slice and are called for every file during indexing operations. Minimal trivial to implement improvement here; do preliminary bounds check [+throwhelper if span too short], then `SliceFast` the rest.

# Low Impact 💧

## Optimize StringExtensions `FromHex`

Reason: We use these functions to store and fetch archives from filesystem; including our file backups and more; so we're talking probably a range of `1000-10000` for an average setup of a highly modded ~~Skyrim~~ game.

Currently we use the following in `FromHex` as part of the process of reading back a hash:

```csharp
for (var i = 0; i < bytes.Length; i++)
{
    var hexOffset = i * 2;
    bytes[i] = byte.Parse(hex[hexOffset..(hexOffset + 2)], NumberStyles.HexNumber);
}
```

This is pretty slow because in `byte.Parse`, the runtime libraries have to do several checks; including:
- Leading & Trailing Whitespace  
- Hex specifiers [`e.g. `0x`, `h`, `$`]  

And in our case; since we generated the original name; we know the exact constraints [i.e no specifier/spaces].  
Therefore there is good opportunity to optimise here.  

`ToHex` could also be optimised by removing bounds checks.

## Add ThrowHelper to `Percent` Constructor

To not prevent inline of trivial constructor.

## Double Enumeration in `Resource.StatusReport`

Currently not used in app; but would be used once download view is added to UI. We enumerate twice over a concurrent dictionary, that's pretty slow.

## GetEveryXItem in `CollectionExtensions` can be 'Spanified'

Would give negligible speedup in folder indexing of folders with huge amount of files. Negligible gain but very easy to do.

**Comment by halgari** [comment]
Don't do any of the work on the SQlite code, I'll probably swap out our SQLite provider this week in favor of a more low-level library that has binaries for almost every OS under the sun (including OSX, iOS and Android)

**Comment by Sewer56** [comment]
Updated the opening post 👌

**Comment by Sewer56** [comment]
Closing this as 'no longer valid'.
A lot of these opts have already made it into mainline code, as part of other PRs, or the code no longer exists.
