### ISSUE TITLE
Redmod health check item not going away after installation of redmod

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2168]
This is something that Nisha experienced. 
Health check item was advising to install redmod. Nisha installed redmod and the health check item remained. 

Tried closing and reopening the app but the health check item remained.

**Comment by halgari** [comment]
Do the files show up in the "preview changes" window?

**Comment by LukeNexusMods** [comment]
> Do the files show up in the "preview changes" window?

The preview changes window is not appearing as an option to select.

**Comment by LukeNexusMods** [comment]
Nisha has followed advice from Seweryn and it had fixed the problem.
