### ISSUE TITLE
Installing in wrong directory for BG3, Linux.

### ISSUE THREAD

**Issue by Eddieddg1** [Nexus-Mods/NexusMods.App#2202]
# Bug Report

## Summary
_(Summarize the bug encountered concisely ensuring you state the current behaviour)_
When installing a mod for bg3, it installs the mod to ".../drive_c/Users/steamuser/..." and not ".../drive_c/users/steamuser/..."
.../ is meant to show there are other directories before and /... is meant to show after. Anyway, this may seem trivial at first, however Linux is a case sensitive operating system so they are treated as entirely different directories.

## Steps to reproduce
_(How one can reproduce the issue - this is very important)_
Install/activate a mod for bg3 (don't know if this happens for other games) and watch it create "Users" folder (and sub-directories) in ".../1086940/pfx/drive_c/".

## What is the expected behaviour?
_(What did you expect to happen instead?)_
Installing the mods to "users" instead of "Users".

## Other information
_(Logs, screenshots, possible fixes, expected behaviour, etc.)_
Just change the part in the code that says ".../pfx/drive_c/Users/..." to ".../pfx/drive_c/users/..."

![20241025_11h10m43s_grim](https://github.com/user-attachments/assets/b1588976-626a-4854-bfab-ff4cf726ea12)

My temporary fix is:
export bg3="$HOME/.local/share/Steam/steamapps/compatdata/1086940/pfx/drive_c/"
rm -rf $bg3/Users
ln -s $bg3/Users $bg3/users

I don't think I need to show logs?.

**Comment by erri120** [comment]
https://github.com/erri120/GameFinder/blob/master/src/GameFinder.Wine/AWinePrefix.cs#L70-L72

**Comment by Eddieddg1** [comment]
I have made a pull request regarding this in @erri120's game finder that he linked

**Comment by Pickysaurus** [comment]
Is it definitely always lowercase or is that a quirk of your personal setup? I only ask because we've had a fair few Linux testers and this hasn't come up before.

**Comment by Eddieddg1** [comment]
I believe it is always, yes. It was like this before I reinstalled arch last week, it is like that on my bazzite pc and obviously on my current install of arch. But, if you are really skepticall you could just look for both "User" and "user" and use the one that is found.

**Comment by Al12rs** [comment]
- fixed with #2220
