### ISSUE TITLE
RedMod Journey

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2224]
The journey for installing Red Mod is causing some confusion. You end up being passed around from the launcher, to a website, to steam and then back to the launcher. 

If you click on the links in the health check item and you have your launcher options in Steam set to launch the game without the launcher, it launches the game instead of sending you to somewhere you can get red mod.

**Comment by LukeNexusMods** [comment]
We can change the link in the health check item so it opens the steam redmod page.

**Comment by Sewer56** [comment]
to `https://store.steampowered.com/app/2060310`
from `steam://run/2060310`

Simple 1 liner.
