### ISSUE TITLE
Baldur's Gate 3 - Game version is not reported correctly

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#2229]
# Bug Report

## Summary
In 0.6.3, the game version for Baldur's Gate 3 reports 1.0.0 - previously it was reporting the correct version. 

### 0.6.2 (Correct)
![image](https://github.com/user-attachments/assets/152d522a-aec1-4ba0-b2cf-e2b03696489d)

### 0.6.3 (Incorrect)
![image](https://github.com/user-attachments/assets/1b7bd55f-891b-4d7d-a9e6-b899577d10c7)

## Steps to reproduce
1. Manage BG3 with 0.6.2 and 0.6.3 on Windows, compare results. 

## What is the expected behaviour?
The version number is reported correctly.

**Comment by Al12rs** [comment]
- fixed in #2249
