### ISSUE TITLE
Export to OpenMW?

### ISSUE THREAD

**Issue by circuitsystem** [Nexus-Mods/NexusMods.App#2235]
# User story

**As a** User

**I want to** Export mods to OpenMW

**So that** It's easier to mod OpenMW

## Design
A good half of morrowind players use OpenMW exclusively now. Many of us use [this python plugin for mod organizer 2](https://www.nexusmods.com/morrowind/mods/45642?tab=description) to export mods to openmw, making modding far easier to deal with on morrowind

This is a request for this feature to be in the Nexus Mods app, and would (hopefully) also be able to export to the flatpak version of OpenMW as well

**Comment by erri120** [comment]
We don't support Morrowind currently or in the near future. I'm closing this as unrelated. We can re-open the issue when we add or think about adding support for Morrowind.
