### ISSUE TITLE
Sub-tab component: Required for Collections and Health check

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#2269]
## Currently

We do not have a sub tab component for switching data types in a view.

## We need

A sub-tab component that allows for this which will be used to switch between load order file types and diagnostic severities. It will likely also be used elsewhere in the future.

## Design

[Figma link](https://www.figma.com/design/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%93%B1%F0%9F%A7%B1-App-components?m=auto&node-id=2775-14036&t=C7jc3eUsxO9zVM4O-1)

![Image](https://github.com/user-attachments/assets/6b235808-f956-4117-a237-c62516fbb6cd)

**Comment by insomnious** [comment]
Completed in https://github.com/Nexus-Mods/NexusMods.App/pull/2302
