### ISSUE TITLE
Download buttons dont change on certain mods

### ISSUE THREAD

**Issue by LukeNexusMods** [Nexus-Mods/NexusMods.App#2308]
When clicking download all or clicking individually there are certain mods that download after you click the download button but then the button does not change to downloaded. 

If you keep clicking the button it will keep downloading the mod over and over. 

This only happens with certain mods. 

Examples are:
-Stardew Valley Expanded- Mod in the collection Stardew Valley VERY expanded

https://next.nexusmods.com/stardewvalley/collections/tckf0m/revisions/77

![Image](https://github.com/user-attachments/assets/47ff6b47-baf1-420a-a746-d6b015373bc4)

**Comment by erri120** [comment]
Fixed in #2304.
