### ISSUE TITLE
Panel UI fixes

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#2373]
## Currently

1. The border radius of the panel content does not match the panel container, meaning content corners overlap the higher border radius of the container.

2. The edge of panel tab container is missing the gradient fade effect from designs for when the open tabs fill the tab bar.

#### 1. Fix border radius for panel content not matching the actual panel edge. Either set both as the same or make container clip content.

![Image](https://github.com/user-attachments/assets/d3195ef6-33f5-44b3-a8b7-bb2f16bec309)

[Figma link](https://www.figma.com/design/VNqTTMrBsVaU2UZ9UlNsJj/%F0%9F%93%B1-Panel-management?node-id=937-9342&t=Da09ArTo8cKEH7eH-1)

#### 2. Add the gradient to edge of tab container as described in designs.

![Image](https://github.com/user-attachments/assets/ce4013e9-7999-46c7-880b-bd1c91965f2a)

[Figma link](https://www.figma.com/design/VNqTTMrBsVaU2UZ9UlNsJj/%F0%9F%93%B1-Panel-management?node-id=215-56279&t=Da09ArTo8cKEH7eH-1)

**Comment by insomnious** [comment]
Currently:
![Image](https://github.com/user-attachments/assets/8fe25ba1-ed96-4b38-9f3a-48507c61a5aa)
