### ISSUE TITLE
Can't complete collection install when bundled mods are included

### ISSUE THREAD

**Issue by Pickysaurus** [Nexus-Mods/NexusMods.App#2383]
# Bug Report

## Summary
When a collection contains bundled mods, they will never be "downloaded" so the user cannot complete the download stage of a collection. 

Relates to https://github.com/Nexus-Mods/NexusMods.App/issues/2380

## Steps to reproduce
1. Install this collection https://next.nexusmods.com/stardewvalley/collections/gkoqjx/revisions/1?tab=mods
2. See that it says 2 required mods are needed.
3. Only one mod is from Nexus Mods, the other is bundled.

## What is the expected behaviour?
The count of mods to download does not include bundled files OR the count does include bundled files but they are already marked as downloaded

## Other information
![Image](https://github.com/user-attachments/assets/2860c4d4-8268-44a8-ad86-743c70d81fa5)

Log files can be found in these locations:

- Windows: `%LOCALAPPDATA%\NexusMods.App\Logs`
- Linux: `~/.local/state/NexusMods.App/Logs`

Please attach both `nexusmods.app.main` and `nexusmods.app.slim` log files with the most recent dates.

**Comment by erri120** [comment]
Fixed in #2381.
