### ISSUE TITLE
Create the layout for the 'Downloads - In Progress' page

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#254]
# Story

## User Story

As a user, when I start downloading a mod I want to see the download progress within the app

## Outline
Create the layout for the 'Downloads - In Progress' page.

This issue should cover:

- the general layout, i.e. the 'Downloads' menu on the left; AND
- the 'In Progress' bar at the top of the main content; AND
- the mods table within the main content.

We'll also need to consider an 'empty' state.

This should not cover (these will be done iteratively in future tasks):

- Adding 'Pause' UI
- Adding 'Cancel' UI
- Adding the 'Total' progress bar above the mods table
- Adding the 'Speed' section in the main content
- Building the 'Completed' page
- Building the 'Download history' page

## Supporting Information
Figma designs: https://www.figma.com/file/Ntr9PttR5VrqpTRwwZHzLu/Mod-list?node-id=252-24430&t=DXyQTx6LsPZC5Kpy-0

**Comment by erri120** [comment]
This was done in #293, right?
