### ISSUE TITLE
Add Helper for Downloading Mods to use in Unit Tests

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#274]
# Improvement

Note: This documents an improvement made during the making of a PR that adds SkyrimSE support.

## Currently
The unit tests in our C# project involve downloading mods from Nexus Mods as part of the test procedure. However, there is a significant amount of duplicated code between individual test projects due to this approach.

## We want

We would like to refactor the test suite to reduce code duplication and improve maintainability. This can be achieved by creating a shared utility or helper class that centralizes the mod downloading functionality. This would enable individual test projects to leverage the shared code, thereby reducing redundancy.

## Design

To solve this; the following design was introduced into the recently added Test Framework.

```csharp
// class TestModDownloader

/// <summary>
/// Downloads this mod asynchronously to a temporary path.
/// </summary>
/// <param name="modFolder">Folder containing the manifest.</param>
/// <param name="targetFs">FileSystem to write to.</param>
/// <param name="token">Allows you to cancel the operation.</param>
/// <returns>Downloaded item inside the provided FileSystem.</returns>
Task<DownloadedItem> DownloadFromManifestAsync(AbsolutePath modFolder, IFileSystem targetFs, CancellationToken token = default);

/// <summary>
/// Downloads this mod asynchronously to a temporary path.
/// </summary>
/// <param name="meta">The metadata for which to download the mod for.</param>
/// <param name="targetFs">FileSystem to write to.</param>
/// <param name="token">Allows you to cancel the operation.</param>
/// <returns>Downloaded item inside the provided FileSystem.</returns>
Task<DownloadedItem> DownloadAsync(RemoteModMetadataBase meta, IFileSystem targetFs, CancellationToken token = default);

/// <summary>
/// Downloads this mod asynchronously to a given path.
/// </summary>
/// <param name="meta">The metadata for which to download the mod for.</param>
/// <param name="targetFs">FileSystem to write to.</param>
/// <param name="folderPath">Folder to download files to.</param>
/// <param name="token">Allows you to cancel the operation.</param>
Task DownloadAsync(RemoteModMetadataBase meta, IFileSystem targetFs, AbsolutePath folderPath, CancellationToken token = default);
```

Current implementations of `RemoteModMetadataBase` include

```csharp
/// <summary>
/// Base class for remotely downloaded mods.
/// </summary>
public class RemoteModMetadataBase
{
    /// <summary>
    /// Where this mod is sourced from.
    /// Defines the concrete type used.
    /// </summary>
    public RemoteModSource Source { get; set; }

    /// <summary>
    /// User friendly name for this mod.
    /// </summary>
    public string Name { get; set; } = "";
}

/// <summary>
/// Metadata for a remote mod.
/// </summary>
public class NexusModMetadata : RemoteModMetadataBase
{
    /// <summary>
    /// Mod ID corresponding to the Nexus API.
    /// </summary>
    public ModId ModId { get; set; }

    /// <summary>
    /// File ID corresponding to the Nexus API.
    /// </summary>
    public FileId FileId { get; set; }

    /// <summary>
    /// Expected hash of the file (sanity check!).
    /// </summary>
    public Hash Hash { get; set; }
}

/// <summary>
/// Metadata used for downloading mods from the FileSystem.
/// </summary>
public class FileSystemModMetadata : RemoteModMetadataBase
{
    /// <summary>
    /// Path to the archive file relative to the folder the JSON is contained in.
    /// </summary>
    public string FilePath { get; set; } = "";

    /// <summary>
    /// This field is set at deserialization time.
    /// It is the physical location of the JSON.
    /// </summary>
    [JsonIgnore]
    public AbsolutePath JsonPath { get; set; }
}
```

In this case, `NexusModMetadata` downloads a mod from Nexus while `FileSystemModMetadata` can be used to download mods already on disk.

The latter is useful because in some cases where you don't care about the contents of the mod (only file names); mods can be stubbed to avoid downloading, improving test time.

**Comment by halgari** [comment]
Don't we already have something like this in AGameTest?

**Comment by Sewer56** [comment]
Yes and no. We have a method for downloading mods in `AGameTest`. 

This one actually creates a system where you can load test data from manifest files specified from Disk. And these manifests can point to a Nexus URL, An Existing File on Disk, arbitrary URL, etc.

It all uses a unified interface so you just feed it a folder and off it grabs the files. I added this when I was working on SkyrimSE because I wound up stubbing some of the mods used for unit tests (with dummies using same file structure) and felt there was an opportunity for saving lines of code down the road by using the same interface to pull mods from different locations.
