### ISSUE TITLE
Bug: Some path tests are skipped on Windows 

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#277]
# Bug Report

Note: This documents a bug fixed made during the making of a PR that adds SkyrimSE support. It's here for tracking only.

## Summary
In our C# project, several test methods are annotated with `Skip.IfNot(linux && OperatingSystem.IsLinux());` which intends to skip Linux tests on non-Linux platforms. However, the current way this is written actually causes these tests to be skipped entirely on non-Linux regardless if they are Linux flagged or not.

## Steps to reproduce
1. Open the C# project.
2. Run the code on a Windows machine.
3. Observe that the methods with `Skip.IfNot(linux && OperatingSystem.IsLinux());` do not run on Windows for the non-Linux test cases.

## What is the expected behaviour?
The expected behaviour is that the annotated methods should run non-linux machines for the non-linux cases. This can be fixed by updating the code to `Skip.If(linux && !OperatingSystem.IsLinux());`.

**Comment by erri120** [comment]
I'm gonna use a truth table for this:

| `linux` | `OpeartingSystem.IsLinux()` | test should be skipped |
|----------|------------------------------------------|--------|
| `false` | `false` | `false` |
| `false` | `true` | `true` |
| `true` | `false` | `true` |
| `true` | `true` | `false` |

This is the table for XOR, so we can use `linux != OperatingSystem.IsLinux()` to determine if the test should be skipped on the current platform:

```csharp
Skip.If(linux != OperatingSystem.IsLinux())
```

**Comment by Sewer56** [comment]
Sure works for me 👍
