### ISSUE TITLE
As a modder, I want to use a FOMOD installer to make mod choices

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#316]
# User story

**As a** modder

**I want to** use a FOMOD installer

**So that** I can make customisation choices when installing a mod

## Requirements
We need to support FOMOD installers and present users with a generic UI/UX.

## Design

[Prototype ](https://www.figma.com/proto/Ntr9PttR5VrqpTRwwZHzLu/%F0%9F%93%B1-Mod-list?page-id=1479%3A27452&type=design&node-id=1548-4037&viewport=-520%2C-329%2C0.74&t=R5gbLaVaAKIzHHfh-1&scaling=min-zoom&starting-point-node-id=1548%3A4037&mode=design)

[Figma](https://www.figma.com/file/Ntr9PttR5VrqpTRwwZHzLu/%F0%9F%93%B1-Mod-list?type=design&node-id=1548%3A4036&mode=design&t=6wszPNE5HLzhudKQ-1)

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** am downloading a FOMOD for Skyrim

**When** I install the FOMOD

**Then** I am prompted to run the FOMOD installer

## Scenario 2
**Given** I am using the FOMOD installer

**When** I complete an installation step

**Then** I am taken to the next FOMOD installation step

## Scenario 3
**Given** I am using the FOMOD installer

**When** I go back

**Then** I am taken to the previous FOMOD installation step

## Scenario 4
**Given** I am using the FOMOD installer

**When** I complete the installation

**Then** I am shown an installation complete message

## Extra

Example FOMODs:

- https://www.nexusmods.com/skyrimspecialedition/mods/659
- https://www.nexusmods.com/skyrimspecialedition/mods/19518
- https://www.nexusmods.com/skyrimspecialedition/mods/2017
- https://www.nexusmods.com/skyrim/mods/17802

**Comment by halgari** [comment]
Mod Organizer 2:

Static Mesh Improvement Mod:
![mo2_1](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/c8c76478-5686-441d-b7b6-4df0529d2763)

Falmer Armors and Weapons Retexture:
![mo2_2](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/735c07a2-2d12-48d4-8287-2a1684cf5a6f)
![mo2_3](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/e8631a74-54c7-43b4-ac1f-cf7eb0d6ffb4)

**Comment by Sewer56** [comment]
Reloaded-II's Mod Pack Installer Interface

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/1d6aafde-58ae-4380-99c3-e69a472ce5d0)

![explorer_JZhrweppN8](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/960d6b40-9efa-4392-8e5d-1d8effaeb038)

![explorer_fDVJNdploP](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/7b093ab6-65f9-41a7-a931-8e6f66efa73b)

![explorer_VXP1HcxLDO](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/da6fb982-06ac-4305-9d1f-23c4646a250e)

I thought I'd throw this in as an another point of reference.

Not the greatest interface; but it was a prototype I made (before I was even aware of the likes of FOMODs or Nexus Collections); and figured I'd iterate upon it depending on how much adoption there is. 

There wasn't much adoption unfortunately; lack of support from modding sites (nobody wanted to either give custom URL handlers OR allow upload with `.r2pack` extension) mainly killed it.

**Comment by halgari** [comment]
Nexus Mod Manager

Static Mesh Improvement Mod:
![nmm_1](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/3c5da4ab-9190-4da6-a504-0bd97085d55d)

Falmer Armors and Weapons Retexture:
![nmm_2](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/eee5aeb5-03c7-481e-9c27-95281a20392b)
![nmm_3](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/74c92bb0-55e6-4b16-b4e8-51de0d4adf30)

**Comment by halgari** [comment]
Examples from ModDrop

Static Mesh Improvement Mod:
![moddrop_1](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/ab326f31-75d9-4206-ab3e-9812ef5130a5)
![moddrop_2](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/297fece3-2b17-44ba-8c9b-1719c44feff4)
![moddrop_3](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/2f446d73-502a-4c92-af98-f275cc14e969)
![moddrop_4](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/846e7f09-6894-4d1a-8c3c-7d3e2947e0c8)

Falmer Armors and Weapons Retexture:
![moddrop_5](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/77de2e93-a2e8-478f-b385-230dd1199bc0)
![moddrop_6](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/fce6c17f-e140-4466-ba5c-dfb9d001c326)

**Comment by Greg-Nexus** [comment]
@Greg-Nexus Add DODs

@captainsandypants Add Designs

**Comment by Al12rs** [comment]
A quick reference of the design, all the details are on figma:
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/41378a5f-74b0-4ac0-b1ca-5be5056ba522)

Figma: https://www.figma.com/file/Ntr9PttR5VrqpTRwwZHzLu/%F0%9F%93%B1-Mod-list?type=design&node-id=1548-4036&mode=design&t=atCgsgap5uzlIPfp-4

Splitting into components:
- Footer stepper for the bottom Previous / progress bar / Next component:
https://www.figma.com/file/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%A7%B1-App-components?type=design&node-id=655-3315&mode=design&t=ip7fbwK9mtKiSKFz-4

- left and right panels? Im not sure if these should be dedicated components or not.

Icons:
- tune
- image
- file

**Comment by Al12rs** [comment]
This is missing https://github.com/Nexus-Mods/NexusMods.App/issues/614
to allow displaying images stored in the archive.

The majority of this ticket was handled in https://github.com/Nexus-Mods/NexusMods.App/pull/600
