### ISSUE TITLE
Epic: i18n and l10n - Internationalisation and Localisation

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#330]
## Introduction

`i18n` and `l10n` describe the process of adapting our code to be locale agnostic. Currently, our UI contains hard-coded strings, meaning the values are constant and part of our code:

https://github.com/Nexus-Mods/NexusMods.App/blob/b1c50408a4692b54a5c488dbcf151d923c66f873/src/NexusMods.App.UI/LeftMenu/Home/HomeLeftMenuViewModel.cs#L23-L37

Although this makes designing and implementing user interfaces very straightforward, it also means that we force English as a UI language.

## Problems

Aside from text translations, `i18n` and `l10n` also encompass formatting rules for various constructs like numbers, date and time, currencies, as well as text layouts. English is left-to-right and top-to-bottom horizontally, but other languages read from right-to-left and some even vertically.

This adds additional complexity to the design process of UIs, since they have to made locale agnostic. If a button has a text of length `10` in English, it might only contain two characters in Japanese or `20` in German. If the UI isn't able to adapt to the drastic changes in text, it will lead to text cutoff, undesired wrapping behavior or make the text completely illegible.

Another issue are fonts. Most fonts used on the web only support a limited amount of characters. CJK fonts (**C**hinese, **J**apanese, and **K**orean), like [Noto by Google](https://fonts.google.com/noto), are special fonts that contain a vast amount of characters from all parts of the world. These are usually not required by websites, since browsers have fallback fonts, however, for applications that render text directly, drawing an unsupported character will usually result in white boxes: https://github.com/jellyfin/jellyfin/issues/5008

https://user-images.githubusercontent.com/39822140/104345555-d5045c00-5541-11eb-953d-f3943a6c63ee.png

## Solutions

Structs like `int`, `double` and `DateTime`, all provide a `ToString` overload that accepts an `IFormatProvider`. Internationalization requires that we use `ToString(CultureInfo.CurrentUICulture)` instead of the normal `ToString`. Source Analyzers can be used to detect these usages and produce warnings.

Avalonia doesn't have "native" support for translations yet. Some discussions are happening in https://github.com/AvaloniaUI/Avalonia/discussions/7131 and https://github.com/AvaloniaUI/Avalonia/discussions/8741, however nothing has been implemented yet. As such, DIY solutions have been created in these two blog posts: [Theming and Localization Functionality for Multiplatform Avalonia UI Framework](https://www.codeproject.com/Articles/5317972/Theming-and-Localization-Functionality-for-Multipl) and [Localization in AvaloniaUI](https://dev.to/ingvarx/localization-in-avaloniaui-2mdm).

### Experimental DIY Solution

The first blog post uses Avalonia [Resource Dictionaries](https://github.com/npolyak/NP.Avalonia.Demos/blob/main/NP.Demos.ThemingAndL10N/NP.Demos.ThemingAndLocalizationDemo/LanguageDictionaries/HebrewResources.axaml) for each language, to define translation strings and, as well as text layout. These resource dictionaries are inlined into the main assembly and can quickly be loaded on demand. This solution has multiple issues:

The resource dictionaries are neither supported by traditional translation services nor the IDE itself, meaning adding, removing and changing translations is going to take up a lot of time and effort. Furthermore, the runtime performance is hindered by a lookup into a dictionary.

### Resource Files

The second blog post uses [resource files](https://learn.microsoft.com/en-us/dotnet/core/extensions/resources), which have been a part of .NET for a long time. These files are supported by Visual Studio and JetBrains Rider, as well as translation services like [weblate](https://docs.weblate.org/en/latest/formats/resx.html).

Using JetBrains Rider as an example, this is the typical workflow ([Docs](https://www.jetbrains.com/help/rider/Resources__Index.html)):

![2023-05-22_14-13-24](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/39ae21f3-7f43-4d16-809e-071fbb1de582)
![2023-05-22_14-13-45](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/41a57b15-aaf6-4411-af1d-a574b7c53ced)

A string can be selected and moved into a resource using the refactoring methods.

![2023-05-22_14-13-58](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/5be8c247-147d-4d85-bebb-b6da85751992)

The [Localization Manager](https://www.jetbrains.com/help/rider/Resources__LocalizationManager.html) provides an interface for viewing and managing all strings.

The current locale can be changed using `Thread.CurrentThread.CurrentUICulture`:

```csharp
Thread.CurrentThread.CurrentUICulture = CultureInfo.GetCultureInfo("de");
```

The IDE has also updated the code from `Name = "Newsfeed"` to `Name = Resources.Newsfeed`:

![2023-05-22_15-00-02](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/2f784579-43a4-40be-983c-5996d6ab7d56)

Finally, running the app will show the results:

![2023-05-22_13-53-30](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/44b1e9da-1d7f-4ab6-96ee-3221d19d4f74)
![2023-05-22_14-57-31](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/e3647605-371f-4d68-ae33-979ab44d3abf)

The biggest issue with this solution is how the resources are being loaded. Each supported language has an accompanying DLL, containing the values. This DLL gets loaded dynamically by the .NET runtime when switching the current locale. As such, there is a small startup performance hit and other features like trimming and AOT could be compromised (requires more research).

String interpolation is also not possible with this approach, and `string.Format` has to be used instead:

```csharp
// original
Console.WriteLine($"Hello {user}")

// using resources
Console.WriteLine(string.Format(Resources.Hello), user);
```

Since there is no compile check being done, badly formatted resource strings can lead to unexpected runtime exceptions.

Some projects like https://github.com/DotNetPlus/ReswPlus exist to provide auto generation of strongly typed static properties and strongly typed string formatting, but more research can be done here.

## Misc

Something of note: Microsoft is very pedantic about localization. They have an entire section about this topic in the [docs](https://learn.microsoft.com/en-us/dotnet/core/extensions/globalization-and-localization), however, they also translated the .NET exceptions. This makes debugging extremely hard and is something we should avoid at all cost. Only the user facing elements, like the UI, should be translated, not the logs and not the exceptions.

## Associated Tasks
 - Backend (https://github.com/Nexus-Mods/NexusMods.App/issues/452)
 - Implementation throughout the app (https://github.com/Nexus-Mods/NexusMods.App/issues/453)

**Comment by Al12rs** [comment]
This page was added two weeks ago to the official Avalonia Docs:
https://docs.avaloniaui.net/docs/next/guides/implementation-guides/localizing
It's not much and it is the only reference to localization or internationalization I could find in there at the moment.

**Comment by erri120** [comment]
> This page was added two weeks ago to the official Avalonia Docs: https://docs.avaloniaui.net/docs/next/guides/implementation-guides/localizing It's not much and it is the only reference to localization or internationalization I could find in there at the moment.

Interestingly, they use `Assets.Resources.Culture` instead of `Thread.CurrentThread.CurrentUICulture` to set the current culture.

**Comment by erri120** [comment]
One interesting thing to note:

Using `<TextBlock Text="{x:Static assets:Resources.GreetingText}"/>` only works when `Resources` and `GreetingText` are `public`. The class `Resources` generated by Rider is `internal` by default, which results in a compile error.

I'm not sure if this is something Avalonia or Rider should fix. I'll check both fronts for a solution.

**Comment by halgari** [comment]
Clased as part of #587 and #453
