### ISSUE TITLE
Typography update

### ISSUE THREAD

**Issue by captainsandypants** [Nexus-Mods/NexusMods.App#346]
# Improvement
## Currently
The app is using the old text styles.

## We want
To use the new text styles that have an improved scaling and naming convention.
We have also have tokenised the font properties (weight, size, letter spacing etc.), we would like to do this on Avalonia too, if possible.

## Design
[Figma link to new styles listed with the old styles they are to replace.](https://www.figma.com/file/8pjtQeNggvVi7RWoLNGV80/%F0%9F%A7%B0-Nexus-Mods-Design-System?type=design&node-id=3744%3A12851&t=18excbN3wKRS80TM-1)  

![Image](https://user-images.githubusercontent.com/118466382/244085882-872ab531-139e-40b7-ab69-3d83bfe27590.png)

**Comment by halgari** [comment]
This is fantastic, what I'd love to do is to find some sort of way to define all these styles once, then apply them via a macro-like thing. Where we can do:

```
<MacroStyle x:Name="heading_2xl_semi">
  <Setter Property="FontSize" Value="60"/>
  ...
</MacroStyle>


<Style Selector="Button.Header TextBlock">
  <Apply Name="heading_2xl_semi"/>
</StyleSelector>
```

If I can find a way to abstract our styles in this way we can define our Typography in one file, and then reuse it in all our control styles. Don't know how to do this yet, but I'm researching it.

**Comment by Al12rs** [comment]
This was done with the Styling rework
