### ISSUE TITLE
`JsonName` -> `JsonTypeId`

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#350]
# Improvement

## Currently 
`JsonName` uses a arbitrary developer defined strings to name `Entities`. How we define these names is ill defined. Sometimes we use `nameof` sometimes we use the class name, other times we use a namespaced name. 

## We want
A more standardized way of naming entities that is both easy to extend, and allows us to move the classes around in the project

## Solution
Let's change `JsonName` to `JsonTypeId` and use Guids in the name. We can generate these in Rider by typing `"nguid"` and using auto-complete to generate a new guid. This change may impact debugging a bit, but it does allow us to store entity type IDs as a number instead of an arbitrary string, and will standardize the storage format.

**Comment by erri120** [comment]
A combination of `nameof` and a GUID would be better for debugging:

```csharp
[JsonTypeId($"{nameof(MyRecord)}-93b10036-493f-49c9-bbf1-c25bd82b02b6")]
public record MyRecord;
```

Somewhat related to this is #290, as we currently don't have any versioning for our data, meaning that any change will always be a breaking change. Maybe a combination of GUID+Version, similarly to our file analyzers, would at least let consumers know, that the model changed.

**Comment by Sewer56** [comment]
This is a candidate for closing with Event Sourcing.
Since we will no longer use this mechanism.

**Comment by LukeNexusMods** [comment]
Are we able to close this ticket now?

**Comment by Al12rs** [comment]
We are still using this, we haven't integrated the new db and replaced all our previous db usage yet.
Actually I don't know if we might have any similar issue with the new db, should check with Tim.

**Comment by halgari** [comment]
Not going to do this, instead remove JSON encoding from the data model and use MnemonicDB for polymorphism.
