### ISSUE TITLE
Add OSX Support to GameFinder (on the GameFinder repo)

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#351]
# Improvement

## Currently 
Game Finder doesn't support steam on OSX, let's implement that and submit a PR to the repo

**Comment by erri120** [comment]
Unless Steam on macOS is very weird, the only cross-platform part in GameFinder is finding Steam using the default installation directory.

**Comment by erri120** [comment]
Only Steam is officially supported on macOS.
