### ISSUE TITLE
FoundGamesView is causing performance issues in switching application pages.

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#358]
# Improvement

## Currently 

Switching into the 'My Games' and 'Found Games' views are extremely slow, even if there are no actual found games.

## Supporting Information
Running in Debug mode on a laptop with a 3550H; 

```
00:01:54.253 [DEBUG] Finding View for NexusMods.App.UI.RightContent.FoundGamesViewModel
00:01:54.254 [INFO] Creating View
00:01:54.730 [INFO] View Created!!
```

## Cause

The `FoundGamesView` control has the following code:

```xaml
<DataContext>
    <rightContent:FoundGamesDesignViewModel />
</DataContext>
```

Constructor of `FoundGamesDesignViewModel` has the following:

```csharp
var games = Enumerable.Range(0, 10).Select(_ => new GameWidgetDesignViewModel());
```

And `GameWidgetDesignViewModel` has this:

```csharp
Image = new Bitmap(AssetLoader.Open(new Uri("avares://NexusMods.App.UI/Assets/DesignTime/cyberpunk_game.png")));
```

The image is not cached; so this image is decoded 10 times every time `FoundGamesDesignViewModel` is created; which in the case of `My Games` view, twice (total 20 decodes).

## Solution

Only use `DataContext` in design mode.

```xaml
<Design.DataContext>
    <rightContent:FoundGamesDesignViewModel />
</Design.DataContext>
```

## Other Notes

Fixed in 6cc444b070e206a74bf51c6e9f337423df0c6fb6 on branch cancel-downloads-new.

**Comment by halgari** [comment]
Yep, makes sense, I think that's left over from when I was experimenting with the design code
