### ISSUE TITLE
ID updates get skipped during high-throughput

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#372]
Our IPC system breaks down during high-throughput activities, like installing a mod, and the `SqliteDataStore.IdChanges` observable is unable to keep up. I found this while working on #362, as I hoped that ID-changes can be used to track when a new loadout-revision was created to re-run diagnostics.

The system works when debugging using breakpoints, which add latency and allow the system additional processing time between ID-updates. I'm unclear whether this is a bug in our code, or a limitation of Sqlite itself, or our entire IPC system.

Tasks:

- [x] #437
- [x] #501
- [ ] #502 
- [ ] fix ID updates being skipped

**Comment by halgari** [comment]
I saw an issue like this once, where the IPC system (the memory mapped file) would say that there was a new ID, but SQLite may not have completely flushed the changes to disk and so the change isn't viewable from other processes yet. I thought I had resolved this via using transactions but it could still be an issue.

The best way to fix this is to probably write a few more tests around it and see if we can get it to break in the tests.

**Comment by erri120** [comment]
This issue is also responsible for some UI bugs we have. When the user installs a mod, our code will quickly update the loadout a bunch of times, which can lead to the ID updates being skipped. Our UI is subscribed to those updates, so not getting any means the UI has to be refreshed manually for the new mods to appear.

**Comment by erri120** [comment]
Batching might be a possible solution for this. Instead of pushing one update at a time, we collect a bunch of updates over a fixed period of time and then push multiple updates as one.

**Comment by erri120** [comment]
Our code also often locks parts of Sqlite completely. This is especially the case with jobs, which get updated and removed frequently, leading to scenarios where a read and write happen at the same time. This slows down the entire thing, and Sqlite will throw an exception after a timeout.

**Comment by erri120** [comment]
Adding a `CommandTimeout` to the `UpdateProgress` method will result in `SQLite Error 5: 'database is locked'`.
