### ISSUE TITLE
As a user, I want to uninstall the Nexus Mods App

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#377]
# User story

**As a** user

**I want to** uninstall the Nexus Mods App

**So that** it is no longer on my system

## Requirements

Consider how users uninstall the app, e.g. any wizard/splash screen we may provide.

We'll want to add an uninstallation survey, which will capture reasons for removing the app.

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by LukeNexusMods** [comment]
Currently some files are left behind when uninstalling the app. This ticket would be to update the current installer so that there are no more manual steps to uninstall files left behind by the current installer.

**Comment by erri120** [comment]
> Currently some files are left behind when uninstalling the app. This ticket would be to update the current installer so that there are no more manual steps to uninstall files left behind by the current installer.

With "current installer", do you mean the InnoSetup on Windows?

**Comment by LukeNexusMods** [comment]
Which one will I have used for windows?

**Comment by Sewer56** [comment]
InnoSetup

**Comment by erri120** [comment]
Should make a CLI command to remove all files. Uninstallers can call that before uninstalling.

**Comment by LukeNexusMods** [comment]
Reopened the issue as there are still app and backup files after running the uninstall on windows.

**Comment by Al12rs** [comment]
@Sewer56 So you write down the files_to_delete and directories_to_delete in the app and then delete them from the app.
Why not have the initial script that called app.exe uninstall-app delete those folders? Seems easier on windows that trying to delete yourself. 

As a fallback I would always delete `Appdata/local/NexusMods.App` . We can change this in the future if we start supporting other locations or we need to keep that intact for some reason.

**Comment by Sewer56** [comment]
Fixed in
- #1503

Was a bug specific to how we release the app. Which is different than our Git Builds 
This is now noted in:
- #1511

As for the comment above, some talk on this is on Slack.
