### ISSUE TITLE
Loadouts - As a user, I want to remove mods from a loadout

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#403]
# User story

**As a** user

**I want to** remove a mod from a loadout

**So that** the mod no longer applies to my game

## Requirements
Users need to be able to quickly and easily remove mods from a loadout.

Verify that deleting a mod from a loadout will not show it again in the UI (including on reload) and that this delete status is respected by the Apply/Ingest routines. This may already be supported but it should be verified (perhaps with a test).

**Comment by Sewer56** [comment]
## Update

Removing mods from a loadout is supported in the GUI, but not supported from CLI in 2024.

Note: 'Mod Libraries' are covered under
- https://github.com/Nexus-Mods/NexusMods.App/issues/523

Note 2: There is no 'garbage collection' mechanism currently, so removed mods do stay on disk; however that's probably outside of the scope of this issue.

**Comment by halgari** [comment]
We think this is done, so make sure it deletes the mod, and that apply removes the files.

**Comment by halgari** [comment]
Verified working on main. Deleted a mod and the apply diff showed the files as ready to be deleted.
