### ISSUE TITLE
Game Support - Stardew Valley

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#42]
## Outline

The desired outcome of this issue is that Stardew Valley:

- is automatically detected; AND
- game version is detected; AND
- can be managed by Nexus Mods App; AND
- the most common mods can be installed; AND
- the game starts with mods installed (and the mods work).

...for all applicable game stores (see below).

## Supporting Information

- Stores
  - [Steam](https://store.steampowered.com/app/413150/Stardew_Valley/)
  - [GOG](https://www.gog.com/game/stardew_valley)
  - [Xbox Game Pass](https://www.xbox.com/en-US/games/store/p/9MWR1NC6VQ6L)
- Automatic Game Detection
  - [ ] Steam
  - [ ] GOG
  - [ ] Windows Game Store
- Game Version Detection
  - [ ] Steam
  - [ ] GOG
  - [ ] Windows Game Store
- Game Managed
  - [ ] Steam
  - [ ] GOG
  - [ ] Windows Game Store

**Comment by LetsTussleBoiz** [comment]
As a fervent modder and mod maker for Stardew, it's also vital that the SMAPI installation be automated as well. Potentially even Content Patcher, but that one is less obvious.
