### ISSUE TITLE
Game Support - Blade & Sorcery

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#43]
## Outline

The desired outcome of this issue is that Blade & Sorcery:

- is automatically detected; AND
- game version is detected; AND
- can be managed by Nexus Mods App; AND
- the most common mods can be installed; AND
- the game starts with mods installed (and the mods work).

...for all applicable game stores (see below).

## Supporting Information

- Automatic Game Detection
  - [ ] Steam
- Game Version Detection
  - [ ] Steam
- Game Managed
  - [ ] Steam

**Comment by nepellion** [comment]
I've never contributed to open-source projects, but this seemed like an easy start as it's Windows-only and Steam-only..
Tracked in draft PR #700.

OT: I've wanted to ask, is the discord for this app internal/private or is the link in readme just broken?

**Comment by Sewer56** [comment]
>  I've wanted to ask, is the discord for this app internal/private or is the link in readme just broken?

The server isn't set as community server, which limits invite links to 30 days. We have to reset them every month.

**Comment by Greg-Nexus** [comment]
https://github.com/Nexus-Mods/NexusMods.App/pull/700
