### ISSUE TITLE
As a user, I want to use an advanced installer to install a mod

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#449]
# User story

**As a** user

**I want to** handle manually installed mods

**So that** I can install mods manually and manage them via the app

## Requirements
Users need a way to manually configure files during mod installation. This is used as a "bail-out" or "escape hatch" when no other installers will work. 

### Issues

1. Backend (https://github.com/Nexus-Mods/NexusMods.App/issues/610)
2. Functionality (https://github.com/Nexus-Mods/NexusMods.App/issues/611)
3. Styling (this issue)

## Design
[Figma designs](https://www.figma.com/file/Ntr9PttR5VrqpTRwwZHzLu/%F0%9F%93%B1-Mod-list?type=design&node-id=1826%3A11997&mode=design&t=dAjYn6oVYz1Epo8j-1)

[Prototype](https://www.figma.com/proto/Ntr9PttR5VrqpTRwwZHzLu/%F0%9F%93%B1-Mod-list?page-id=1826%3A5125&type=design&node-id=1826-5161&viewport=579%2C196%2C0.23&t=A6zTbYWd3oKZP1wF-1&scaling=min-zoom&starting-point-node-id=1826%3A5161&mode=design)

## Scenario 1
**Given** I am installing a mod via the App

**When** the format is not recognised

**Then** I am presented with the option to use an advanced mod installer

## Scenario 2
**Given** I am installing a mod via the App where the format is not recognised

**When** I select 'Close'

**Then** the advanced mod installer closes

## Scenario 3
**Given** I am installing a mod via the App where the format is not recognised

**When** I select 'Advanced Install'

**Then** the advanced mod installer moves to the next step

## Scenario 4
**Given** I am using the advanced mod installer

**When** I select 'Cancel'

**Then** I see the advanced mod installer closes

## Scenario 5
**Given** I am using the advanced mod installer

**When** I select 'Install all' on the left-hand panel
**And** I select an install location on the right-hand panel

**Then** I see all files and folders are displayed in the selected install location on the right-hand panel

## Scenario 6
**Given** I am using the advanced mod installer

**When** I select 'Include' for a specific file on the left-hand panel
**And** I select an install location on the right-hand panel

**Then** I see the selected file is displayed in the selected install location on the right-hand panel

## Scenario 7
**Given** I am using the advanced mod installer

**When** I select 'Include' for a specific folder on the left-hand panel
**And** I select an install location on the right-hand panel

**Then** I see the selected folder and it's files are displayed in the selected install location on the right-hand panel

## Scenario 8
**Given** I am using the advanced mod installer

**When** I select 'Include' for a specific folder on the left-hand panel
**And** I select an install location on the right-hand panel
**And** a folder with the same name already exists in the target install location

**Then** I see the selected folder and it's files are merged into the selected install location on the right-hand panel
**And** I see a "Folder Merged" label on the right-hand panel

## Scenario 8
**Given** I am using the advanced mod installer
**And** I have already selected a file/folder
**And** I have already selected a target install location

**When** I select the included file/folder on the left-hand panel

**Then** I see the selected file/folder is removed from the right-hand panel

**Comment by halgari** [comment]
Here is an example of how this looks in MO2, When installing a mod you can say "Manual" and then you are showed this dialog, and you can move files around, create folders, etc. There's some complexity here that is somewhat hard for users to understand, like setting the `<data>` directory but this sort of installer is required for some badly packed mods, and/or custom installation modes

![ModOrganizer_2D7eKsUkAa](https://github.com/Nexus-Mods/NexusMods.App/assets/654621/4034b898-8e70-4ae6-a374-284935d6631e)

**Comment by Pickysaurus** [comment]
We need to think of a better way to refer to this process "install mods manually" caused a lot of confusion internally. I personally thought this meant "install a mod from file on your HDD rather than downloading from Nexus Mods".

"Restructure mods on install"?
