### ISSUE TITLE
Implement localization/internationalization throughout the app

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#453]
# Improvement

## Currently
After (#452) we have the tools we need to implement localization/internationalization throughout the app. Next step is to convert old code. 

## We want
Every UI text element, and every UI facing message needs to be abstracted to go through the translation code. 

What does not need to support translation:
* Game names
* Log messages
* Exceptions
* Class names

We *do not* intend to translate any of this on our own, simply abstract these strings into the resource files. Someone else can translate as they find the need.

**Comment by Aragas** [comment]
If possible, add the ability to programmatically import translations.
Some extensions, like Bannerlord, might come with their own translation files, so there should be an API to map the language and transform the strings correctly, so we will avoid the double work of maintaining the transactions in different formats
