### ISSUE TITLE
Investigate code-signing

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#455]
# Spike
**Timeboxed: 1 day**

## Proposal
We'll need to code-sign our app at some point. Let's look at what Vortex is doing, and spend no more than 1 day looking into how to sign our executables. If we have to do this by hand, that's fine, we'll figure it out, but there surely has to be some sort of way to sign stuff via github actions

## Impact
Long-term I want fully automated releases where we press a button, and the release is created/signed/and uploaded to Github and a message sent to Discord. We'll start by doing all this by hand, but once we know how much of this can be automated we can figure out how soon we want to move down that path. 

## Supporting Information
Vortex signs their releases, so let's talk it over with @insomnious and see how hard it will be to get secure access to the code certs

**Comment by insomnious** [comment]
I'm planning to spike exactly this for an code signing online so we can package as well as build automatically. If this isn't completed before you need an answer, give me a quick shout and I'll prioritize
