### ISSUE TITLE
Move loadout related operations out of DownloadTasks

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#461]
Some download tasks are currently handling higher level operations like mod installation, which ideally shouldn't be their responsibility.  Same for the nxm download task looking for a valid game/loadout for the download (currently causes a local exception see #336 ). 

This stuff should probably be responsibility of the caller, such as a Verb.

https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/Networking/NexusMods.Networking.Downloaders/HttpDownloadTask.cs#L90-L96

https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/Networking/NexusMods.Networking.Downloaders/NxmDownloadTask.cs#L85-L88

https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/Networking/NexusMods.Networking.Downloaders/NxmDownloadTask.cs#L108-L112

**Comment by halgari** [comment]
This is blocked on having a more complete UI design for the app, and how we want to handle windows/panes/pages

**Comment by Al12rs** [comment]
#500 does some improvements here, but a more complete solution requires what mentioned above

**Comment by Al12rs** [comment]
This is no longer the case after some changes
