### ISSUE TITLE
As a user, I want to run the game from the app (Windows)

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#463]
# User story
As a user, I want to start the game from the app with the mods applied.

**I want to** start the currently selected game with the mods active 

**So that** I may play the game with mods.

## Requirements
A game and loadout need to be selected.

Windows only.

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by Al12rs** [comment]
UI launch button appears to cause an exception at the moment. Needs investigation

**Comment by halgari** [comment]
Fixed in #505
