### ISSUE TITLE
Triaged [Added] - Show the name of the currently managed game

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#474]
Currently when a game is selected from the left spine menu, the name won't get listed anywhere except for the first mod that contains the game files (which could be renamed, removed, or simply not being the scroll view).

Some games might be difficult to distinguish from the Icons alone, for example Skyrim Legendary edition and Skyrim Special Edition:

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/5d7619fc-40ff-4210-bb60-594fc864be58)

As a user I would expect the name of the currently managed game to show up somewhere that isn't a mod. 
Suggestions:
- Top windows bar, though if I understood correctly this bar might be missing on Linux.
- New bottom status bar (some examples of status bars from Rider, Explorer, MO2):

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/94095716-3811-469f-96ea-f3b3103211e1)

**Comment by captainsandypants** [comment]
The game title is displayed in the top bar in the more recent structure designs.

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/c230ae8e-fc23-40a8-b179-8df0b857c308)

**Comment by Al12rs** [comment]
Done with #950
