### ISSUE TITLE
Expected LastTable.Rows to be a collection with 3 item(s), but found an empty collection

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#487]
Common issue when running tests. See https://github.com/Nexus-Mods/NexusMods.App/actions/runs/5679817048.

**Comment by Greg-Nexus** [comment]
Relates to #425

**Comment by halgari** [comment]
Haven't seen this in a long time thanks to changes in #486 we will continue to imporve this as part of the IPC improvements (single process app)
