### ISSUE TITLE
Use an extensible solution for IDs instead of Enums for GameFolderType

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#492]
GameFolderType currently is an Enum defined in the main App, that identifies a small list of common game paths that the main application and other components might need to reference in a game installation agnostic way.

The issue is that some games might have particular paths they need to expose that aren't present in other games.
If new game needs to add one such identifiable path it would need to edit the shared Enum. 
The problem is that the enum would quickly get polluted with game specific path ids that might be interpreted differently for different games.

A different solution is needed, one that doesn't rely on a central shared list of IDs but instead allows each game to define its own list in addition to the common ones.

Many of these paths could likely be useful for other extension components (mod installers, diagnostics, etc), while the main application could realistically not need to be aware of them.

So it would be convenient for games to be able to define new PathIds without having to change the main app code, while still allowing other components to reference them. 
The developer of the extension or component will need to know the static ID of the path it needs and check for its existence in the currently managed game.
This admittedly isn't very elegant, but would allow bypassing visibility of the ID definition.

It can make it harder for developers to find the correct ID that is needed to be implemented for a game. 

For example all bethesda games have the `Data` folder, to add a new Bethesda game, the developer would need to look for what ID was used in the other games to define Data and make sure to reuse the same. Any extension developer wanting to reference Data would need to look up the exact ID to use. This is somewhat simplified in the case of human readable IDs like strings. while more error prone in the case of GUIDs for example.

## Proposal:
Use statically defined GUIDs wrapped in ValueObjects (for Nominal Typing) as GamePathTypes (or GamePathIds)

To define a new GUID statically on Rider, you can press Shift twice, type in GUID and there is an option to generate a GUID in various formats.

App defines a default list of common GamePathTypes (game, saves, confic, appdata)
Game then exposes a collection of GamePaths with either the App defined IDs or custom IDs.

Upside is fixed size of IDs and very low chance of collision and ability for any component to check for a path if they know the ID, even if the game type that defined it isn't visible from the extension or component.

Downside is non human readable nature of the ID. 
You can name the value object instance in the code that references a particular path ID instead.

**Comment by Al12rs** [comment]
I agree that strings would come much more natural and intuitive to me as well. The main downsides there are the general inefficiency in string comparisons and the fact that the ids wouldn't have fixed sizes. 

Since we have thousands of GamePaths moving around in the application I would be more comfortable with a fixed size ID.

An idea could be that of using strings to query the actual GamePathId from the Game, which will keep a dictionary of them, so that the program uses GUIDs internally, but a developer can obtain the GUID using a string.

It is getting a bit complicated though over using a simple Enum, so it might not be very appreciated.

**Comment by Al12rs** [comment]
We could use a hash of a string to get fixed sizes. 
- What kind of hash?
- Should the program compute the hash at runtime or should it be baked statically?
- If statically, how can a developer easily obtain the hash of the string ID?

**Comment by Aragas** [comment]
A hash would be identical in functionality to a GUID for consumers
We basically give the ability to use a static hash (with the original lost in this case) or use the human readable source converted at runtime or compilation if using source generator, but then you'll have two id's, and if the original of the hash isn't stored besides the hash, then again, lost info

I assume that it will work only if we always operate with the original source, but the internals (lower than the game extensiom level) operate with the hash, but I don't see the point here

**Comment by Al12rs** [comment]
Maybe something like `GamePathId.From("load_order_file_fath")` .
All the code would see is GamePathId objects which contain only the hash, but one can obtain the Id using the a known string.
The first time the ID is defined it will also be created using `From("idString")`.

The main code can handle the GamePathId object directly, while any extension developer that might need to identify a specific path will have to look up the string from the Game class where the IDs are defined.

**Comment by Greg-Nexus** [comment]
Change to GUIDs, but also have a centralised list of well known ones.

**Comment by Al12rs** [comment]
Rough Notes from meeting:
- Use ValueObjects as the ID, with string/Integer have the game return a dictionary
- Have the main app reserve the first 100
- Ids are scoped per game
- No problem with value objects for serialization/deserialization, auto serializes underlying types
- Game has access to the install so it should be able to create the bindings
- Game class can handle checking for nested relationships and so that we can query that info
