### ISSUE TITLE
[Machine Specific] IPC Events Received with Huge Delay

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#495]
# Bug Report

## Summary

Cause is unclear. On my current dev machine, when an IPC event is fired, it can take multiple minutes for it to arrive on the App end. Usually a few minutes, but I've ran into cases where I basically gave up waiting for it to arrive. 

The messages don't appear to get dropped and do eventually arrive (e.g. sometimes very shortly after a restart of the app). 

I've first experienced this after one merges from `main` when I was developing the feature to `cancel download` 2 sprints ago, sometime after I merged main after delivering a demo.

Possible commit IDs are therefore:  

- 4c1bc4899a3501034d998b4a0141a109608ab5ae
- 91d74d9055e16e370c6e5667955fe7ee4d08b72c
- 0b193468df8dfdbace7b70dec87be7ce8a5393ce

It reproduces on my desktop but not my laptop; even after a full repo clean (`git clean -xdf`). 

This only affects out-of-process writes (e.g. opening an `nxm://` link); in-process writes such as unit tests and OAuth appear to be fine.

Current cause is unknown.

## Steps to reproduce

- Trigger an IPC event, such as downloading an `nxm://` link.
- Observe... nothing.

## Other information

***I consider this hard blocking me from my sprint work***; and request to investigate immediately. 

I'm practically unable to verify my code outside of unit tests as is, at one point I spent 20 minutes trying to initiate a download; it was so slow I proceeded to work on my very slow laptop instead for the time being. However that too, wastes time. [I was hoping to submit a PR today, but couldn't; due to runtime only DI issue I found on laptop as I was doublechecking before submission]

The only thing I know (currently) is that it's not an issue with any of the higher level components. Rather, the lowest level IPC related component `ProcessMessages` in `SqliteIPC` is not seeing anything; for a long time; as if the write itself was hugely delayed.

Maybe some sort of flushing related issue. This needs investigation.

**Comment by erri120** [comment]
Possibly related to #372.

**Comment by Sewer56** [comment]
This was fixed in https://github.com/Nexus-Mods/NexusMods.App/pull/555
