### ISSUE TITLE
Need to Set Explicit Working Directory in Protocol Handlers

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#513]
# Improvement

## Currently 

Currently, protocol handlers like `nxm://` don't set a specific working directory. 
This is especially problematic on non-WIndows, where it defaults to the user's `$HOME` folder. 

Because we use Microsoft's Host Builder (`Host.CreateDefaultBuilder`) during startup, it scans the current working directory recursively [as it's most likely looking for something]. This can cause significant delays if the current working directory contains many files.

In my case, this (currently) causes a delay of approximately 7 minutes in IPC operation as my home folder contains over 500,000 files; which the host builder is taking forever to look through.

## We want

For this, and other related reasons, we should set a specific working directory for the protocol handlers.  

## Design

At the very least on non-Windows systems, we need to modify the protocol handler registration code to set a specific working directory.

This will include updating `IProtocolRegistration` to allow specifying a working directory.
In the case of Linux, we need to set the `Path` field inside the `.desktop` file to the location of the working directory.

**Comment by halgari** [comment]
We should investigate as part of this why it's scanning all the folders, and if we can stop the scan (and use our hardcoded config paths)
