### ISSUE TITLE
Button doesn't enter focused state randomly

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#518]
https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/249a5654-91ad-471b-9068-8cde68a788db

**Comment by erri120** [comment]
The FOMOD installer "next" button is also susceptible to this.

**Comment by erri120** [comment]
@Al12rs is this still an issue?

**Comment by Al12rs** [comment]
Doesn't seem that way for the Downloads tool bar.
Tested the fomod installer as well and was not able to reproduce. Might have been an issue with using a transparent background or something along those lines.
