### ISSUE TITLE
Don't allow users to add the same mod multiple times to a loadout

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#527]
# Bug Report

## Summary
Users seem to be able to add a mod to a loadout an infinite number of times.

## Steps to reproduce
1. Launch the app
2. Login
3. Manage a game (e.g. Skyrim)
4. Download SkyUI multiple times
5. See the mod multiple times in the default loadout

## What is the expected behaviour?
Not too sure on the UI, we'll need some input from Design.

I don't think there is a valid use-case for downloading the same mod over and over?

## Other information
![SkyUI](https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/e20e9c7d-765a-4b17-aa5b-71cff364ef02)

**Comment by Al12rs** [comment]
Users should be able to reinstall the same mod multiple times and have different versions. 
Consider the case of FOMODs for example, where each mod installation can have different options.

In general there are use cases for having multiple installations of the same mod.
What isn't useful is downloading the same file multiple times, though to be sure some hashing would be needed to make sure that the new download isn't different (perhaps the first one got corrupted or something).

**Comment by erri120** [comment]
Downloading the same file again doesn't make sense, but installing the same file multiple times should be valid. If you try to do that in MO2, a dialog box will open that asks the user whether they want to replace the existing mod or create a new mod with a different name.
