### ISSUE TITLE
`IO Exception: Connection reset by peer` flaky AdvancedHttpDownloaderTests

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#536]
Test: `NexusMods.Networking.HttpDownloader.Tests.AdvancedHttpDownloaderTests.CanDownloadFromUnreliableSource`
Run:
https://github.com/Nexus-Mods/NexusMods.App/actions/runs/5798366295/job/15716846995#step:6:578

**Comment by halgari** [comment]
Haven't seen these in a long time, since I added a lot of retries to the networking logic
