### ISSUE TITLE
Remove ArchiveAnalyzer and move the code into installers

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#554]
Stop using static analysis for file analyzing. Instead of analyzing an archive contents once, we can now hand easy to access data streams to installers and allow them to perform their own content analysis if desired. This removes a lot of stale caching issues and allows installers to always have up-to-date information on files.

This will require that ModInstallers recieve a file tree of file names, hashes, and a `Stream entry.Open()` method for gaining readonly seekable access to an input entry. Should also leverage #553

**Comment by erri120** [comment]
Done in #615
