### ISSUE TITLE
Install queue, pause, cancel, reorder

### ISSUE THREAD

**Issue by HawthorneK456** [Nexus-Mods/NexusMods.App#584]
# User story

**As a** Nexus Mods App user

**I want to** view a queue of mods which are downloading

**So that** I can choose to pause/cancel downloads which have not yet completed
**AND** change the queue order

## Requirements
This was an improvement originally requested for Vortex: https://github.com/Nexus-Mods/Vortex/issues/318 

Probably want to split this into multiple stories if you choose to implement this. 

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by LukeNexusMods** [comment]
Done

**Comment by Al12rs** [comment]
We don't actually have this @LukeNexusMods 
The original issue was referring to mod installation, not mod download (in vortex installation happens automatically after download, it is harder to refer to the different operations).

What the original report was asking for was to improve the experience when trying to install multiple mods at the same time.
Specifically being able visually see a queue of install operations and being able to manipulate that queue by cancelling, pausing, resuming and reordering.

We have nothing for reordering, neither for downloads nor for installs, and installs don't have any of the requested options.

We might not end up needing the options depending on our UX approach to multiple mod installs, but we will not know until then.
