### ISSUE TITLE
GitHub Labels cleanup and standardization across App related Repos 

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#588]
The NexusMods.App repo has a lot of Labels already and we will need to add more due to the absence of good Epic tracking on GitHub.
It would be good to flesh them out and remove any old ones we shouldn't use.

Once that is done, the same labels should be also ported to other repositories relevant to App development:
- https://github.com/Nexus-Mods/NexusMods.Paths
- https://github.com/Nexus-Mods/NexusMods.Archives.Nx
- https://github.com/Nexus-Mods/NexusMods.Hashing.xxHash64
- https://github.com/Nexus-Mods/NexusMods.App.Meta

To simplify that process it might be worth looking into automatization of the process.

In case automatic cloning of the labels isn't possible, then we should ensure the essential ones, such as the weights are available.

**Comment by erri120** [comment]
You can find various "sync label"-actions on the marketplace: https://github.com/marketplace?query=sync+labels like https://github.com/micnncim/action-label-syncer.

**Comment by Al12rs** [comment]
@LukeNexusMods kinda did this, haven't really been using the other repos tickets
