### ISSUE TITLE
Streamline and facilitate external contributions by removing Commit Signing requirements

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#589]
The following repos have Commit signing requirement enabled:
- https://github.com/Nexus-Mods/NexusMods.App.Meta
- https://github.com/Nexus-Mods/NexusMods.Paths

Commit signing verifies the authenticity of the name and email on the commit. This isn't particularly useful as the developers with merge permissions are limited to the core development team and all external contributions need to be reviewed anyways. 

Commit signing only avoids commit impersonation, which by itself doesn't really enable malicious actors to do much anyways, as all contributions are reviewed.

The signing requirement on the other hand is very frustrating for good intentioned contributors that after finishing their work find out that all their commits are not accepted due to signing requirement at merge time, as the requirement isn't made apparent before then.

Setting up signing can be quite frustrating and time consuming itself depending on the git programs used and the platform (~2h+ for both me and Seweryn), and then it can ask for password at each commit depending on the signing solution used, which isn't very streamlined.

The signing requirement is not something common in open source development (neither me nor Seweryn have encountered a public project requiring it), and the downsides seem to outweigh the limited benefits.

People with permissions to change this on the motioned repos should be @halgari and @erri120

**Comment by Sewer56** [comment]
@Nexus-Mods/nexusmods-app-developers 

Suggesting for closing.

I believe this was done on all major affected repos (including template). Some repos that haven't been touched for a while (or created a long time back) may still have this limitation, we can fix that as we run across it.

**Comment by Al12rs** [comment]
Agreed
