### ISSUE TITLE
Undeploying Mods Leaves Behind Empty Directories

### ISSUE THREAD

**Issue by Sewer56** [Nexus-Mods/NexusMods.App#593]
# Bug Report

## Summary

When a mod is undeployed (i.e., removed from the current loadout and then deployment is ran), empty directories are left in the game folder that did not originally exist at the time of first adding the game. This leads to clutter and could potentially leave a lot of junk in certain games' folders over time as the user removes and re-adds mods.

![20230829_08h07m45s_grim](https://github.com/Nexus-Mods/NexusMods.App/assets/6697380/4cdc598a-1956-489d-a621-c005b1e4f676)

## Steps to reproduce

1. Add a game for management in the Nexus Mods App.
2. Deploy a mod to the game that creates new directories.
3. Undeploy the mod from the current loadout.
4. Check the game folder; the empty directories from the undeployed mod will still be present.

## What is the expected behaviour?

When a mod is undeployed, any directories that were created by that mod and that are now empty should be removed from the game folder. 

## Other information

A possible approach is the following:

1. Scan the current folder's directories in a post-deployment operation, and remove directories which:
- Are not expected to be in deployed data/files.
- Are empty.

Note: Empty directories inserted by mods should probably not be removed in case we run into a situation where games do checks on empty directories (e.g. doing special behaviour if a given directory exists).

**Comment by Al12rs** [comment]
Fixed with #1218
