### ISSUE TITLE
Use static resources for translations

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#601]
#563 allowed for live updating of translation strings, see #599 for additional details. Currently, the login text that uses the `LocalizedExtension` class doesn't appear:

![2023-09-04_14-47-15](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/27e47fa3-db16-4684-816e-4763059196b0)

Changing this to a static resource fixed the issue:

![2023-09-04_14-53-30](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/40da20db-2fe5-437f-b207-99d7452195b3)

Since live updating wasn't part of the requirement and adds unnecessary complexity, it might be better to drop it entirely and simply ask the user to restart the app.

Static resources also have compile time checks, which will prevent these issues from occurring:

![2023-09-04_15-17-34](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/2e1e2ea3-c4aa-4d9d-a6de-68d5968acd29)

**Comment by Al12rs** [comment]
We discussed in standup to use static references instead of live updating.
Reasonings are:
- Compile safety in XML
- Less complexity when making a string localizable.
