### ISSUE TITLE
UI to reflect currently managed games

### ISSUE THREAD

**Issue by HawthorneK456** [Nexus-Mods/NexusMods.App#609]
# User story

**As a** Nexus Mods App user

**I want** the web app UI to reflect the current game that I'm managing

**So that** the experience modding the game feels consistent with playing the game and reflects some of the imagery from the game and the Nexus Mods Website.

## Requirements
This was originally requested as a feature for extending the themes in Vortex: https://github.com/Nexus-Mods/Vortex/issues/2293

Some users actually created and uploaded some themes for Vortex themselves to the Nexus site to provide this functionality: 

Some examples:
- https://www.nexusmods.com/site/mods/541 (Unique DLs 3,279)
- https://www.nexusmods.com/site/mods/327 (Unique DLs 6,475)
- https://www.nexusmods.com/site/mods/414 (Unique DLs 2,716)

Not a high priority and not sure what if any customised theming we want to support in the web app & if we do whether we can adopt the same approach that our community can create and share them? Making a note here for consideration.

## Design
_(Any designs required for this story)_

## DOD
_(Describe the expected behaviour from the users point of view. Create multiple DoD's if required to fully describe what should happen. Number each DoD)_

## Scenario 1
**Given** _______

**When** _______

**Then** _______

**Comment by erri120** [comment]
Similar to #474.

**Comment by Al12rs** [comment]
Implemented
