### ISSUE TITLE
Discover & manage games installed via Heroic Games Launcher

### ISSUE THREAD

**Issue by MattSturgeon** [Nexus-Mods/NexusMods.App#629]
# User story

**As a** linux\* user **I want to** manage games installed via [Heroic Games Launcher](https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher), 
**So that** I can modify games purchased on GOG, Epic, & Amazon on linux.

_\* Heroic is actually cross-platform, some Windows/Mac users may also prefer using Heroic over the official Epic/GoGGalaxy stores._

## Requirements
- Detect games installed into the _default_ heroic paths
- Check heroic's config to find other game install paths
- Or perhaps allow users to manually configure where to look for Heroic installs in the NM App?
- Able to launch the discovered games

## DOD
Games installed via Heroic should be discovered in the same way as games installed via other launchers such as Steam.

## Additional note

Heroic makes use of store-specific tools ([Legendary](https://github.com/derrod/legendary),  [gogdl](https://github.com/Heroic-Games-Launcher/heroic-gogdl) & [Nile](https://github.com/imLinguin/nile)). Perhaps it will also be possible to discover/manage/launch games installed directly using these lower level tools?

**Comment by EzioTheDeadPoet** [comment]
Probably an issue more suited for the library used for finding (which is the 1st step for managing games) the games. 
https://github.com/erri120/GameFinder

**Comment by MattSturgeon** [comment]
> Probably an issue more suited for the library used for finding (which is the 1st step for managing games) the games. [erri120/GameFinder](https://github.com/erri120/GameFinder)

Great thanks. Upstream issue opened as https://github.com/erri120/GameFinder/issues/108

**Comment by erri120** [comment]
This will be handled in https://github.com/erri120/GameFinder/issues/108.
