### ISSUE TITLE
Rewrite `GenericFolderMatchInstaller` to simplify logic using `FileTreeNode`

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#647]
The `GenericFolderMatchInstaller` was written before `FileTreeNode` was created, so it had to deal with a flat list of files instead of a tree structure.

This made the `GenericFolderMatchInstaller` logic complicated. With the introduction of FileTreeNode, a lot of the logic can now be greatly simplified.
This should make the code easier to understand and easier to maintain in the future.

**Comment by Sewer56** [comment]
This was completed by @Al12rs and @Sewer56 (me) over the course of time since.

Originally the implementation moved to `FileTreeNode`, and more recently it was rewritten in the new `Trees` system within the `Paths` library.
