### ISSUE TITLE
As a user, I want to view a list of mods

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#65]
## User Story

As a user, I want to

## Requirements

**Must haves:**  

View a list of all added mods

**Won't haves:**
- Sort
- Filters
- Actions

**Notes:**

"Toggle" component is in the process of being redesigned for NMA, if there is an out of the box toggle available in Avalonia please go ahead and use that rather then creating our current, soon to be outdated, toggles from scratch. 

We will not implement the 'Used by' column as part of this issue.

## Designs

[Figma](https://www.figma.com/file/Ntr9PttR5VrqpTRwwZHzLu/Mod-list?node-id=48%3A3075&t=7JcghBzAi7a0GeXe-1)

![image](https://user-images.githubusercontent.com/118466382/222426443-2cf50fad-e326-44ae-b6c4-614a7368f134.png)

### Scenario 1

**Given**
I open NMA and select a game

**When**
I select "Mods" from the left menu

**Then**
I am shown a list of added mods

**Comment by halgari** [comment]
Implemented in #236, minus the collections link button, which we don't have yet because we don't have collections
