### ISSUE TITLE
Make Game Folder indexing multithreaded again

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#654]
#615 Changed the indexing of the game folder to be single threaded, to avoid overcomplicating things.
This should be made multi threaded again at some point, maybe after moving to NX archives (#640)

**Comment by Sewer56** [comment]
@halgari solved this a while back when rewriting the Loadout Synchronizer.

https://github.com/Nexus-Mods/NexusMods.App/blob/d6e79c9aed70ec84adc11f11c88c905e9d2dc533/src/NexusMods.DataModel/FileHashCache.cs#L85
