### ISSUE TITLE
View mod content (files/folders)

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#694]
# Improvement

## Currently 
_(Describe the current behaviour of the existing feature you want to improve)_

## We want
_(Describe the new behaviour you want to see for this feature)_

## Supporting Information
_(Include any supporting screenshots etc to support the above)_

## Design
_(Any designs to required for this feature)_

**Comment by BellCubeDev** [comment]
I have a more filled-out story for file & dir previews at #229

**Comment by Greg-Nexus** [comment]
Nice, I'll close this.
