### ISSUE TITLE
Convert AdvancedInstaller projects

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#703]
The AdvancedInstaller projects currently use custom properties and imports:

https://github.com/Nexus-Mods/NexusMods.App/blob/main/src/Games/NexusMods.Games.AdvancedInstaller/NexusMods.Games.AdvancedInstaller.csproj

https://github.com/Nexus-Mods/NexusMods.App/blob/main/tests/Games/NexusMods.Games.AdvancedInstaller.Tests/NexusMods.Games.AdvancedInstaller.Tests.csproj

Results in https://github.com/Nexus-Mods/NexusMods.App/pull/702#issuecomment-1752557078 https://github.com/Nexus-Mods/NexusMods.App/pull/686#issuecomment-1742643932 https://github.com/Nexus-Mods/NexusMods.App/pull/662#issuecomment-1733250710.

**Comment by erri120** [comment]
@Al12rs @Sewer56

**Comment by Sewer56** [comment]
Just an oversight, I'll fix this on UI branch
