### ISSUE TITLE
Setup basic App layout ready for workspaces/panels

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#706]
# Chore

## Requirements

The basic layout and structure of the App needs updating to ensure:

1. we are accurately reflecting features and functionality that are available to users.
2. existing pages are in a layout that is compatible with workspaces/panels

We will be removing:

- the 'Newsfeed' page and left-menu item, defaulting the "Home" page to 'My Games'.
- the 'Browse Games' page and left-menu item.
- the 'Search' bar from the UI.
- the 'Help' icon from the UI.
- the 'Settings' icon from the UI.
- the 'Home' icon from the spine menu.

We will be adjusting the layout of the menus (top, left and spine) so that they work with workspaces/panels.

Further issues will be moving existing pages into workspaces/panels, for the purposes of this issue these pages can be kept largely the same and moved into a container.

## Design

Stripped down layouts are now available in Figma, these layouts will only show functionality that is either completed or in progress:

https://www.figma.com/file/RGRSmIC4KoVlIosQB5YmQY/%F0%9F%A7%B1-App-components?type=design&node-id=974%3A23861&mode=design&t=ddCwpiM7OsZ7nks2-1

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/c36ef25f-8541-446d-8f56-01346dfaac76)

Going forward placeholder content will be marked with a red cross pattern to clearly indicate that it is not to be built. These frames will also be labelled "Placeholder content - ignore"

![Image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/64de7369-9323-4a8e-902e-a03b825b0632)

## Acceptance Criteria

**Comment by Pickysaurus** [comment]
Can we please make sure "Plugins" is called "Load order"? 

That way it can be generic across all games with load order-able entries rather than specific to Bethesda titles.
