### ISSUE TITLE
Upgrade to .NET 8

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#707]
Docs:
- [What's new](https://learn.microsoft.com/en-us/dotnet/core/whats-new/dotnet-8)
- [Breaking changes](https://learn.microsoft.com/en-us/dotnet/core/compatibility/8.0)

Impact on our code:

- All:
  - New [Version requirements](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/version-requirements)
  - ['dotnet pack' uses Release configuration](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-pack-config)
  - ['dotnet publish' uses Release configuration](https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/dotnet-publish-config)
- `NexusMods.Paths`: [GetFolderPath behavior on Unix](https://learn.microsoft.com/en-us/dotnet/core/compatibility/core-libraries/8.0/getfolderpath-unix).
- `NexusMods.Networking.NexusWebApi.NMA`: [Microsoft.AspNetCore.WebUtilities](https://www.nuget.org/packages/Microsoft.AspNetCore.WebUtilities/8.0.0-rc.2.23480.2) can now be used.
- more to come

**Comment by erri120** [comment]
```
NETSDK1206: Found version-specific or distribution-specific runtime identifier(s): alpine-arm, alpine-arm64, alpine-x64. Affected libraries: SQLitePCLRaw.lib.e_sqlite3.
In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.
```

**Comment by halgari** [comment]
This is done, we have some tickets for some other small issues
