### ISSUE TITLE
Download with mod manager hang for non non logged in users

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#760]
# Bug Report
This happened during SprintDemo.
If user isn't logged in the nxm download hangs at 0%

## Steps to Reproduce

1. Open the App
2. Make sure you're logged out
3. Go to Nexus Mods
4. Attempt to download a mod via the App
5. Go to your downloads in the App
6. See "Unknown NXM Mod" and no download progress

## What is the expected result?

We should intercept the user between Steps 4 and 5, prompting them to login in order to continue.

We should also not queue downloads, the App can currently get into a state where downloads are stuck indefinitely.

## Supporting information
![Unknown Downloads](https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/55cb40d7-59a7-45c7-af05-78ba285c50cc)

## Designs

[Figma link](https://www.figma.com/design/7HwK7ibw0X3VgmjRwuf6m8/%F0%9F%93%B1%F0%9F%9A%80-Startup-messages?node-id=250-137&t=8vFF3ZFviAdGdNVL-1)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/2e084d89-f428-4329-b77c-c35533774984)

**Comment by captainsandypants** [comment]
@LukeNexusMods @Al12rs Are we planning to do this for Alpha? In other words do you need a design ASAP?

**Comment by Al12rs** [comment]
I was looking at the code, I'm not sure we can add a modal or something like that at least not without it being a horrible hack. 
I can make it so the download doesn't show up, but I don't know about informing the user of the problem apart from logging it for now. 
The backend is the one knowing about the issue, and the backend really should not be trying to open modal dialogs, if it even works in the first place

**Comment by captainsandypants** [comment]
As agreed, we'll create a new modal to prompt for login for the Alpha release. Improved login experience to be designed in a separate ticket and scheduled in.

**Comment by erri120** [comment]
> As agreed, we'll create a new modal to prompt for login for the Alpha release. Improved login experience to be designed in a separate ticket and scheduled in.

Do we have a design for that? Also, do you really mean "modal" or overlay?

**Comment by erri120** [comment]
The easiest approach would be to open an overlay when the app starts to prompt the user to login. Opening an overlay when the user tries to download something when not logged in is much harder and probably very hacky.

**Comment by Al12rs** [comment]
What lausandy meant was that we would show the Login overlay on startup for now. Not a new dialog. We would update the existing one.
