### ISSUE TITLE
Allow users to stop managing games

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#773]
# Improvement

## Currently 
When you go to 'My Games' and add a game, the 'Add game' button remains even though you've added the game.

## We want
When a game is currently being managed, we should change the 'Add game' button to 'Remove game'.

The icon also needs changing from a 'plus' to something else (probably a 'minus').

## Supporting Information
![Add Game Button](https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/7a5e8dce-8e85-44e7-98de-9ba84b3ebe53)

## Design
TBD

**Comment by LukeNexusMods** [comment]
I believe this was confusing people when it came to deleting mods. Because they couldnt remove a game from being managed they assumed mods were not able to be deleted.

**Comment by Sewer56** [comment]
I think this may change with further input from design. 

It's possible `Add Game` might change to `New Loadout` if a game already exists, some further discussion will be needed on this eventually. 

Good call, this issue got buried hard.

**Comment by Sewer56** [comment]
CC @captainsandypants

**Comment by captainsandypants** [comment]
The original designs cover all this, we just didn't QA.

**Comment by Al12rs** [comment]
duplicate of #1106

**Comment by Al12rs** [comment]
This was implemented by @Sewer56
