### ISSUE TITLE
Toggle icon on loadout screen doesn't always display correctly

### ISSUE THREAD

**Issue by Greg-Nexus** [Nexus-Mods/NexusMods.App#774]
# Bug Report

## Summary
The 'Toggle' icon on the loadout screen isn't displaying correctly.

## Steps to reproduce
1. Open the app.
2. Manage a game.
3. Go to your loadout.
4. Check the icon about the toggle column, see it is incorrect.
5. Resize the app window, see the icon corrects itself.

## What is the expected behaviour?
The icon displays correctly:
![Correct Icon on Loadout](https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/751990f2-bdf8-4966-9495-c16ed27e06b7)

## Other information
This is what I'm seeing most of the time:
![Wrong Icong on Loadout](https://github.com/Nexus-Mods/NexusMods.App/assets/100707075/7fcf74cd-5dcd-4b83-8aec-40b71e4f0479)

**Comment by LukeNexusMods** [comment]
Fixed
