### ISSUE TITLE
Panel resizing improvements

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#791]
- [x] Use Figma design for the styling
  - [x] small icon
  - [x] icon only visible when hovered
  - [x] mouse icon changes when hovering: `SetCursor` is not implemented on some platforms.
- [x] only one icon per axis, depending on the orientation
- [x] Rework panel creation code to take into account linked panels. Currently, the panels are always split in half. (https://github.com/Nexus-Mods/NexusMods.App/pull/813)
- [x] Rework tests. (https://github.com/Nexus-Mods/NexusMods.App/pull/813)
- [x] Figure out what to do when the orientation changes from vertical to horizontal and vise versa.

![2023-11-27_12-32-57](https://github.com/Nexus-Mods/NexusMods.App/assets/16577545/ed43c0c8-67e3-40ea-b6d8-f892a4e98b3e)

**Comment by captainsandypants** [comment]
Added designs (pretty much what you already have but smaller and added details on the gap size, cursor type change)

[Figma design](https://www.figma.com/file/VNqTTMrBsVaU2UZ9UlNsJj/%F0%9F%93%B1Panel-management?type=design&node-id=443%3A6109&mode=design&t=52PdALs4LK0c78II-1)

![image](https://github.com/Nexus-Mods/NexusMods.App/assets/118466382/e76baaff-bc01-4ad6-999c-4fb0f931e736)
