### ISSUE TITLE
Deploying one loadout triggers an ingestion in another loadout

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#871]
# Bug Report

## Summary
Trying to apply loadout A while loadout B is applied results in A throwing an error because it needs an ingest. Instead we would expect some sort of ingest of B and then A to recognize B was up-to-date and not trigger a ingest. 

Not exactly sure how this should work, I'll take a look.

**Comment by Al12rs** [comment]
Notes from meeting:
- Ingest needs to know the LoadoutId that was last applied, we can pass in a GameInstallation to help track that down.
- We should save the Last Applied Loadout ID as metadata.
- Are there any cases where we should ingest into a loadout that is different from the one that was last applied?
    - Maybe if the user clones their loadout?
    - User forgets they didn't apply new loadout before making changes, but they want to apply to the new loadout. Should still work.
    - So we might still need target LoadoutId to handle these future use cases. This will require attention to which loadout gets passed to which function, as it would mean potentially dealing with two different ones.
