### ISSUE TITLE
Moar abstractions

### ISSUE THREAD

**Issue by halgari** [Nexus-Mods/NexusMods.App#890]
# Improvement

## Currently 
A lot of code is complected in the `NexusMods.Abstractions.Games` abstraction project. It contains information about loadouts, file stores, trees, downloads, and Games

## Improvement
As of now I will split this out into the following projects

- [ ] DiskState - for hashing, caching and storing information about disk state
- [ ] Games - for game implementations, this needs references to mod files (for returning default mod file lists)
- [ ] GameLocators - This should only contain GameInstallation, GamePaths, and IStore structs 
- [ ] Loadouts - for entities and data about Loadouts, Mods, and Files, and syncronizers
- [ ] Syncronizer - the loadout Syncronizer pulls in so many other libraries we need it separate from the Loadouts
- [ ] DataModel.Entities - Likely deleted after moving the code into the other 3 abstraction libraries
- [ ] Tools? - Not sure if tools will go in Loadouts or in their own library, going to see what I think once I get to that code
- [ ] Triggers - Not directly connected to any other of the above libraries, so they get their own project

## Why?
It's hard to know where to start with the Event Store implementation because of this lack of abstraction, shouldn't be hard to pull this apart and then I can rewrite the DiskState code a bit without having to touch the other libraries.

**Comment by Al12rs** [comment]
Completed in #895
