### ISSUE TITLE
Find way to identify which the currently relevant MainWindow is when there are multiple App instances open

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#893]
# Spike

The app supports users opening multiple instances, this means that there can be multiple `MainWindows` open at the same time.

If there are multiple MainWindow open, we need a way to distinguish them from the code, so that it is possible to do stuff like changing the active Workspace on one window, while not changing it on the other window. 

This not only means that each window needs some unique identifier, but also that we need a reliable way to obtain the ID of the hosting MainWindow from most places in the code, without having to pass it down everywhere of course.

The main issue we have is that our Services are Singletons, while for some case we would actually want to get a separate instance of the service for each active MainWindow. An example is the `WorkspaceController`, where we would like to have one for each MainWindow, but still be able to access this through Dependency Injection instead of passing it down.

## Supporting Information
Depending on OS implementation, each Window should either be a separate process or separate thread, this could potentially be used to identify the "current" window. Investigation is required to identify the best way to solve this.

**Comment by erri120** [comment]
Things to investigate:

- using the process ID
- using the thread ID
- using `ThreadStatic`

**Comment by Al12rs** [comment]
A solution was adopted in #898
It is based on obtaining the currently active window in moments where the the window should be guaranteed to be the active one (a button being pressed).

Hopefully this works well enough.
