### ISSUE TITLE
Save and load workspaces

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#907]
The state of an entire workspace can be aggregated and applied using an existing method. What's currently missing is a "save" and "load" mechanism:

- Should we save all workspaces in all windows when the application closes, or when anything inside the workspaces changes?
- [ ] Add API to load workspaces given a context. This allows spine items to load saved workspaces, since they can deterministically create a context.

**Comment by Al12rs** [comment]
Note to consider Multi window:
Each window can have a different Workspace configurations while they are open at the same time, and we should not try to synchronize them while they are open.

When opening a new window thought it will use the last saved data. So if we save each time the workspaces are changed then we will get a more up to date version of the workspace, but might have many windows updating the same thing with different values frequently.

**Comment by Al12rs** [comment]
Should also save last active workspace? To continue where you left off?

**Comment by erri120** [comment]
> Should also save last active workspace? To continue where you left off? 

Yes, all of the window stuff needs to be included as well.

**Comment by Al12rs** [comment]
- Save the state of the workspaces on a MainWindow when the mainwindow closes.
- If a popped out workspace is closed by the user don't save.
- If a mainwindow is closed with some popped out workspaces attached to it, then save the popped out workspaces and open the back again when opening a new Mainwindow.
