### ISSUE TITLE
Create custom navigation control

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#942]
To make the user experience more consistent, we should develop a custom navigation control that handles navigation. Consumers of that control would only need to specify _what_ they want to do, while the navigation control handles _how_ that's going to happen.

The control should also have a context menu that may contain the following items:

- Open in new tab
- Open in new panel
- Open in new window

Avalonia already provides a [ContextMenu](https://docs.avaloniaui.net/docs/reference/controls/contextmenu) control.

**Comment by Al12rs** [comment]
This control would allow us to accept custom interactions like Middle-click, Shift-Click, etc.. inside it, avoiding having to duplicate the functionality across multiple controls.

**Comment by erri120** [comment]
Just a couple of notes and observations:

- `LoadoutLeftMenu`, `DownloadsLeftMenu`, `HomeLeftMenu`: Use `IconViewModel.Activate` for navigation. `IconViewModel` gets rendered using an invisible `Button` with an icon and text inside. The `Activate` command gets bind to that button.
- `ApplyControlViewModel`: `ApplyDiffButton` triggers navigation to the apply diff page.
- `DiagnosticListViewModel`: `SeeDetailsCommand` bound to the `EntryButton` triggers navigation.
- `LoadoutGridViewModel`: `ViewModFilesButton` opens mod info page.
- `TopBarViewModel`: `SettingsActionCommand` opens settings.

In all cases, even with the weird `LoadoutGridViewModel` implementation, a command bound to an interactive control, like a `Button`, was used for navigation. The actual navigation always happens inside the VM, never in the View.

**Comment by Al12rs** [comment]
You might want to add this to `NewTabPage` as well
