### ISSUE TITLE
Add ToolTip Styling

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#952]
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/556b9773-c72a-4c49-97c3-1b3b5ac53710)
![image](https://github.com/Nexus-Mods/NexusMods.App/assets/26797547/f67a3686-7136-4571-aa96-b63603c4547c)

Look into fixing the styles for those tooltips and see if it can't be done for all tooltips

**Comment by captainsandypants** [comment]
We can use the website designs for this:

https://www.figma.com/file/8pjtQeNggvVi7RWoLNGV80/%F0%9F%A7%B0-Nexus-Mods-Design-System?type=design&node-id=7100%3A22897&mode=design&t=OcBGuMHBuNf1keej-1
