### ISSUE TITLE
Fontconfig error during startup

### ISSUE THREAD

**Issue by l0b0** [Nexus-Mods/NexusMods.App#961]
# Bug Report

## Summary

There's several fontconfig errors with very little info during startup on Linux.

## Steps to reproduce

1. Check out https://github.com/NixOS/nixpkgs/pull/270372
2. Run `nix-build --attr pkgs.nexus-mods-app.passthru.tests.serve` (or `nix-build --attr pkgs.nexus-mods-app.passthru.tests.serve --check` if you've already built it)

## What is the expected behaviour?

No fontconfig errors.

## Other information

Log:

```console
❯ nix-build --attr pkgs.nexus-mods-app.passthru.tests.serve --check
[…]
Fontconfig error: Cannot load default config file: No such file: (null)
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
Fontconfig error: No writable cache directories
[…]
```

I've tried setting `FONTCONFIG_FILE` as in [this issue](https://github.com/NixOS/nixpkgs/issues/209525), but that doesn't seem to help.

Is it possible that the application relies on fonts already being installed on the system?

**Comment by erri120** [comment]
This might be an issue with Avalonia. We don't explicitly use fontconfig, but Avalonia is probably using it. I'd suggest looking up issues regarding Avalonia, fontconfig, and nix.

**Comment by l0b0** [comment]
> This might be an issue with Avalonia. We don't explicitly use fontconfig, but Avalonia is probably using it. I'd suggest looking up issues regarding Avalonia, fontconfig, and nix.

I couldn't find anything specific. But it also doesn't seem to happen when running on a desktop, so I'll just leave it for now.

**Comment by erri120** [comment]
> > This might be an issue with Avalonia. We don't explicitly use fontconfig, but Avalonia is probably using it. I'd suggest looking up issues regarding Avalonia, fontconfig, and nix.
> 
> I couldn't find anything specific. But it also doesn't seem to happen when running on a desktop, so I'll just leave it for now.

Were you trying to run the desktop application in an environment without a desktop? We have a CLI that you can use instead.

**Comment by l0b0** [comment]
> Were you trying to run the desktop application in an environment without a desktop? We have a CLI that you can use instead.

Yes - isn't the CLI just `NexusMods.App`?

**Comment by erri120** [comment]
> > Were you trying to run the desktop application in an environment without a desktop? We have a CLI that you can use instead.
> 
> Yes - isn't the CLI just `NexusMods.App`?

Yes, the `NexusMods.App` executable will launch the UI if no command line arguments are passed in.

I'm closing this issue as "not planned" because you can't run the UI without a desktop environment.
