### ISSUE TITLE
Regression: Opening a second instance of the App doesn't create a new Window

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#968]
Regression introduced with #877

When opening a second instance of the App the current mainwindow is brought into focus instead of creating a second main window.

Reproduced this on Windows 11.
Edit: erri confirmed same issue on Linux as well.

Use manually started instances of the App to reproduce this, starting the App with debugger makes it not reachable by normal instances of the app, meaning the bug would not reproduce.

**Comment by erri120** [comment]
The second process also doesn't exit properly.

**Comment by halgari** [comment]
likely related to this issue: https://github.com/Nexus-Mods/NexusMods.App/issues/965
