### ISSUE TITLE
Diagnostic improvements

### ISSUE THREAD

**Issue by erri120** [Nexus-Mods/NexusMods.App#977]
#327 and #362 added basic diagnostics, and #975 added a basic source generator to improve the creation of diagnostics. This issue contains various improvements for our diagnostics system.

## Rendering and Embeddings

A difficult part of diagnostics is the rendering. Using #933 to render markdown, we can create custom a superset of Markdown with custom "embeddings":

```markdown
Mod {{% ModReference ModA %}} is not compatible with {{% ModReference ModB %}}!
```

This will be stored as a string and the UI can use #933 to render this using custom Avalonia controls. Instead of having `{{% ModReference ModA %}}` in the text, this would be replaced with a custom Avalonia control.

A `ModReference` embedding could be a custom image button containing the icon for mods on the left and the name of the mod on the right. Clicking the button will navigate the user to the mod.

Using source generators, we can use these text embeddings to generate a data type and to verify the string.

## Description and Details

Diagnostics currently only have a `Message` property. To provide the user with more information, like how to fix the issue, it'd be better to have a short `Description` and a potentially long `Details` property. The `Description` can be shown in the UI at various places, while the `Details` property would only be shown when the user clicks on the diagnostic to get more information.

The `Details` property can potentially be very elaborate, so it should be rendered in some scrollable text block.

## Diagnostic definitions outside of code

With the source generator added in #975, we can generate diagnostics using definitions outside of code. As an example, we could have a `001_MyDiagnostic.md` file with the following contents:

```markdown
---
Source: "NexusMods.Games.Example"
ID: 1
Severity: "Critical"
Description: "Mod {{% ModReference ModA %}} is not compatible with {{% ModReference ModB %}}!"
---

Mod {{% ModReference ModA %}} is not compatible with {{% ModReference ModB %}} because {{% ModReference ModB %}} contains file {{% FileReference FileA %}} that disables {{% ModReference ModA %}}.

This can be fixed by {{% EditAction FileA "editing FileA" %}} and removing the following line:

`disabled: "ModA"`
```

This builds heavily on the previous two improvements of having embeddings and a `Details` property.

### Publish to docs

If the diagnostic definitions are inside some markdown file, we can easily generate docs for them and put them on a website. This would allow anyone to quickly link to a specific diagnostic and help other users. Ideally, users would be able to right-click a diagnostic and get a permalink to the online documentation.

### Translations

Translations could be provided by having multiple files following this schema:

- Original English version: `001_MyDiagnostic.md`
- German translation: `001_MyDiagnostic.de.md`
- Japanese translation: `001_MyDiagnostic.ja.md`

These translation files would only contain the following:

```
---
Description: "Translated description"
---

Translated details.
```

The front-matter fields like `Source`, `ID`, and `Severity` would only be used in the original file to prevent translations from randomly overwriting those values.

The downside of this approach is that translations are not accessible through resources that we currently use.

**Comment by Al12rs** [comment]
For 'Diagnostic definitions outside of code', I'm guessing that the actual logic would be defined in code using the ID to link the check logic to the details?

I agree about having a separate short `Description` and longer `Details`.

I'm not sure how far the custom markdown syntax would work, I like the final results it would offer but not sure about how well it can be used or implemented.
I'd like to discuss this in more detail in a call sometime.

**Comment by Al12rs** [comment]
Looking at the PR I understand the idea better, but am still not convinced.

To add something that wasn't mentioned here, both Vortex and MO2 Warnings/Diagnostics can show a button to try to automatically fix the issue.

Vortex in particular can have multiple buttons on the notification, allowing it to offer multiple choices to the user on how to handle the problem.

MO2 only had a AutoFix button. In there the diagnostic provider could put in whatever they wanted, even entirely new UI to handle the problem if needed, or no UI at all.

**Comment by erri120** [comment]
> Looking at the PR I understand the idea better, but am still not convinced.
> 
> To add something that wasn't mentioned here, both Vortex and MO2 Warnings/Diagnostics can show a button to try to automatically fix the issue.
> 
> Vortex in particular can have multiple buttons on the notification, allowing it to offer multiple choices to the user on how to handle the problem.
> 
> MO2 only had a AutoFix button. In there the diagnostic provider could put in whatever they wanted, even entirely new UI to handle the problem if needed, or no UI at all.

The original design for diagnostics in #327 also considered having some sort of "quick fix" button. I didn't mention fixes here because those were already mentioned in #327, and we currently don't have any diagnostics that can be fixed automatically.
