### ISSUE TITLE
Second loadout ingests previously deployed loadout as game files on creation

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#982]
### Problem:
When creating a new loadout, whatever is currently in the game folder will be considered as "Game Files" and be added to that loadout's "Game Files" mod.

### Expected behavior:
New loadout should check if another loadout is currently being deployed to the game folder and avoid ingesting its files.

Now the actual problem: What to use as the actual game files for new loadout?
- Use previously applied loadout "Game Files" mod contents:
    - Pro: simple and easy to do
    - Con: User might have modified the contents of "Game Files" in the previous loadout
    - Con: Ingested Game Update data might not be part of Game Files mod in previous loadout, resulting in missing update files in new loadout.
- Have a custom source of updated ground truth of what the game vanilla state is, that is kept up to date when the game is updated.
    - Pro: if we find a way to do this right it would greatly beneficial to know what the vanilla state of the game should be at all times.
    - Con: This might be quite tricky to implement. We should know when a game version changes, so we can have special logic in those events, but the main issue is initial detection when managing the game for the first time.

**Comment by LukeNexusMods** [comment]
@Al12rs Is this needed as part of creating multiple loadouts?

**Comment by Al12rs** [comment]
This should actually be fixed by code from @Sewer56 and halgari, but since we disabled multiple loadouts, this needs to be confirmed

**Comment by Al12rs** [comment]
So yeah put it in

**Comment by LukeNexusMods** [comment]
Did we figure out if this was fixed or not?
