### ISSUE TITLE
Apply/Ingest - Store last applied `LoadoutId` and revision ID separate from `DiskState`

### ISSUE THREAD

**Issue by Al12rs** [Nexus-Mods/NexusMods.App#985]
This is to be able to access that information without also having to load the entire `DiskState` from DB.

This can be done by having two tables:
- `<GameLocationId, DiskState>`
- `<GameLocationId, (LoadoutRevisionID, LoadoutId, more small data in the future if needed)>`

This is because with large loadouts or games with large number of files DiskState can be pretty big.

**Comment by halgari** [comment]
This will be fixed by the additional features offered by #1173 and so I should start by supporting DiskState and the FileStore
